---
datagov_app_process: web

ckan_session_store_type: memory
datagov_service: catalog

newrelic_app_name: catalog

# role url
url_readonly: "{{ catalog_url_public }}"
url_writable: "{{ catalog_url_admin }}"

# project path
project_source_rollback_path: /usr/lib/ckan-rollback
project_source_new_code_path: /usr/lib/ckan-new
current_source_symlink: /usr/lib/ckan
project_index_path: /usr/lib/ckan

# other
env: local

# max login
saml2_site_url: https://admin-catalog.data.gov/

# secrets
catalog_ckan_who_ini_secret: "{{ vault_who_ini_secret }}"
ckan_instance_secret: "{{ vault_ckan_instance_secret }}"
ckan_instance_uuid: "{{ vault_ckan_instance_secret }}"

# token_dat for Google Analytics
token_dat: "{{ vault_token_dat }}"

# Trendmicro firewall policy
trendmicro_policy_id: "{{ trendmicro_policy_id_web }}"
