---
datagov_service: inventory
app_type: inventory-next
inventory_python_home: "{{ python_home }}"
datagov_in_service: true

datapusher_build_pkg_branch: datagov/inventory-next

# Trendmicro firewall policy
trendmicro_policy_id: "{{ trendmicro_policy_id_web }}"

# db credentials
inventory_ckan_db_host: "{{ inventory_next_postgresql_login_host }}"
inventory_db_user: "{{ inventory_next_postgresql_login_user }}"
inventory_db_pass: "{{ inventory_next_postgresql_login_password }}"
#inventory_db_name: "{{ inventory_next_postgresql_db_name }}"
inventory_db_name: ckan_try_01

datastore_db_server: "{{ inventory_next_datastore_login_host }}"
#inventory_datastore_db_name: "{{ inventory_next_datastore_db_name }}"
inventory_datastore_db_name: datastore_try_01
inventory_datastore_user: "{{ inventory_next_datastore_user }}"
inventory_datastore_pass: "{{ inventory_next_datastore_pass }}"
#inventory_datastore_ro_user: "{{ inventory_next_datastore_ro_user }}"
inventory_datastore_ro_user: datastore_ro_try_01
inventory_datastore_ro_pass: "{{ inventory_next_datastore_ro_pass }}"

#inventory_datapusher_db_name: "{{ inventory_next_datapusher_db_name }}"
inventory_datapusher_db_name: datapusher_try_01
inventory_datapusher_db_user: "{{ inventory_db_user }}"
inventory_datapusher_db_pass: "{{ inventory_db_pass }}"

# other
inventory_ckan_bucket_name: "{{ inventory_next_ckan_s3_bucket_name }}"
inventory_ckan_bucket_prefix: "{{ inventory_next_ckan_s3_bucket_prefix }}"
ckan_site_domain: "{{ inventory_next_ckan_service_url }}"

inventory_app_repo_branch: inventory_ckan_2.8
newrelic_app_name: inventory-next
newrelic_enabled: true

# saml2 authentication
inventory_ckan_saml2_enabled: false
inventory_ckan_plugins_additional: [s3filestore]

# redis
inventory_ckan_redis_password: "{{ inventory_next_ckan_redis_password }}"
inventory_ckan_redis_host: "{{ inventory_next_ckan_redis_host }}"
# Requires redis due to standard EC2 redis system setup
inventory_ckan_redis_url: redis://:{{ inventory_ckan_redis_password }}@{{ inventory_ckan_redis_host }}:6379/{{ inventory_ckan_redis_db }}

# secrets
ckan_instance_secret: "{{ inventory_next_ckan_instance_secret }}"
ckan_instance_uuid: "{{ inventory_next_ckan_instance_uuid }}"
who_ini_secret: "{{ inventory_next_ckan_who_ini_secret }}"

# solr
inventory_ckan_solr_host: "{{ inventory_next_ckan_solr_host }}"
