---
# Global vars
# THESE ARE NOT DEFAULTS, THESE VARS OVERRIDE INVENTORY group_vars/*  !!!
# https://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

# catalog
catalog_ckan_python_home: "{{ common_python_version_directory }}"
ckan_uses_gunicorn: false


# Default TLS/SSL certificate used for internal traffic to host.
default_tls_host_certificate_filepath: /etc/ssl/certs/datagov_host.crt
default_tls_host_key_filepath: /etc/ssl/private/datagov_host.key

# apache2 role
apache2_ssl_certificate_file: "{{ default_tls_host_certificate_filepath }}"
apache2_ssl_certificate_key_file: "{{ default_tls_host_key_filepath }}"


# common roles
common_operators: "{{ jumpbox_operators }}"  # This is inherited from inventory variables
common_reboot_notify_email: "{{ datagov_team_email }}"
common_tls_host_key: "{{ default_tls_host_key }}"
common_tls_host_certificate: "{{ default_tls_host_certificate }}"


dashboard_php_major_minor_version: "{{ php_major_minor_version }}"


# ###########################
# site-wide datagov variables
# ###########################

datagov_support_email: datagov@gsa.gov
datagov_team_email: datagovhelp@gsa.gov

# Production operators
# This list is used to authorize operators to the BSP environments
# (production/staging). Please keep this list in alphabetical order.
datagov_operators_production:
  - username: adborden
    email: aaron.borden@gsa.gov
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFtWXnfXkTvUrcGxsColboVWfaRAB57vqA0zbsz3bHXh0XngTEaOrGiT3Eg9ep6a5YZJnsO83DIfdNllYWRE45PaJsAxcTKoBZ/KRJXCVODnj/H0CoccHFCUexOpIJWjCs4IjlGRgVnp9s7DMeh021XYVUE1CeXFFLZVLpbWpDC4PkmdolD3Lu/8LJ4YkXGSmEGvzf1eVneekW301g4fhIbI9k3zZSqknpIPjVh2ZNUNssJ0K8hRSuWbyE4neTXLUlJ9gdXLXIVbpPQW/ny56jz2h9G0ImLChHit80v19WEgCH3E84Bp7hiGz2q5tW5flTOcSluCd0n7xeD0zeh5wL datagov-adborden
  - username: cmacdermaid
    email: christopher.macdermaid@gsa.gov
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDEo6qzr/8VBbydGAmbQPFO462UtJnnOfsTGbfKb6IZOW00uFqTwqwsrrV+5pnFZN5dpKTBM+c0OLu2+aeVPmKh4fgVzFqyvoiZP609PxzQTPgUGnZjh1gpMclrXI/Vn6LtLdkwzcC3ymXlVtERF7Yvjodyari4BiVMTibY5Jb+nfElmm0oHulBzeRbfddN2GNfrcDZhIKteJPxStSWEpFR/ylJj5xiP/9KenZnIwh+wn9aoVZfwQPkAi/rqB0wslt6X2POVYK7nlmyY/EUHIih9v3YeU9F/msC3nZFOLE7csWOp7uPuRbRGwU289tR7rCWqgMnDlE6UT2B6XNtCqNTNf1y3jPrlQeB4slRB4hi2h8qZ2b6E2S5LVpfUgqSnl0OzQqJUEXTY2YN8b4qxUsBvOc8mHvGaHkNqzMxDMyCqte39FWRkLkI54aUXxhUnd3woOsf5h7h9Y0CLTeS+wnrcJJJ3MmJ1Cgrx804F+FwEYU4ZcvmdJBCpaEWKk1kiVS4a4LQ6sAkIkt4n0Mu7gytHUhlGCfx0uiGSjwN7g6SMi0wNd2DXnK/Lsle9ZqCy1hfA3uqJrH9EK8PcuttFB7KDDrXexXamlI+GGntAf7L4HmLiGQC3xZBpFITazdIvVzFodX4SjHWZRezxU2jFvu37hwJPp6oQlL1vR58W6vb4Q== christopher.macdermaid@gsa.gov
  - username: fxia
    email: fuhu.xia@gsa.gov
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3THO5PQvZoEGscVKh1RdnCEyfW62f41H8NaGNj7faV1TO2ngo1U/WyKvf1QnOanllGaPQLYeE0tsmXChz6tbKErssL04Zux+UEUfU2MHLhqsb3IkAvIKjYGIl9gvFRYDslvSxZjCXtRA+egqZlmgXpJ2+nYLMPjar3nxnN/8Je+dTIgX0EGCtOPLC8ouvSg7ZEwIf7D3C4HT/kvvGyFUDj/hUgVpxqUTaeO2ILoCgyHvAqS0hy3Fn1uStAZJ6cbub7AnmGvo4CJqamx8zVzepFBQk0+Kcsp92hXclSrsi9m/UpeCbmL0k6VbamKZHEcJUC4CfvsJ2yGT0EoMO+l5l fuhu.xia@gsa.gov
  - username: jamesbrown
    email: jbrown@xentity.com
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0hjmDjbqbRLZN7sCvztfrrOpFoNSc7o2z0sSs3i5pL3TAeySkBXvzr9i9JglRVgd8lJC+ucX9t5GBcw8PLVoaGwoErnEVLUYLsWDgn2PSCPMakffB5PB6kzgnzuxJsXRxKpU8aEUNIFi7/2W0knBiGOBS4JR06xlDngI1HhjS0Qc8ge46fYy9GVeROkW49X2J6RxwJ+nKMjs8It2uyH+tf3zeJ6YeevoruaEvCF6QuJjA06haTH4lYHJ186ql96iaMGEW4+AJTIaLHNtHGOr3kxDaS+nZUdUBJFYrthHWBUYiKxH0xxM5d+UVesv3PfZ9iemBQx2FFx/AR8/RXSed jamesbrown@pop-os
  - username: jkramer
    email: julie.kramer@civicactions.com
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDkht7dxg11wS34k+4jfvV49cSrC0jrHptZTciGMFkzHmZ2WTRmmrxwJE7RxtlW21Eu8LJVWmawUwTcW3EkaIsbKYUb13hugavUavTUZltWS8CIO8+372Uvzlva8oFxJ/vlBsEUfJxKxKvbDDF3XV1sLqE+cdh9GH0c/6Ixja8gT2+pjBeXAtCE6+TKIjblFVL4GSkDtSEqCY/KJgNRPyCx3sysA2kXQk12rDRTOTRTRL8atVk+8KqKmDlADdmKhfZm/5XBfLkB96ISzYXjVRT00j+8rx0dssr44SXYHUy9l7aOkejPJkr+h7JpAgNccEaMTNAcwauGYTLQIMjazdkF638Sugzcm8Scrj5glKIrSeutkR6WXY58xAJjf5562drjFFj+r6b+3syI0h0I23WsvTs9q/+DKimbWZXhQfGGOdb0FiaVPSCyYS0kXxHMuzgdxvadnixNWohlXuHsuvuqhjKRHQIIqBAzxtlwKGVc3rNA5eSj7BkdKvG2Go6bOD9mf6/B4z/7j113MX2cv0CpwvR3DN0Okx3E7qL0HvvaOJWMed+FNh8cBJprMUDKOa8ktON+HV3RnQIkpSvFt8KE6NjJyz5vyCZCAUVC1YrQalVSGqKtBCnWT6El6B+31a58duTksV9FyrFELImPzxP/+3F0TfrBVffA0P1edG1llw== thejuliekramer@gmail.com
  - username: mogul
    email: bret.mogilefsky@gsa.gov
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDwVi3qaiX0pd2mqRJ5hHJgbeMuU/CP6MofaFbLjafnoMo5TTgRwakH68xok5CnQ2irSJwyH0epPKz7Jvy/CvAFkVH3qGVMCHqX2+Ybfbc5cYRCFlEJ+7Gn/ONYeegM3ZJ6MqA37VRUQIcDUvx087RQHKU1VRf+2DZtz/3Lbp/sU1F+WXM45zHfO35ckHg9mQ+FzlPpJqLUi2EG1BEJyUtqjAGUWqG8oN60+71cxynhTSqiGeqShHuEV7JZFI5Z0UwyuqIUEdClFKskYYIbwYGvujqPnYQnrlGrOqqieNlJUI2C2GokpBHCrqCFy9D9+5xLVpKF7d30QePjeSKXL5Gx7wa04/0fH3gks2U8RXCJ8WBgwi+t58Yv8mIYJRIYqHp4NaD/U3JSe0/KUx12K7poERuT0YK5W4Y1YVjZCdPwTMf5PmOk3gP0JfebfZNcSiWK5bcOkwjAEg6EIrmUei/S6eErXoszpRqYbE8O3J6U7T/lvhhAOi2dDQdhk/sWPMc5mvL+TvWWTPer2tMUMPXg8otl2GGdLxFgQ8XIfl0CEW0MC4mi7BNeI+ylwVqIwcYlMBbN2jGGpZdG4+PyKrRPQdl7jMdbnfTh1u/L7aqGxIOE7cYuLxKCUc4FUH1z5HaYT4YU7zUo0pgZSNPxOpw4UG0re2Tx+Q2ElbCIVD7pdQ== bret.mogilefsky@gsa.gov
  - username: philipashlock
    email: philip.ashlock@gsa.gov
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClHMziNct6CvUS1TcGXJT2F3rJVvO/g5tEn3/dGkPczexnBNa+4NBRrqZu4+tt9nAprhNcRH37O34+749xwTFcnt7d5WgJsbnhagrShNW3FRUTwIJ22YwaK9WbOMb6aQUt8fuH9BXxwZ16TThE4aGfZm5VQ1Gg73ClWGEOe62cv2sCLAHVjL6bzlmgjvx2VNn/M49W1nIl5KnRc4JfJ9tLvKjOJqQvI0bTwsnG/I6fnv8fOIiT2fQIt0b/FNEMvJ+AgEceGycL7m5zfVbSkSmaNP2kKJx0Sa+zXZhJB92G4ybeiVo/fZbEdAgTTxJzt8SmGEESf7+KH91bOEpQUuEr philipashlock@gsa.gov
  - username: psharpe
    email: preston.sharpe@gsa.gov
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAt21OnWUEiVxc/1OxXGmePpQ7uMEqkdv0sTtbkeFnVPYR7fPL0HosFQZDzRIbkVvIsbT0e/kR0KWuwoCWsOY9Gyqg1RA20VgsmPKKVKqwIGGqSO8Ga/cWnR7b7tePMsL25KmtTo+HPVDJuEv1HJiskBESbiK/PPEXA40zwyvVg8vpqq9vs6rDoj3WONkOla+WHW7HA+ViQLnRuxdUEtClTuxCYoG3GABDlS7fTpnBK4qHngsk2ne+fgZ9d80q3+sJupbfnj15L6vl9/4hiMtyp1wrwKQ273eQ5MCmt9C63xyYvf9Ho46CJoyDd0OVJnM2G9sU/wgsw5cm3q/jyx74/w== rsa-key-20200205
  - username: srinirei
    email: srinivasu.seeram@gsa.gov
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3/rtmHLa9O+jG7Z1ZwC28pM7RWp/f2QjAy1jGsJWGcRQoIHtHlU9f2FdN+Qm3ub267O7KmxnegGZKTCHN82oEqQfu6Krl+gtgf8CGHG7NNPW23sOeiLrscAcbeHfS7OODNFaOau20XxghI/kWIeIanmMJ6ln6GE921fkcB8LbKj4Mr3o4rAFDz5dFrqMK10jS4QkgpOB7khdsqo2ygZ6rY67A15VwdmJzi6uQeUhTO0XMxdx0JYfBaNYE+npv8ijjxkI7LKvIC7Z7O1aTwXk2DxWAMMUKGAxSkliYWWPdK22Dgp/UsOpoNgjQm4WtSrzHOWWBxZ4ld2GDYfLFzLeJ srinirei@DL57-8VMSN53
  - username: twood
    email: tom.wood@civicactions.com
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCnQZMuUYNL4AMje9YL0L8pZNKoJ1b+Vbx9dH30H5ARXxWdOGmGILpMNJ7KOqPokk06fNPBV5NgohxcdzP4dq2E+7SPr4n1Oe7nYEC6wAo0A6IX2WWQ3gQzwZmi15XIohh/FGgDEUQ3NOlV65Go9mPfMNCWgmEin78cMwnyFitQJ4elk445rccbUnHDAFsoVHYoUjWosroMmTNzV1DEfO5fAX3oSOPLOB3kKyOcGhMblBhtyHtYEgok+DvjN9RJqTiM3bgvD4ApzUI7KBP/XJRrE+7iaF6U8YmRvFsLCroQdGUX4MaxkWZZSrccxCAHoDsFyPOlM8D/qfXo++q53JzudCv5fQHT1AcCkNT+POjRONgSihtsTNbtt1GXSpRG16/laSUFh/Fp5eWbQALwnZqm/CJejt/kGtHCyyTCIE6DnvdodJ752+bsCTU3tpeOOt+FjPwkT8Ejf5c5X4kXJy0NWo0PpsS6yf3DaJt246C8Jkso6kPrY2jLW65zbCqjy/lEQ7qLJrIKfcijsGz6e+i1el8UXlZXcwWBGYsY2GIZLCYdbApJ+ifn0ILl1gdWTc5Bd/1YHWSULbM71X7XksG1O9N3qDyd4hfCmakFpkf9PDBFRzCziVgAlbxht9ZFRfyYLz/UZ7viDJuee5OqWi7b30PL80IdLDneejA+eki5RQ== taw@Toms-MacBook-Pro-2.local



# Test operators
# This list is used to authorize operators to the sandbox environments.  Please
# keep this list in alphabetical order.
datagov_operators_test:
  - username: adborden
    email: aaron.borden@gsa.gov
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFtWXnfXkTvUrcGxsColboVWfaRAB57vqA0zbsz3bHXh0XngTEaOrGiT3Eg9ep6a5YZJnsO83DIfdNllYWRE45PaJsAxcTKoBZ/KRJXCVODnj/H0CoccHFCUexOpIJWjCs4IjlGRgVnp9s7DMeh021XYVUE1CeXFFLZVLpbWpDC4PkmdolD3Lu/8LJ4YkXGSmEGvzf1eVneekW301g4fhIbI9k3zZSqknpIPjVh2ZNUNssJ0K8hRSuWbyE4neTXLUlJ9gdXLXIVbpPQW/ny56jz2h9G0ImLChHit80v19WEgCH3E84Bp7hiGz2q5tW5flTOcSluCd0n7xeD0zeh5wL datagov-adborden
  - username: anuveyatsu
    email: anuar.ustayev@gmail.com
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDtEGDBwGmSC6DvaUU4gNnRbcAva+ElPRa7qCoPY0WDxHsNks4yTSSDzpX/cJgLnHupiK23BvQHC90MK3g32Z4LI2ldWuTNt00gf2qbB+fjmcibrGRmsRYqoqM1RxNtkq/U77Qh1k7NTxqw4iF1FNPJq3iCL6XAiL7jXN2JIVezt69rM1MYsEqcgrJH+hz8FNl8+zdaCgpEksrlhWZzu3s5Zyd9im8P3T7XUn+RaJa4J8fXL8Ju0cAGkn0lFUXhPtXbGkUPyM03Ja810C9vgPeIdGw8ko0VfDeC+7dVg/AXeVRTia3zA1zAim9AxpOWCVq9/rLVREktO8B7RHrcBEnC+cUrJ14h4jYA9+j7RPOvQXDeJva0ncgY0FO/37Hx00LF6/3dtiRV49uGzasFO2jzg6CP7wNSCPOpl2kNm85ziCg+jzvbmAfmW6RreXV2dv8E44sroP8z4hGgvzFEKvCJsWRcfDC3SuXwHxdxeS0+Minv6Tg94V/KNLauJtUop7ZdgG87Kwa65vgxPZr0K6JbjOVi86nPS4adB6FTZzphRY6zo1jNEVJKxxkueMJ7FeyEMHTj7f8IMSUn35sgovGyf4kPEmXr9G5chT5Y/tONdAH3Qy04QmDr8fUObK+K2jrOeoysEiMOXPmusrh+4s+KrKEuhfFMHbIR8at9B21b4w== anuar.ustayev@gmail.com
  - username: avazquez
    email: andres@data99.com.ar
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCus0kWIp+wpaIlA/B52q+cgKylBDqQqtRJ0V3fdSq0l4t0SEd8eDe/IoiALa24X1SCo4xk+e6VCZALJfUPIweJeTVCbwR71ghHHMHFZkgxQgmPBMqWun0K1p2yBi0dW4z8L8KH/STzm4bo6SpowyH3HhVo7Ta58bB896INGU+pqnFlcSNsJDv7JA9ny+KP0fVRrlIpJSDG29vC1yYnpwhh0YXskuOtWPtYoKQLOW2FT6a4ZtQhnjqStmLlcFA/vYwjMie9H++HOqmFMsdb7GCXMVEy8rU99cnJ5XLYXgW3byZ2Ckv63Tr2ZUPBJdsxnyNfmyhO8RCkD7Qp0GoVJFlNN4b+CNcqcoIR6CIQVHDBAXtvuVtmNeX8vWkaQSGtwoZYCjURAbSUTPmUX/LNahodGM/IrcLtFpli66kRDYvk390l1jYZbGuNVcTrg4ydnIl/gA4+Bt0Eo2vfUNQxc7/2KsOtYqmXMsSBL2iaWNoSNu4HKMcxYDJzN37/wTqseBXzr3YBzk0svoM8EbRaYRJy/ejBvP/fe+bjmjz6Jw8DnWTgKe9tjwarr51q3mJ7CoYJruHM46FiH/wLkcMf57mjj84h9JMy2UVu8NRkTASRFZspowpsmzaEVSqjohQ8RgNQhMPhoG51ABa0mkRC7nYR4OqtfhwieEJXfrak3kcMnw== andres@data99.com.ar
  - username: cmacdermaid
    email: christopher.macdermaid@gsa.gov
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDEo6qzr/8VBbydGAmbQPFO462UtJnnOfsTGbfKb6IZOW00uFqTwqwsrrV+5pnFZN5dpKTBM+c0OLu2+aeVPmKh4fgVzFqyvoiZP609PxzQTPgUGnZjh1gpMclrXI/Vn6LtLdkwzcC3ymXlVtERF7Yvjodyari4BiVMTibY5Jb+nfElmm0oHulBzeRbfddN2GNfrcDZhIKteJPxStSWEpFR/ylJj5xiP/9KenZnIwh+wn9aoVZfwQPkAi/rqB0wslt6X2POVYK7nlmyY/EUHIih9v3YeU9F/msC3nZFOLE7csWOp7uPuRbRGwU289tR7rCWqgMnDlE6UT2B6XNtCqNTNf1y3jPrlQeB4slRB4hi2h8qZ2b6E2S5LVpfUgqSnl0OzQqJUEXTY2YN8b4qxUsBvOc8mHvGaHkNqzMxDMyCqte39FWRkLkI54aUXxhUnd3woOsf5h7h9Y0CLTeS+wnrcJJJ3MmJ1Cgrx804F+FwEYU4ZcvmdJBCpaEWKk1kiVS4a4LQ6sAkIkt4n0Mu7gytHUhlGCfx0uiGSjwN7g6SMi0wNd2DXnK/Lsle9ZqCy1hfA3uqJrH9EK8PcuttFB7KDDrXexXamlI+GGntAf7L4HmLiGQC3xZBpFITazdIvVzFodX4SjHWZRezxU2jFvu37hwJPp6oQlL1vR58W6vb4Q== christopher.macdermaid@gsa.gov
  - username: fxia
    email: fuhu.xia@gsa.gov
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3THO5PQvZoEGscVKh1RdnCEyfW62f41H8NaGNj7faV1TO2ngo1U/WyKvf1QnOanllGaPQLYeE0tsmXChz6tbKErssL04Zux+UEUfU2MHLhqsb3IkAvIKjYGIl9gvFRYDslvSxZjCXtRA+egqZlmgXpJ2+nYLMPjar3nxnN/8Je+dTIgX0EGCtOPLC8ouvSg7ZEwIf7D3C4HT/kvvGyFUDj/hUgVpxqUTaeO2ILoCgyHvAqS0hy3Fn1uStAZJ6cbub7AnmGvo4CJqamx8zVzepFBQk0+Kcsp92hXclSrsi9m/UpeCbmL0k6VbamKZHEcJUC4CfvsJ2yGT0EoMO+l5l fuhu.xia@gsa.gov
  - username: jamesbrown
    email: jbrown@xentity.com
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0hjmDjbqbRLZN7sCvztfrrOpFoNSc7o2z0sSs3i5pL3TAeySkBXvzr9i9JglRVgd8lJC+ucX9t5GBcw8PLVoaGwoErnEVLUYLsWDgn2PSCPMakffB5PB6kzgnzuxJsXRxKpU8aEUNIFi7/2W0knBiGOBS4JR06xlDngI1HhjS0Qc8ge46fYy9GVeROkW49X2J6RxwJ+nKMjs8It2uyH+tf3zeJ6YeevoruaEvCF6QuJjA06haTH4lYHJ186ql96iaMGEW4+AJTIaLHNtHGOr3kxDaS+nZUdUBJFYrthHWBUYiKxH0xxM5d+UVesv3PfZ9iemBQx2FFx/AR8/RXSed jamesbrown@pop-os
  - username: jkramer
    email: julie.kramer@civicactions.com
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDkht7dxg11wS34k+4jfvV49cSrC0jrHptZTciGMFkzHmZ2WTRmmrxwJE7RxtlW21Eu8LJVWmawUwTcW3EkaIsbKYUb13hugavUavTUZltWS8CIO8+372Uvzlva8oFxJ/vlBsEUfJxKxKvbDDF3XV1sLqE+cdh9GH0c/6Ixja8gT2+pjBeXAtCE6+TKIjblFVL4GSkDtSEqCY/KJgNRPyCx3sysA2kXQk12rDRTOTRTRL8atVk+8KqKmDlADdmKhfZm/5XBfLkB96ISzYXjVRT00j+8rx0dssr44SXYHUy9l7aOkejPJkr+h7JpAgNccEaMTNAcwauGYTLQIMjazdkF638Sugzcm8Scrj5glKIrSeutkR6WXY58xAJjf5562drjFFj+r6b+3syI0h0I23WsvTs9q/+DKimbWZXhQfGGOdb0FiaVPSCyYS0kXxHMuzgdxvadnixNWohlXuHsuvuqhjKRHQIIqBAzxtlwKGVc3rNA5eSj7BkdKvG2Go6bOD9mf6/B4z/7j113MX2cv0CpwvR3DN0Okx3E7qL0HvvaOJWMed+FNh8cBJprMUDKOa8ktON+HV3RnQIkpSvFt8KE6NjJyz5vyCZCAUVC1YrQalVSGqKtBCnWT6El6B+31a58duTksV9FyrFELImPzxP/+3F0TfrBVffA0P1edG1llw== thejuliekramer@gmail.com
  - username: karlen
    email: karlen.manaseryan@datopian.com
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCoMlaICduphPVOKJEQcyq4Mn/zCu893rlRiDxFb9dneRZz3INIXdtPqVXPzRvCz/gDKU3wQA6JTrt0zlbNmazRCr52Q3mmKfMLgjVW+dT0rhOQRmz457kzwfdlgJJjpYkZeFXxiFYpXP/fECSrN/63j9oBWMpz4ioy9mOE9QiLqr1my8iVTTVjkOuhgRzI7eeUd2nqwSn/plzvKU1hA4RPMcD6JTNUz40M6XV/1Oz22hPuzhvRIWWX8K4CBYee4mhAGcIIPHZ8B8MSb9vQeUgmPPPYdCBEmBWkbs/mMzlawcL2+rnE83WAk4rLcTUOaezbiZap5K9gKDojHixhTWGMe2tfwgKW+fJISmKE45BE6FlWetA5lKPbv6s02GbcXsce9h20UGLAiNJBuC9fC6A/HwFPkSmrWXvCuL1cSLbDSz7Mi+J4zNhl4brAXx3P+cZGse/d4XF4gQkZq7z2McJGeFyx07bEL2AWto9oeD+5E0fWk3xpaGl8IZAE0LvHu3ixrIwia8I3j6NzYPIa59UakusE5RYUzKNg76g+qx8goofk9+gi3tJhp+TJ8vxO7veb7seJF6SsR0ZfldPunbVM1sIW15vQSMaHD6mjBngE1/wwiJZFsozdxFPoIR7gnX6nST23n2HEMimdqRXE0MEU4MS3p2QFzd5tSVndDymhTQ== kmanaseryan@gmail.com
  - username: mogul
    email: bret.mogilefsky@gsa.gov
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDwVi3qaiX0pd2mqRJ5hHJgbeMuU/CP6MofaFbLjafnoMo5TTgRwakH68xok5CnQ2irSJwyH0epPKz7Jvy/CvAFkVH3qGVMCHqX2+Ybfbc5cYRCFlEJ+7Gn/ONYeegM3ZJ6MqA37VRUQIcDUvx087RQHKU1VRf+2DZtz/3Lbp/sU1F+WXM45zHfO35ckHg9mQ+FzlPpJqLUi2EG1BEJyUtqjAGUWqG8oN60+71cxynhTSqiGeqShHuEV7JZFI5Z0UwyuqIUEdClFKskYYIbwYGvujqPnYQnrlGrOqqieNlJUI2C2GokpBHCrqCFy9D9+5xLVpKF7d30QePjeSKXL5Gx7wa04/0fH3gks2U8RXCJ8WBgwi+t58Yv8mIYJRIYqHp4NaD/U3JSe0/KUx12K7poERuT0YK5W4Y1YVjZCdPwTMf5PmOk3gP0JfebfZNcSiWK5bcOkwjAEg6EIrmUei/S6eErXoszpRqYbE8O3J6U7T/lvhhAOi2dDQdhk/sWPMc5mvL+TvWWTPer2tMUMPXg8otl2GGdLxFgQ8XIfl0CEW0MC4mi7BNeI+ylwVqIwcYlMBbN2jGGpZdG4+PyKrRPQdl7jMdbnfTh1u/L7aqGxIOE7cYuLxKCUc4FUH1z5HaYT4YU7zUo0pgZSNPxOpw4UG0re2Tx+Q2ElbCIVD7pdQ== bret.mogilefsky@gsa.gov
  - username: psharpe
    email: preston.sharpe@gsa.gov
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAt21OnWUEiVxc/1OxXGmePpQ7uMEqkdv0sTtbkeFnVPYR7fPL0HosFQZDzRIbkVvIsbT0e/kR0KWuwoCWsOY9Gyqg1RA20VgsmPKKVKqwIGGqSO8Ga/cWnR7b7tePMsL25KmtTo+HPVDJuEv1HJiskBESbiK/PPEXA40zwyvVg8vpqq9vs6rDoj3WONkOla+WHW7HA+ViQLnRuxdUEtClTuxCYoG3GABDlS7fTpnBK4qHngsk2ne+fgZ9d80q3+sJupbfnj15L6vl9/4hiMtyp1wrwKQ273eQ5MCmt9C63xyYvf9Ho46CJoyDd0OVJnM2G9sU/wgsw5cm3q/jyx74/w== rsa-key-20200205
  - username: srinirei
    email: srinivasu.seeram@gsa.gov
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3/rtmHLa9O+jG7Z1ZwC28pM7RWp/f2QjAy1jGsJWGcRQoIHtHlU9f2FdN+Qm3ub267O7KmxnegGZKTCHN82oEqQfu6Krl+gtgf8CGHG7NNPW23sOeiLrscAcbeHfS7OODNFaOau20XxghI/kWIeIanmMJ6ln6GE921fkcB8LbKj4Mr3o4rAFDz5dFrqMK10jS4QkgpOB7khdsqo2ygZ6rY67A15VwdmJzi6uQeUhTO0XMxdx0JYfBaNYE+npv8ijjxkI7LKvIC7Z7O1aTwXk2DxWAMMUKGAxSkliYWWPdK22Dgp/UsOpoNgjQm4WtSrzHOWWBxZ4ld2GDYfLFzLeJ srinirei@DL57-8VMSN53
  - username: twood
    email: tom.wood@civicactions.com
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCnQZMuUYNL4AMje9YL0L8pZNKoJ1b+Vbx9dH30H5ARXxWdOGmGILpMNJ7KOqPokk06fNPBV5NgohxcdzP4dq2E+7SPr4n1Oe7nYEC6wAo0A6IX2WWQ3gQzwZmi15XIohh/FGgDEUQ3NOlV65Go9mPfMNCWgmEin78cMwnyFitQJ4elk445rccbUnHDAFsoVHYoUjWosroMmTNzV1DEfO5fAX3oSOPLOB3kKyOcGhMblBhtyHtYEgok+DvjN9RJqTiM3bgvD4ApzUI7KBP/XJRrE+7iaF6U8YmRvFsLCroQdGUX4MaxkWZZSrccxCAHoDsFyPOlM8D/qfXo++q53JzudCv5fQHT1AcCkNT+POjRONgSihtsTNbtt1GXSpRG16/laSUFh/Fp5eWbQALwnZqm/CJejt/kGtHCyyTCIE6DnvdodJ752+bsCTU3tpeOOt+FjPwkT8Ejf5c5X4kXJy0NWo0PpsS6yf3DaJt246C8Jkso6kPrY2jLW65zbCqjy/lEQ7qLJrIKfcijsGz6e+i1el8UXlZXcwWBGYsY2GIZLCYdbApJ+ifn0ILl1gdWTc5Bd/1YHWSULbM71X7XksG1O9N3qDyd4hfCmakFpkf9PDBFRzCziVgAlbxht9ZFRfyYLz/UZ7viDJuee5OqWi7b30PL80IdLDneejA+eki5RQ== taw@Toms-MacBook-Pro-2.local

inventory_ckan_plugins_default:
  - datajson
  - datapusher
  - datastore
  - dcat_usmetadata
  - googleanalyticsbasic
  - recline_view
  - stats
  - text_view
  - usmetadata


# jenkins
jenkins_config: "{{ lookup('template', 'jenkins_config.yml.j2') }}"
jenkins_home: /data/jenkins
jenkins_jobs:
  - name: deploy-ci-platform
    git_url: https://github.com/gsa/datagov-deploy.git
    git_ref: refs/heads/develop
  - name: deploy-ci-app-catalog
    git_url: https://github.com/gsa/catalog-app.git
  - name: deploy-ci-app-catalog-next
    git_url: https://github.com/gsa/catalog.data.gov.git
    github_project_url: https://github.com/gsa/datagov-ckan-multi
  - name: deploy-ci-app-dashboard
    git_url: https://github.com/gsa/project-open-data-dashboard.git
  - name: deploy-ci-app-inventory
    git_url: https://github.com/gsa/inventory-app.git
  - name: deploy-ci-app-inventory-next
    git_url: https://github.com/gsa/inventory-app.git
    git_ref: refs/heads/inventory_ckan_2.8
  - name: deploy-ci-app-wordpress
    git_url: https://github.com/gsa/datagov-wp-boilerplate.git


# Limit SSH Access
jumpbox_ips:
  - "10.0.0.0/8"
  - "127.0.0.1"


# newrelic monitoring
newrelic_environment: "{{ datagov_environment | default('unknown') }}"
nrinfragent_config:
  license_key: "{{ newrelic_license_key }}"
  collector_url: https://gov-infra-api.newrelic.com
  command_channel_url: https://gov-infrastructure-command-api.newrelic.com
  identity_url: https://gov-identity-api.newrelic.com
  custom_attributes:
    environment: "{{ datagov_environment | default('unknown') }}"
    service: "{{ datagov_service | default('unknown') }}"


# monit settings
monit_apache2_mem_threshold: 82


# Nginx
nginx_remove_default_vhost: true
nginx_ppa_use: true
nginx_ppa_version: stable
nginx_extra_conf_options: |-
  include /etc/nginx/modules-enabled/*.conf;


# PHP
php_enable_php_fpm: true
php_expose_php: 0
php_fpm_pm_max_children: 200
php_fpm_pm_max_spare_servers: 20
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_start_servers: 15
php_max_execution_time: 300
php_memory_limit: 2048M
php_opcache_conf_filename: "10-opcache.ini"
php_webserver_daemon: nginx
php_major_minor_version: 7.3
php_default_version_debian: "{{ php_major_minor_version }}"
php_mysql_package: "php{{ php_major_minor_version }}-mysql"

# for php-versions role
php_version: "{{ php_major_minor_version }}"

# postfix
postfix_inet_interfaces: loopback-only  # only listen on loopback interfaces, we don't accept remote mail from remote sources.
postfix_smtpd_tls_key_file: "{{ default_tls_host_key_filepath }}"
postfix_smtpd_tls_cert_file: "{{ default_tls_host_certificate_filepath }}"


# pyenv
pyenv_update_git_install: true


# solr
solr_home: /data/solr5
solr_version: 5.5.5
solr_port: "8983"

# new python version
common_python_version_directory: /usr/local/lib/python{{ common_python_version_number }}
python_home: "{{ common_python_version_directory }}"

# Disabling MySQL server (we need only client on this machine)
mysql_enabled_on_startup: false

# Disable ipv6 checks in gsa.ansible-os-ubuntu-16 which is not configured
ubu16gsa_ipv6_configured: false

wordpress_php_major_minor_version: "{{ php_major_minor_version }}"
