---
# Global vars
# THESE ARE NOT DEFAULTS, THESE VARS OVERRIDE INVENTORY group_vars/*  !!!
# https://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

# Operators for production and staging environments (GSA environments)
datagov_operators_production: "{{ vault_datagov_operators_production }}"
# Operators for test and sandbox environments
datagov_operators_test: "{{ vault_datagov_operators_test }}"


# catalog
catalog_ckan_python_home: "{{ common_python_version_directory }}"


# Default TLS/SSL certificate used for internal traffic to host.
default_tls_host_certificate_filepath: /etc/ssl/certs/datagov_host.crt
default_tls_host_key_filepath: /etc/ssl/private/datagov_host.key

# apache2 role
apache2_ssl_certificate_file: "{{ default_tls_host_certificate_filepath }}"
apache2_ssl_certificate_key_file: "{{ default_tls_host_key_filepath }}"

# common roles
common_operators: "{{ jumpbox_operators }}"  # This is inherited from inventory variables
common_reboot_notify_email: "{{ datagov_team_email }}"
common_tls_host_key: "{{ default_tls_host_key }}"
common_tls_host_certificate: "{{ default_tls_host_certificate }}"


dashboard_php_major_minor_version: "{{ php_major_minor_version }}"


# site-wide datagov variables
datagov_support_email: datagov@gsa.gov
datagov_team_email: datagovhelp@gsa.gov

# newrelic monitoring
nrinfragent_config:
  license_key: "{{ vault_nrinfragent_license_key }}"
  custom_attributes:
    environment: "{{ datagov_environment | default('unknown') }}"
    service: "{{ datagov_service | default('unknown') }}"

# Nginx
nginx_remove_default_vhost: true
nginx_ppa_use: true
nginx_ppa_version: stable
nginx_extra_conf_options: |-
  include /etc/nginx/modules-enabled/*.conf;


# PHP
php_enable_php_fpm: true
php_expose_php: 0
php_fpm_pm_max_children: 200
php_fpm_pm_max_spare_servers: 20
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_start_servers: 15
php_max_execution_time: 300
php_memory_limit: 2048M
php_opcache_conf_filename: "10-opcache.ini"
php_webserver_daemon: nginx
php_major_minor_version: 7.3
php_default_version_debian: "{{ php_major_minor_version }}"
php_mysql_package: "php{{ php_major_minor_version }}-mysql"

# for php-versions role
php_version: "{{ php_major_minor_version }}" 

# solr
solr_home: /data/solr5
solr_version: 5.5.5
solr_port: "8983"

# new python version
common_python_version_directory: /usr/local/lib/python{{ common_python_version_number }}
python_home: "{{ common_python_version_directory }}"

# Disabling MySQL server (we need only client on this machine)
mysql_enabled_on_startup: false

# Disable ipv6 checks in gsa.ansible-os-ubuntu-16 which is not configured
ubu16gsa_ipv6_configured: false

wordpress_php_major_minor_version: "{{ php_major_minor_version }}"
