---
# Global vars
# THESE ARE NOT DEFAULTS, THESE VARS OVERRIDE INVENTORY group_vars/*  !!!
# https://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

# Default TLS/SSL certificate used for internal traffic to host.
default_tls_host_certificate_filepath: /etc/ssl/certs/datagov_host.crt
default_tls_host_key_filepath: /etc/ssl/private/datagov_host.key

# apache2 role
apache2_ssl_certificate_file: "{{ default_tls_host_certificate_filepath }}"
apache2_ssl_certificate_key_file: "{{ default_tls_host_key_filepath }}"

# common roles
common_tls_host_key: "{{ default_tls_host_key }}"
common_tls_host_certificate: "{{ default_tls_host_certificate }}"

# site-wide datagov variables
datagov_support_email: datagov@gsa.gov
datagov_team_email: datagovhelp@gsa.gov

# newrelic monitoring
nrinfragent_config:
  license_key: "{{ vault_nrinfragent_license_key }}"
  custom_attributes:
    environment: "{{ datagov_environment | default('unknown') }}"
    service: "{{ datagov_service | default('unknown') }}"

# Nginx
nginx_remove_default_vhost: true
nginx_ppa_use: true
nginx_ppa_version: stable
nginx_extra_conf_options: |-
  include /etc/nginx/modules-enabled/*.conf;


# PHP
php_enable_php_fpm: true
php_expose_php: 0
php_fpm_pm_max_children: 200
php_fpm_pm_max_spare_servers: 20
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_start_servers: 15
php_max_execution_time: 300
php_memory_limit: 2048M
php_opcache_conf_filename: "10-opcache.ini"
php_webserver_daemon: nginx


# new python version
common_python_version_number: 2.7.10
common_python_version_directory: /usr/local/lib/python{{ python_version_number }}
python_home: "{{ common_python_version_directory }}"

# Disabling MySQL server (we need only client on this machine)
mysql_enabled_on_startup: false


# This should probably be environment specific
jumpbox_operators:
  - username: adborden
    email: aaron.borden@gsa.gov
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFtWXnfXkTvUrcGxsColboVWfaRAB57vqA0zbsz3bHXh0XngTEaOrGiT3Eg9ep6a5YZJnsO83DIfdNllYWRE45PaJsAxcTKoBZ/KRJXCVODnj/H0CoccHFCUexOpIJWjCs4IjlGRgVnp9s7DMeh021XYVUE1CeXFFLZVLpbWpDC4PkmdolD3Lu/8LJ4YkXGSmEGvzf1eVneekW301g4fhIbI9k3zZSqknpIPjVh2ZNUNssJ0K8hRSuWbyE4neTXLUlJ9gdXLXIVbpPQW/ny56jz2h9G0ImLChHit80v19WEgCH3E84Bp7hiGz2q5tW5flTOcSluCd0n7xeD0zeh5wL datagov-adborden
  - username: jjediny
    email: john.jediny@gsa.gov
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDWkYdnJm6FIQ6JgtNRmBEfNBtL6Y3yqX0waHHybaQnQyvJvd+VaU5dX0ad0tTwTRUPhy9yZN/kWRLdeYFOg4akkTnL6CAvPbjU67QAMGIXJpzz29+GIVWWWqhQbEFvvLG6nUdFGCBpRd0AiPUUn7gLYqbE/SvS0M9kdkBtpz+z/ZbiEVjUmGkugInhbPcl4sSdlaJULmq8vWHLTga/+PX+1VbE4L/h2gBpQutntws81WUb+Lmb8pXJSUmbsKX2KW9Jt11rZKI4Tk9PMw1qogj8Y7uY5jr6QUtC+6uBjP/etTPHF/1rc4ozesbCYFtK1zmaD+l3/pzXudKhGO5FKBwRxS9sAfM2ZC60XuZDBUZY4fqTsRnovO23dEBtkemEBjqJ6ZzxSXzRZ5KTBISOYGiZSHuc7tTiUeK22Xe0u3AEitnV3+t/VBpAgpG9/VIy4DF1qVCsQ5QR4Zw5kfXUHHHlxGZBnpC8R0TI2cBATB7FRnIQSzj/LhQi3gvZAhCIOUyPuAukwyFGedsBgr6dudqDeHkHAdNTEX2QxYKJhFUqkCBVBQMaWGTL91YZSzzbSQM5W8URAaK4c8Jk2/E1/ycO6dHT2fwP9vKQBZNerRI0h+i7L+SL24upN8BHQMnd+m9l4hQtsfXYGSAqapiOnp5xA7pzpoxCp/GTVq/uf9hSfw== john.jediny@gsa.gov

