---
# In sandbox, we use python3 on bionic web hosts
# https://github.com/GSA/datagov-infrastructure-modules/issues/32
ansible_python_interpreter: /usr/bin/python3

datagov_service: inventory-next
app_type: inventory-next
inventory_db_name: inventory_db_next
inventory_python_home: "{{ python_home }}"
datagov_in_service: true

datapusher_build_pkg_branch: datagov/inventory-next

# Inventory Datapusher
inventory_datastore_ro_user: datastore_ro
inventory_datastore_user: datastore

# db credentials
inventory_ckan_db_host: "{{ inventory_next_postgresql_login_host }}"
inventory_db_user: "{{ inventory_next_postgresql_login_user }}"
inventory_db_pass: "{{ inventory_next_postgresql_login_password }}"
datastore_db_server: "{{ inventory_next_postgresql_login_host }}"
inventory_datapusher_db_pass: "{{ inventory_next_datapusher_db_pass }}"
inventory_datastore_pass: "{{ inventory_next_datastore_pass }}"
inventory_datastore_ro_pass: "{{ inventory_next_datastore_ro_pass }}"

# other
inventory_ckan_bucket_name: "{{ inventory_next_ckan_s3_bucket_name }}"
inventory_ckan_bucket_prefix: "{{ inventory_next_ckan_s3_bucket_prefix }}"
ckan_site_domain: "{{ inventory_next_ckan_service_url }}"

inventory_app_repo_branch: fcs
newrelic_app_name: inventory-next

inventory_ckan_plugins_additional: [saml2auth s3filestore]
inventory_ckan_plugins_first: [datagov_inventory]

# saml2 authentication
inventory_ckan_saml2_enabled: true
ckan_production_ini_template: inventory-next/etc_ckan_production.ini.j2
inventory_ckan_who_ini_path: inventory-next/etc_ckan_who.saml2.ini.j2

# login.gov identity sandbox
saml2_idp_metadata_url: "https://idp.int.identitysandbox.gov/api/saml/metadata2021"
saml2_site_url: "https://inventory-next.sandbox.datagov.us/"

saml2_sp_public_certificate: "{{ vault_inventory_next_saml2_sp_public_certificate }}"
saml2_sp_private_key: "{{ vault_inventory_next_saml2_sp_private_key }}"

inventory_ckan_saml2_entity_id: "urn:gov:gsa:SAML:2.0.profiles:sp:sso:gsa:datagov-sandbox-inventory"

# redis
inventory_ckan_redis_password: "{{ inventory_next_ckan_redis_password }}"
inventory_ckan_redis_host: "{{ inventory_next_ckan_redis_host }}"
# Requires rediss due to AWS redis security configuration
inventory_ckan_redis_url: rediss://:{{ inventory_ckan_redis_password }}@{{ inventory_ckan_redis_host }}:6379/{{ inventory_ckan_redis_db }}

# secrets
ckan_instance_secret: "{{ inventory_next_ckan_instance_secret }}"
ckan_instance_uuid: "{{ inventory_next_ckan_instance_uuid }}"
who_ini_secret: "{{ inventory_next_ckan_who_ini_secret }}"
