---
default_tls_host_key: "{{ vault_default_tls_host_key }}"
default_tls_host_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIIGNzCCBB+gAwIBAgIUfahEa79Clvr81cJAUKkVNgJCuuUwDQYJKoZIhvcNAQEL
  BQAwgaoxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJEQzETMBEGA1UEBwwKV2FzaGlu
  Z3RvbjEqMCgGA1UECgwhVGVjaG5vbG9neSBUcmFuc2Zvcm1hdGlvbiBTZXJ2aWNl
  MREwDwYDVQQLDAhEYXRhLmdvdjEWMBQGA1UEAwwNZGVmYXVsdC5sb2NhbDEiMCAG
  CSqGSIb3DQEJARYTZGF0YWdvdmhlbHBAZ3NhLmdvdjAeFw0xOTExMDUxOTQ4MTda
  Fw0yMDExMDQxOTQ4MTdaMIGqMQswCQYDVQQGEwJVUzELMAkGA1UECAwCREMxEzAR
  BgNVBAcMCldhc2hpbmd0b24xKjAoBgNVBAoMIVRlY2hub2xvZ3kgVHJhbnNmb3Jt
  YXRpb24gU2VydmljZTERMA8GA1UECwwIRGF0YS5nb3YxFjAUBgNVBAMMDWRlZmF1
  bHQubG9jYWwxIjAgBgkqhkiG9w0BCQEWE2RhdGFnb3ZoZWxwQGdzYS5nb3YwggIi
  MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDXEkWPLPGdXauxNLzl5J9Ut/HE
  +a1G0KzZ9xcYPhKBaAWGJB46y3CkMD9k2qzCf5vrgfKxcuhwiVlbmcCrlIWKLLWs
  djVUNkk4Vba95mQVI/go4TC2WhaH25qP2kWX5wvpI6B/qG/V86PmH6XLsLC2yBBL
  DLQLhT5jb/0sFuEpviiify+hKtiFZHyhV47a5xuQz6qZYMI8BPWIUsbkl74TaTFw
  s/hjjYHPIUeIid3LwlEUea8/dF3cbD+7b3swSoT8se7msjUkovxp5SSJfzprfp1S
  t0i9o63GOG/aMeE2DwvKCgYx8GVkKrxhyTbrbYH2xi13bR08/LfUZ9jVV2dz69uW
  pitgtWqWzYzeTSY70nagLTulZHX7m+5GbSEgaKIbGm2QiTjfYkAz4kemmOrjSayW
  28UcfpVBBxkIwaySOZL3UQ+KGvJFKr5Gy0jKH5J9K0LJfQbPJZg5gbfqPyx+tipr
  2dxaPEZNB633drP9HcWNLbE5HyTzErKwmQdW0Ww07gZrxeDuayi/foh7E4lVhzak
  WSLP1d9uZZp32442CC4neCDYBaWQZnRc2Md1amjSL6FI25FeP6Vb6zpcckIqn1Yu
  WyFjWxZusT1gwo/gbXFxXVHB75AqEclUALmqj95sM6awrxDDMPR6ZO3+aQC7ywhQ
  badWzv7oT61mp7Dz5QIDAQABo1MwUTAdBgNVHQ4EFgQUm0TruL9qVop5y/IHZtPV
  HseKjQEwHwYDVR0jBBgwFoAUm0TruL9qVop5y/IHZtPVHseKjQEwDwYDVR0TAQH/
  BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAtewDyrN5dkawrqeYhJdK9Zkkxms3
  CvqKjf0CEMEK8XlrmG7i08NTvM0w5a/YEs8p/UmOxctdhtDw61YDpf0GcX45E9KX
  MwKDZvmTsBqo9YmOR4xopwiI36AtyDyGKTbVgc7yy1hnO5p20cNNiSGfYGPx6kR1
  a8eUgeCEdJyL0JqdAVVEI3PNU/tB+67OseGMN0gSa1cMeGi8mxCBupjwUyknvYid
  CmEv66kiGgxergqosuOYMPJryxOT/S/CF2vNOYN32xfQr2uzxsU4yJ/f4idlnLcn
  wzJMucUt86/x9uWxfMy+xnSw3auM1MBw8erec/lR9xo8jwh6CFYGxUcNdfYKZVZ2
  6fY7zOaHvPxfk0afIXGhzi7enRyu+0/FfBzgYC7sr1anFf2G6FqEeNT9dQegt88l
  vCAYe+VDcQkIpaZ1h+layoIu+P6m0udDZh24t1RI5AWgumvF21ykoB51zzDw1s5i
  W/bjymDASJAQzteJM4oEDDAF+GD0bJnmQwQgz2avO0AYluwmTbuugiP4RBJfhnLr
  OAQlJa0BAXqxMyz6WooJmQKVD6t9m+mD+uXZ1o52uxq67/YA7yquTKUPWqZ5t0IP
  HFIWJ3HiZLorJiXDwYgvTx+dYS2dlhN6GjVPvmyYogZEX3OBA63MydSSHrdkwT9h
  nT6KhbA07C76xSo=
  -----END CERTIFICATE-----

web_app_env: production
wordpress_s3_enabled: false
wordpress_saml2_enabled: false
wordpress_service_url: https://localhost:8080
jumpbox_operators: []
common_python_version_number: 2.7.10