---
# catalog
catalog_ckan_app_version: master
catalog_ckan_db_host: "{{ catalog_postgresql_login_host }}"
catalog_ckan_db_name: ckan
catalog_ckan_db_pass: "{{ vault_catalog_ckan_db_pass }}"
catalog_ckan_db_user: ckan
catalog_ckan_redis_host: catalog-harvester1tf.internal.ci.datagov.us
catalog_ckan_redis_pass: "{{ vault_catalog_ckan_redis_pass }}"
catalog_ckan_service_url: https://catalog.ci.datagov.us
catalog_ckan_solr_host: datagovsolr1tf.internal.ci.datagov.us
catalog_ckan_solr_port: "{{ solr_port }}"
catalog_postgresql_login_host: "{{ vault_catalog_postgresql_login_host }}"
catalog_postgresql_login_password: "{{ vault_catalog_postgresql_login_password }}"
catalog_postgresql_login_user: "{{ vault_catalog_postgresql_login_user }}"
catalog_pycsw_db_host: "{{ catalog_postgresql_login_host }}"
catalog_pycsw_db_name: pycsw
catalog_pycsw_db_pass: "{{ vault_catalog_pycsw_db_pass }}"
catalog_pycsw_db_user: pycsw
catalog_db_pass: "{{ catalog_ckan_db_pass }}"
catalog_db_name: "{{ catalog_ckan_db_name }}"
catalog_db_user: "{{ catalog_ckan_db_user }}"


# common
common_newrelic_enabled: false
common_python_version_number: 2.7.10
filebeat_enabled: false
nessus_agent_enabled: false
trendmicro_enabled: false
project_git_version: master

# crm
# hostname needed for smoke test, IP address needed for ALB health check
crm_nginx_server_name: crm.ci.datagov.us $hostname {{ ansible_default_ipv4.address }}
crm_service_url: https://crm.ci.datagov.us


# dashboard
# hostname needed for smoke test, IP address needed for ALB health check
dashboard_nginx_server_name: dashboard.ci.datagov.us $hostname {{ ansible_default_ipv4.address }}
dashboard_service_url: https://dashboard.ci.datagov.us


# data.gov-wide variables
datagov_enable_postgresql_role: true
datagov_environment: ci
datagov_sandbox_env: ci

default_tls_host_key: "{{ vault_default_tls_host_key }}"
default_tls_host_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIIEVTCCAz2gAwIBAgIJALhe8ZrGe78rMA0GCSqGSIb3DQEBCwUAMIHAMQswCQYD
  VQQGEwJVUzELMAkGA1UECAwCREMxEzARBgNVBAcMCldhc2hpbmd0b24xKDAmBgNV
  BAoMH0dlbmVyYWwgU2VydmljZXMgQWRtaW5pc3RyYXRpb24xKjAoBgNVBAsMIVRl
  Y2hub2xvZ3kgVHJhbnNmb3JtYXRpb24gU2VydmljZTEVMBMGA1UEAwwMKi5kYXRh
  Z292LnVzMSIwIAYJKoZIhvcNAQkBFhNkYXRhZ292aGVscEBnc2EuZ292MB4XDTE5
  MDIwOTAwMjMzNloXDTIxMDIwODAwMjMzNlowgcAxCzAJBgNVBAYTAlVTMQswCQYD
  VQQIDAJEQzETMBEGA1UEBwwKV2FzaGluZ3RvbjEoMCYGA1UECgwfR2VuZXJhbCBT
  ZXJ2aWNlcyBBZG1pbmlzdHJhdGlvbjEqMCgGA1UECwwhVGVjaG5vbG9neSBUcmFu
  c2Zvcm1hdGlvbiBTZXJ2aWNlMRUwEwYDVQQDDAwqLmRhdGFnb3YudXMxIjAgBgkq
  hkiG9w0BCQEWE2RhdGFnb3ZoZWxwQGdzYS5nb3YwggEiMA0GCSqGSIb3DQEBAQUA
  A4IBDwAwggEKAoIBAQCrvX1zkUtZyxjkniG8x8EXoFHmtm2PiavFhcs6d0W2IHPe
  jXXLUEXJb7ldwdKwi5yCTuW8J0CGoIl8EkkTy3+rQWjjS74iTvewxkcYVdHB/oXf
  wpPuL9azvX1WEekfdKCYf98D+RWnr+5XWMbXyRafI2a9yeE3et6mkeqeu4iP/8iA
  G7o/BEcLhrDFQFuzA0WQxGhajqQvSTTfjhEp2Dqq4u/Ek7DqVuf7IJ/KYt3PeGeX
  bV19LAzKt2HE5uqXSRZn0vnMRyCT9kz+yNZqUVHCzk7GE01Jl7wxTDU1cGraqrMK
  9Cg4zBNX1g3B8xucGOichpawOBiW+a5A2yhCNPzjAgMBAAGjUDBOMB0GA1UdDgQW
  BBRe5bzhJ9N8pjtAXKbwzLu6c2F4hDAfBgNVHSMEGDAWgBRe5bzhJ9N8pjtAXKbw
  zLu6c2F4hDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCdv74tZfxn
  NsfDG4SwnPvusMorYWM719wDdfXO0VIQMGcP/aRitgw6aMlHXpWltqMXOO0NyOv3
  zMbYIvTNJWRCFiOMSUSTc3UEs/Hd5/O8d31Ncqg7MJRfISlIRvjQ6FntOZ3WDmrG
  ZwnqGkfGYpj92Q2xuXDd7FjGTKXVJiwaVMkDifUe/ez74R3ltSNeohaLOkZf5Zcw
  68XH2jjigSenaTkHd8QND1yde5/ekyX7s594M5tz16Tr05Wmnf+3OSNFssooFlXY
  a6iApABZqU0Aac0KNKxx7F8BvcTfems78jd0RhKrGKD77l4VTtFb+gU2C02Abbm+
  lo4YdL0A8Y/f
  -----END CERTIFICATE-----


jenkins_admin_password: "{{ vault_jenkins_admin_password }}"
jenkins_home: /data/jenkins
jenkins_hostname: jenkins1tf.internal.ci.datagov.us
jenkins_tls_key: "{{ vault_jenkins_tls_key }}"
jenkins_tls_cert: |
  -----BEGIN CERTIFICATE-----
  MIIF5zCCA8+gAwIBAgIJAPGalCzW7H32MA0GCSqGSIb3DQEBCwUAMIGJMQswCQYD
  VQQGEwJVUzELMAkGA1UECAwCREMxEzARBgNVBAcMCldhc2hpbmd0b24xKjAoBgNV
  BAoMIVRlY2hub2xvZ3kgVHJhbnNmb3JtYXRpb24gU2VydmljZTERMA8GA1UECwwI
  RGF0YS5nb3YxGTAXBgNVBAMMEGNpLmNpLmRhdGFnb3YudXMwHhcNMTkwODE4MDY0
  MjExWhcNMjAwODE3MDY0MjExWjCBiTELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkRD
  MRMwEQYDVQQHDApXYXNoaW5ndG9uMSowKAYDVQQKDCFUZWNobm9sb2d5IFRyYW5z
  Zm9ybWF0aW9uIFNlcnZpY2UxETAPBgNVBAsMCERhdGEuZ292MRkwFwYDVQQDDBBj
  aS5jaS5kYXRhZ292LnVzMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
  yf3hvZucOevPQZq9J1Xxq77NLDM9lLV3q6JvjzS2Kjx6xhHvTct54hpXKa1Ue+li
  NFOXJfuVAxN4HLU53ZvsSPcroraUIzs/D1X+5J62TfKmNA/duoOtWj+l55mCX7UL
  n4x+aTklbbu0g9Ca1tA3u+spykBBf4tY5y+YbTaoD+JFkdh9GoZUgFWee2jq8WYK
  b8EDhx4KXWuZbGE+40pMSBEqiK7/dwsPZ21an/VXf7i0KEGmQg0mVr/4XJjsYUUo
  DgHc/ztadaMKpeZUS7p4pRH/Hs2xkw7uXNDRu7lL9sywnY36rdIR3mgIwqbxgEmm
  rHRF1IE8+f+DHxfJihJjDLipxP3FLY/yZcMFofVONxWptBaww6nrzXugYoXFkfeN
  TjvhLgi1RmN079TzhvfpxfTFe/E3+7TTJmG1G9eLpguJT7p7/MjMjBq1d5QnCT/v
  xsmhnNb2ndAjwChHz1NB4Q4kyqnAZ5TKFMWK/lKp6fV8ca0zASYRce0DkO8AOq85
  zLaO0VPTcjJ3oc514tvv8qwg9V+cZ85LQpV9/miGxvG0ajzbqedJhJUetoPYgtDv
  +I18ZTJV6SGzJwyveRPzREHFheV2ZhxImc4KEkZHuICoR6WtUUx/OST483YFJRIP
  r0tED44wzUc08T/lx5DsCq8Um0iewTdI8nc3qrdNO+UCAwEAAaNQME4wHQYDVR0O
  BBYEFC9oB6LocUJBiIA57poqyefCwJUgMB8GA1UdIwQYMBaAFC9oB6LocUJBiIA5
  7poqyefCwJUgMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAFLNJ1c6
  CFoNYOyxvgSReFYxclJDzmZ+KYHFeYzzzjQCx8VyUCnHKGVhOcoI+JtaN/YgRHxV
  420wLJfKoK6gFC3cF9hPmMVCYLNHMN76Tjbzi59KhyJl/QCYJPN5JB1targz9hYa
  6CSvrw+Fj9EbkeJJ3zoAApKVIxdrzS+c4qx+Av7YVehKBBFvUQNfelW4Cesm7EC+
  8VRv0XY0/e7lV9qD3hrp71ubIhi34hbPqGedLg5N4Fp3qUwmXeWygCPGnMOXYXwg
  LYcx6MqXXV7REJGxbOSUwkd9gkXuXn2rhvceXR0o4XSsxqJz6Qp1JSDQ9VUQI6Yh
  OWYf4n4dUHhuCOWziEub3F7tXvuNfao8NIp/3Zo4t42DfPd4EY52HMS2tA/MlDeq
  XKfKqXyjUvuD8GNhcR6d9NVa2FLVRIMdE2RLOHz+4FL9bMZ69h0cIP1mM5A6nOaC
  VhbIUZM+GnLnzmrTrISKLhMxbZNFLX+cunG/zslPRtNJ/wqvtQHaLPMm7/rkQTsQ
  jzJNh6aeWMsDa/FNNeKNCNNxgvHTEofQgjwlhCBOy/iCanLLMqvQNaC/4u50SZnd
  tZR5O+m3zP2oUaoiMP0SbxaI/IjlIIhpmDA7ixjKjvewoKtd3Aab8L61o2WZxmIs
  n00mcY+HqnIWpl6uTgqCcexzzNwVa4xJJwF5
  -----END CERTIFICATE-----
jenkins_url: https://ci.ci.datagov.us


jumpbox_operators: "{{ datagov_operators_test }}"


inventory_ckan_service_url: https://inventory.ci.datagov.us
inventory_ckan_solr_port: "{{ solr_port }}"


pycsw_app_version: datagov/v2.4.x
pycsw_base_url: https://catalog.ci.datagov.us
pycsw_catalog_url: https://catalog.ci.datagov.us
pycsw_db_host: "{{ catalog_pycsw_db_host }}"
pycsw_db_name: "{{ catalog_pycsw_db_name }}"
pycsw_db_password: "{{ catalog_pycsw_db_pass }}"
pycsw_db_user: "{{ catalog_pycsw_db_user }}"


# public urls
urls_public:
  catalog: https://catalog.{{ datagov_sandbox_env }}.datagov.us
urls_private:
  catalog: https://catalog.{{ datagov_sandbox_env }}.datagov.us

ckan_site_domain: "{{ urls_public.catalog }}"

# s3 bucket
catalog_bucket_name: "{{ vault_catalog_bucket_name }}"

# List of CodeIgniter pre-approved admin emails
codeigniter_pre_approved_admins: "{{ vault_codeigniter_pre_approved_admins }}"


# App environment
web_app_env: production
real_ansible_env: production


# newrelic
nrinfragent_license_key: "{{ vault_nrinfragent_license_key }}"


# postfix
postfix_relayhost: smtp.gsa.gov
postfix_relayhost_port: 25
postfix_sasl_auth_enable: false
postfix_relaytls: true
default_email_from: no-reply@data.gov
postfix_key: "{{ vault_postfix_key }}"
postfix_pem: "{{ vault_postfix_pem }}"


# SAML
saml2_idp_entry: login.test.max.gov
saml2_idp_metadata_url: "https://{{ saml2_idp_entry }}/idp/shibboleth"
saml_idp_cert_fprint: "67:76:BB:87:FE:76:D6:4A:BE:19:3F:E2:B6:1A:49:06:AE:56:06:B8"
saml2_sp_public_certificate: "{{ vault_saml2_sp_public_certificate }}"
saml2_sp_private_key: "{{ vault_saml2_sp_private_key }}"


# fgdc2iso service on catalog-harvester
# saxon license
saxon_license: "{{ vault_saxon_license }}"


# SecOps user
secops_user: "{{ vault_secops_user }}"
secops_user_public_key: "{{ vault_secops_user_public_key }}"


# solr
solr_master_server: datagovsolr1tf.internal.{{ datagov_sandbox_env }}.datagov.us
solr_java_packages:
  - openjdk-8-jdk


# wordpress
# hostname needed for smoke test, IP address needed for ALB health check
wordpress_nginx_server_name: wordpress.ci.datagov.us $hostname {{ ansible_default_ipv4.address }}
wordpress_service_url: https://wordpress.ci.datagov.us
