---
datagov_service: inventory

# project path
project_source_rollback_path: /usr/lib/ckan-rollback
project_source_new_code_path: /usr/lib/ckan-new
current_source_symlink: /usr/lib/ckan
project_index_path: /usr/lib/ckan

# db credentials
ckan_db_server: "{{ postgresql_login_host }}"
inventory_app_repo_branch: bionic
inventory_ckan_db_host: "{{ ckan_db_server }}"
inventory_db_user: inventory
inventory_db_pass: "{{ vault_inventory_db_pass }}"
inventory_db_name: inventory
datastore_db_server: "{{ postgresql_login_host }}"
inventory_datapusher_db_name: datapusher
inventory_datapusher_db_user: datapusher
inventory_datapusher_db_pass: "{{ vault_inventory_datapusher_db_pass }}"
inventory_datastore_db_name: datastore
inventory_datastore_user: datastore
inventory_datastore_pass: "{{ vault_inventory_datastore_db_pass }}"
inventory_datastore_ro_user: datastore_ro
inventory_datastore_ro_pass: "{{ vault_inventory_datastore_ro_db_pass }}"

# other
inventory_ckan_solr_host: datagovsolr1tf.internal.bionic.datagov.us
inventory_ckan_bucket_name: unset
inventory_ckan_bucket_prefix: unset
ckan_site_domain: https://inventory.bionic.datagov.us

postgresql_login_host: "{{ vault_postgresql_login_host }}"
postgresql_login_user: "{{ vault_postgresql_login_user }}"
postgresql_login_password: "{{ vault_postgresql_login_password }}"
# TODO is this for all databases (inventory, datastore, datapusher)?
postgresql_enable_extensions:
  - postgis

# max login
saml2_site_url: unset

# secrets
who_ini_secret: "{{ vault_inventory_ckan_who_ini_secret }}"
ckan_instance_secret: "{{ vault_inventory_ckan_instance_secret }}"
ckan_instance_uuid: "{{ vault_inventory_ckan_instance_uuid }}"
