---
ckan_session_store_type: ext:database

# server readonly/writable type
readwrite_type: writable

# db credentials
catalog_ckan_db_host: "{{ vault_catalog_ckan_db_host }}"
catalog_ckan_db_name: "{{ vault_catalog_ckan_db_name }}"
catalog_ckan_db_user: "{{ vault_catalog_ckan_db_user }}"
catalog_ckan_db_pass: "{{ vault_catalog_ckan_db_pass }}"
catalog_db_user: "{{ vault_catalog_db_user }}"
catalog_db_pass: "{{ vault_catalog_db_pass }}"
catalog_db_name: "{{ vault_catalog_db_name }}"

# other
catalog_ckan_solr_host: datagov-solrm1p.prod-ocsit.bsp.gsa.gov

# Since catalog-admin and catalog-web have the same variable precendence (and
# catalog-web wins), we override the app name here in host vars.
newrelic_app_name: catalog-admin
