---

  - name: 4.1.1 Restrict Core Dumps (Scored)
    lineinfile: dest='/etc/security/limits.conf' line="* hard core 0" state=present
    ignore_errors: True
    tags:
      - section4
      - section4.1
      - section4.1.1

  - name: 4.1.2 Restrict Core Dumps (Scored)
    sysctl: >
        name=fs.suid_dumpable
        value=0
        state=present
    when: restrict_core_dumps == True
    ignore_errors: True 
    tags:
      - section4
      - section4.1
      - section4.1.2

  - name: 4.1.4 Restrict Core Dumps (stat file) (Scored)
    stat: path='/etc/init/apport.conf'
    register: apport_present
    ignore_errors: True
    tags:
      - section4
      - section4.1
      - section4.1.4

  - name: 4.1.5 Restrict Core Dumps (Scored)
    lineinfile: >
        dest='/etc/init/apport.conf'
        line='#start on runlevel [2345]'
        state=present
        regexp='start on runlevel'
    when: apport_present.stat.exists == True
    ignore_errors: True
    tags:
      - section4
      - section4.1
      - section4.1.3

  - name: 4.1.6 Restrict Core Dumps (stat file) (Scored)
    stat: path='/etc/init/whoopsie.conf'
    register: whoopsie_present
    ignore_errors: True
    tags:
      - section4
      - section4.1
      - section4.1.4

  - name: 4.1.7 Restrict Core Dumps (Scored)
    lineinfile: >
        dest='/etc/init/whoopsie.conf'
        line='#start on runlevel [2345]'
        state=present
        regexp='start on runlevel'
    when: whoopsie_present.stat.exists == True
    ignore_errors: True
    tags:
      - section4
      - section4.1
      - section4.1.4

  - name: 4.2 Enable XD/NX Support on 32-bit x86 Systems (read dmesg) (Not Scored)
    shell: 'dmesg | grep NX'
    register: nx_result
    failed_when: nx_result.rc == 1
    changed_when: False
    ignore_errors: True
    tags:
      - section4
      - section4.2

  - name: 4.3 Enable Randomized Virtual Memory Region Placement (Scored)
    sysctl: >
       name=kernel.randomize_va_space
       value=2
       state=present
    when: enable_aslr
    ignore_errors: True
    tags:
      - section4
      - section4.3

  - name: 4.4.1 Disable Prelink (check) (Scored)
    stat: path=/usr/sbin/prelink
    register: prelink_rc
    ignore_errors: True
    tags:
      - section4
      - section4.4

  - name: 4.4.2 Disable Prelink (restore) (Scored)
    command: '/usr/sbin/prelink -ua'
    when: prelink_rc.stat.exists == True
    ignore_errors: True
    tags:
      - section4
      - section4.4

  - name: 4.4.3 Disable Prelink (remove) (Scored)
    apt: purge=yes name='prelink' state=absent
    when: prelink_rc.stat.exists == True
    ignore_errors: True
    tags:
      - section4
      - section4.4
