---

- name: Remove old datapusher code
  file: path="{{ datapusher_virtual_env }}" state=absent

- include_tasks: build-pkgs.yml
  vars:
    build_pkg_name: "{{ datapusher_build_pkg_name }}"
    build_pkg_branch: "{{ datapusher_build_pkg_branch }}"
    build_pkg_repo: "{{ datapusher_build_pkg_repo }}"
    build_pkg_requirements: "{{ datapusher_build_pkg_requirements }}"
    virtualenv: "{{ datapusher_virtual_env }}"

# TODO remove this code to resolve https://github.com/gsa/data.gov/issues/1177
- name: "Datapusher json content-type temp fix (content-type: application/json does not work now)"
  replace:
    dest: /usr/lib/datapusher/lib/python2.7/site-packages/ckanserviceprovider/web.py
    regexp: 'application/json'
    replace: 'application/x-www-form-urlencoded'
  notify: restart apache2

- name: "Remove compiled web.pyc"
  file:
    path: /usr/lib/datapusher/lib/python2.7/site-packages/ckanserviceprovider/web.pyc
    state: absent
  notify: restart apache2

- name: Add Datapusher configuration files
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: www-data
    mode: "0640"
  with_items:
    - etc/ckan/datapusher.wsgi
    - etc/ckan/datapusher_settings.py
    - etc/apache2/sites-enabled/datapusher.conf
  notify: restart apache2
