---
# catalog
catalog_ckan_app_version: master
catalog_ckan_archiver_process_count: 3
catalog_ckan_db_host: "{{ vault_catalog_ckan_db_host }}"
catalog_ckan_db_name: "{{ vault_catalog_ckan_db_name }}"
catalog_ckan_db_pass: "{{ vault_catalog_ckan_db_pass }}"
catalog_ckan_db_user: "{{ vault_catalog_ckan_db_user }}"
catalog_ckan_harvest_fetch_process_count: 6
catalog_ckan_plugins_additional: [saml2]
catalog_ckan_qa_update_process_count: 5
catalog_ckan_readwrite_configuration: readonly
catalog_ckan_saml2_enabled: true
catalog_ckan_service_url: https://catalog.data.gov
catalog_ckan_solr_port: "8983"
catalog_ckan_solr_host: datagov-solr1p.prod-ocsit.bsp.gsa.gov
catalog_ckan_wsgi_processes: 6
catalog_pycsw_db_host: "{{ vault_catalog_pycsw_db_host }}"
catalog_pycsw_db_name: "{{ vault_catalog_pycsw_db_name }}"
catalog_pycsw_db_pass: "{{ vault_catalog_pycsw_db_pass }}"
catalog_pycsw_db_user: "{{ vault_catalog_pycsw_db_user }}"


# common
common_audit_report_enabled: false
common_filebeat_logstash_output: "{{ vault_common_filebeat_logstash_output }}"
common_filebeat_config:
  filebeat.config.modules:
    enabled: true
    path: ${path.config}/modules.d/*.yml
  filebeat.modules:
    - module: system
      syslog:
        enabled: true
  output.logstash:
    hosts: ["{{ common_filebeat_logstash_output }}"]

common_newrelic_enabled: "{{ datagov_in_service | default(true) }}"
common_python_version_number: 2.7.10
filebeat_enabled: true
nessus_agent_enabled: true
trendmicro_enabled: true
# TODO prefix these with common_
filebeat_config: "{{ common_filebeat_config }}"
products:
  - filebeat


# dashboard
# hostname needed for smoke test, IP address needed for ALB health check
dashboard_nginx_server_name: labs.data.gov labs-bsp.data.gov dashboard-bsp.data.gov $hostname {{ ansible_default_ipv4.address }}
dashboard_service_url: https://labs.data.gov/dashboard
php_cli_memory_limit: 3192M

# data.gov-wide variables
datagov_environment: production


default_tls_host_key: "{{ vault_default_tls_host_key }}"
default_tls_host_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIIK4zCCCcugAwIBAgITHQAA9snRbIm3m347/wACAAD2yTANBgkqhkiG9w0BAQsF
  ADBvMRMwEQYKCZImiZPyLGQBGRYDZ292MRMwEQYKCZImiZPyLGQBGRYDZ3NhMRIw
  EAYKCZImiZPyLGQBGRYCZHMxEzARBgoJkiaJk/IsZAEZFgNlbnQxGjAYBgNVBAMT
  EUVDT0gyUy1JU1NDQTAxKDEpMB4XDTIwMDMxMTE2MjUzMFoXDTIzMDMxMTE2MjUz
  MFowgfAxCzAJBgNVBAYTAlVTMR0wGwYDVQQIExREaXN0cmljdCBvZiBDb2x1bWJp
  YTETMBEGA1UEBxMKV2FzaGluZ3RvbjEoMCYGA1UEChMfR2VuZXJhbCBTZXJ2aWNl
  cyBBZG1pbmlzdHJhdGlvbjEqMCgGA1UECxMhVGVjaG5vbG9neSBUcmFuc2Zvcm1h
  dGlvbiBTZXJ2aWNlMTMwMQYDVQQDEypjYXRhbG9nLWhhcnZlc3RlcjFwLnByb2Qt
  b2NzaXQuYnNwLmdzYS5nb3YxIjAgBgkqhkiG9w0BCQEWE2RhdGFnb3ZoZWxwQGdz
  YS5nb3YwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDcadI+mvBHg3gD
  iYwF29njwDeZnuXQW1DgBG2y0LYsdQ2CoJLY8A+vCp5mJXWrdyK75IGUY0LnxwNQ
  tklh+WnyPP8UTzrgpLzg7LlLhXXCT8cezqtCam2mDUSE9v7O/Y79tH1nwoI1r72m
  OBD62P9L7LoxvjhC5kKpU9Jy+SqekN2n74BOPqfO5C/AvvCQb05sLGbBV0lsHhYF
  TyfUdmt3ZcA3NFjpRxwKgBU3h1zjrUkT4yhUF0z2qaLgWeQ+1fq6lrb3t9WjtWkp
  Zb8BExQzVyEeoB3/VqD+8lBAQ2jVntWJOd+msxfK9kXB98qPo+SZvyefb7o2VhXZ
  oUPQ3W6JAgMBAAGjggb0MIIG8DATBgNVHSUEDDAKBggrBgEFBQcDATCCBTcGA1Ud
  EQSCBS4wggUqgipjYXRhbG9nLWhhcnZlc3RlcjJwLnByb2Qtb2NzaXQuYnNwLmdz
  YS5nb3aCKmNhdGFsb2ctaGFydmVzdGVyM3AucHJvZC1vY3NpdC5ic3AuZ3NhLmdv
  doIqY2F0YWxvZy1oYXJ2ZXN0ZXI0cC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292gipj
  YXRhbG9nLWhhcnZlc3RlcjVwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCKmNhdGFs
  b2ctaGFydmVzdGVyNnAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIkY2F0YWxvZy13
  ZWIxcC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giRjYXRhbG9nLXdlYjJwLnByb2Qt
  b2NzaXQuYnNwLmdzYS5nb3aCJWNhdGFsb2diLXdlYjFwLnByb2Qtb2NzaXQuYnNw
  LmdzYS5nb3aCJWNhdGFsb2diLXdlYjJwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aC
  JGNhdGFsb2did2ViMXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIkY2F0YWxvZ2J3
  ZWIycC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giljYXRhbG9naGFydmVzdGVyMXAu
  cHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIpY2F0YWxvZ2hhcnZlc3RlcjJwLnByb2Qt
  b2NzaXQuYnNwLmdzYS5nb3aCKWNhdGFsb2doYXJ2ZXN0ZXIzcC5wcm9kLW9jc2l0
  LmJzcC5nc2EuZ292giljYXRhbG9naGFydmVzdGVyNHAucHJvZC1vY3NpdC5ic3Au
  Z3NhLmdvdoIpY2F0YWxvZ2hhcnZlc3RlcjVwLnByb2Qtb2NzaXQuYnNwLmdzYS5n
  b3aCKWNhdGFsb2doYXJ2ZXN0ZXI2cC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292gidj
  YXRhbG9ncHViLXdlYjFwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCJmNhdGFsb2dw
  dWJ3ZWIxcC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giNjYXRhbG9nd2ViMXAucHJv
  ZC1vY3NpdC5ic3AuZ3NhLmdvdoIjY2F0YWxvZ3dlYjJwLnByb2Qtb2NzaXQuYnNw
  LmdzYS5nb3aCJWRhc2hib2FyZHdlYjFwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aC
  JWRhc2hib2FyZHdlYjJwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCJWRhdGFnb3Yt
  anVtcDJwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCJWRhdGFnb3Ytc29scjFwLnBy
  b2Qtb2NzaXQuYnNwLmdzYS5nb3aCJWRhdGFnb3Ytc29scjJwLnByb2Qtb2NzaXQu
  YnNwLmdzYS5nb3aCJmRhdGFnb3Ytc29scm0xcC5wcm9kLW9jc2l0LmJzcC5nc2Eu
  Z292giNpbnZlbnRvcnktMXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIjaW52ZW50
  b3J5LTJwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCImludmVudG9yeTFwLnByb2Qt
  b2NzaXQuYnNwLmdzYS5nb3aCImludmVudG9yeTJwLnByb2Qtb2NzaXQuYnNwLmdz
  YS5nb3aCJXdvcmRwcmVzc3dlYjFwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCJXdv
  cmRwcmVzc3dlYjJwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3YwHQYDVR0OBBYEFPEh
  VlRcnExmFRf1Ov3+/p1VmVxxMB8GA1UdIwQYMBaAFElMyfD/ZIWax2Ir/ssotChM
  RSIYMEwGA1UdHwRFMEMwQaA/oD2GO2h0dHA6Ly9nc2Fwa2kuZW50LmRzLmdzYS5n
  b3YvZ3NhY2VydHMvRUNPSDJTLUlTU0NBMDEoMikuY3JsMIGnBggrBgEFBQcBAQSB
  mjCBlzBlBggrBgEFBQcwAoZZaHR0cDovL2dzYXBraS5lbnQuZHMuZ3NhLmdvdi9n
  c2FjZXJ0cy9FQ09IMlMtSVNTQ0EwMS5lbnQuZHMuZ3NhLmdvdl9FQ09IMlMtSVNT
  Q0EwMSgyKS5jcnQwLgYIKwYBBQUHMAGGImh0dHA6Ly9nc2FvY3NwLmVudC5kcy5n
  c2EuZ292L29jc3AwCwYDVR0PBAQDAgWgMDwGCSsGAQQBgjcVBwQvMC0GJSsGAQQB
  gjcVCIOJry+FnqB9gvmDD4awjg2En5cRPoHqnDWE72YCAWQCAREwGwYJKwYBBAGC
  NxUKBA4wDDAKBggrBgEFBQcDATANBgkqhkiG9w0BAQsFAAOCAQEAkpq0AGdRP9xB
  UEvGY7qa6GMYsVJfUxIvD2St8h74lWmEfcow41OtKWKedi1NHAjZ2Cmd8wHTJTTx
  0Oc+aAHB6ExbrjopOFVMK4STNXxyCK9aEcEeBnuU4gnD4GVVza4BYXlKOWcuqT8R
  2lHDxd4+is0OqjTKffofBGRF5aIyvtktP8WDjnxMfGiAcsD+NqHW/GfPyCTz5xMD
  nLnWRL9hpGlUW2F69UveYyRtw0E9qNYZ/r6PTAY2Zz/C19Xr/kzyT/jbTOawqvzz
  1gLs4v0xGDFuDtSeSDCl7LrNaM7rx32w4OI5UF/WSgHUf4L7U6Z3bvkjOB6L/aPN
  jq6TzjDZiw==
  -----END CERTIFICATE-----



jumpbox_operators: "{{ datagov_operators_production }}"


inventory_ckan_service_url: https://inventory.data.gov
inventory_ckan_solr_host: datagov-solrm1p.prod-ocsit.bsp.gsa.gov
inventory_ckan_solr_port: "8983"


# Newrelic
nrinfragent_license_key: "{{ vault_nrinfragent_license_key }}"
newrelic_environment: production


pycsw_app_version: datagov/v2.4.x
pycsw_base_url: https://catalog.data.gov
pycsw_catalog_url: https://catalog.data.gov
pycsw_db_host: "{{ catalog_pycsw_db_host }}"
pycsw_db_name: "{{ catalog_pycsw_db_name }}"
pycsw_db_password: "{{ catalog_pycsw_db_pass }}"
pycsw_db_user: "{{ catalog_pycsw_db_user }}"

# public urls
urls_public:
  catalog: https://catalog.data.gov
urls_private:
  catalog: "{{ vault_urls_private_catalog }}"
ckan_site_domain: "{{ urls_public.catalog }}"

# s3 bucket
catalog_bucket_name: "{{ vault_catalog_bucket_name }}"


# solr
solr_master_server: datagovsolrm1p.prod-ocsit.bsp.gsa.gov
solr_java_packages:
  - openjdk-8-jdk
solr_cores:
  - catalog
  - inventory
solr_xms: 8192m
solr_xmx: 8192m



# SecOps user
secops_user: "{{ vault_secops_user }}"
secops_user_public_key: "{{ vault_secops_user_public_key }}"

# TrendMicro
trendmicro_deb_url: https://dsm.sec.helix.gsa.gov/software/agent/Ubuntu_14.04/x86_64/
trendmicro_policy_id_app: "{{ vault_trendmicro_policy_id_app }}"
trendmicro_policy_id_jumpbox: "{{ vault_trendmicro_policy_id_jumpbox }}"
trendmicro_policy_id_web: "{{ vault_trendmicro_policy_id_web }}"

# List of CodeIgniter pre-approved admin emails
codeigniter_pre_approved_admins: "{{ vault_codeigniter_pre_approved_admins }}"

# App environment
web_app_env: production
real_ansible_env: production

# postfix
default_email_from: "{{ vault_default_email_from }}"
postfix_raw_options:
  - |
    smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
    smtpd_tls_mandatory_ciphers = high
    smtpd_tls_mandatory_exclude_ciphers = aNULL, MD5
postfix_relayhost: smtp.gsa.gov
postfix_relayhost_port: 25
postfix_relaytls: true
postfix_sasl_auth_enable: false
postfix_smtpd_tls_cert_file: /etc/ssl/certs/datagov_host.crt
postfix_smtpd_tls_key_file: /etc/ssl/certs/datagov_host.key
postfix_aliases:
  - user: postmaster
    alias: root
  - user: root
    alias: "{{ datagov_team_email }}"
postfix_sender_canonical_maps:
  - sender: "@{{ ansible_fqdn }}"
    rewrite: no-reply+{{ ansible_fqdn }}@data.gov


# SAML
saml2_idp_entry: login.max.gov
saml2_idp_metadata_url: "https://{{ saml2_idp_entry }}/idp/shibboleth"
saml_idp_cert_fprint: "67:76:BB:87:FE:76:D6:4A:BE:19:3F:E2:B6:1A:49:06:AE:56:06:B8"
saml2_sp_public_certificate: "{{ vault_saml2_sp_public_certificate }}"
saml2_sp_private_key: "{{ vault_saml2_sp_private_key }}"

# td-agent
elasticsearch_endpoint: "{{ vault_elasticsearch_endpoint }}"
bsp_elasticsearch_endpoint: "{{ vault_bsp_elasticsearch_endpoint }}"
bsp_shared_key: "{{ vault_bsp_shared_key }}"
system: "es"

# nessus
nessus_agent_key: "{{ vault_nessus_agent_key }}"
nessus_agent_host: "{{ vault_nessus_agent_host }}"
nessus_agent_port: "{{ vault_nessus_agent_port }}"
nessus_agent_group: "{{ vault_nessus_agent_group }}"

# saxon license
saxon_license: "{{ vault_saxon_license }}"


# ckan
# Auth cookie `auth_tkt` must be HTTPS-only (SECURE) on Production
who_secure: True

# Automated CI tests
ci_inventory: inventories/production
ci_ssh_config_host: '*.prod-ocsit.bsp.gsa.gov'
ci_deploy_version: master


# wordpress
# hostname needed for smoke test, IP address needed for ALB health check
wordpress_nginx_server_name: www.data.gov data.gov wp-bsp.data.gov labs.data.gov $hostname {{ ansible_default_ipv4.address }}
wordpress_service_url: https://www.data.gov
