---
# catalog
catalog_ckan_apache_server_name: "{{ catalog_host_public }}"
catalog_ckan_app_version: master
catalog_ckan_archiver_process_count: 3
catalog_ckan_db_host: "{{ vault_catalog_ckan_db_host }}"
catalog_ckan_db_name: "{{ vault_catalog_ckan_db_name }}"
catalog_ckan_db_pass: "{{ vault_catalog_ckan_db_pass }}"
catalog_ckan_db_user: "{{ vault_catalog_ckan_db_user }}"
catalog_ckan_email_from: "{{ default_email_from }}"
catalog_ckan_harvest_fetch_process_count: 6
catalog_ckan_plugins_additional: [saml2]
catalog_ckan_qa_update_process_count: 5
catalog_ckan_readwrite_configuration: readonly
catalog_ckan_redis_host: catalog-harvester1p.prod-ocsit.bsp.gsa.gov
catalog_ckan_redis_password: "{{ redis_password }}"
catalog_ckan_fgdc2iso_host: catalog-fgdc2iso1p.prod-ocsit.bsp.gsa.gov
catalog_ckan_saml2_enabled: true
catalog_ckan_service_url: https://{{ catalog_host_public }}
catalog_ckan_admin_service_url: https://{{ catalog_host_admin }}
catalog_ckan_who_ini_path: "etc_ckan_who.saml2.ini.j2"
catalog_ckan_solr_port: "8983"
catalog_ckan_solr_host: datagov-solr1p.prod-ocsit.bsp.gsa.gov
catalog_ckan_wsgi_processes: 6
catalog_pycsw_db_host: "{{ vault_catalog_pycsw_db_host }}"
catalog_pycsw_db_name: "{{ vault_catalog_pycsw_db_name }}"
catalog_pycsw_db_pass: "{{ vault_catalog_pycsw_db_pass }}"
catalog_pycsw_db_user: "{{ vault_catalog_pycsw_db_user }}"

# catalog-next
catalog_next_ckan_db_name: "{{ vault_catalog_next_ckan_db_name }}"
catalog_next_ckan_db_pass: "{{ vault_catalog_next_ckan_db_pass }}"
catalog_next_ckan_db_primary_host: "{{ vault_catalog_next_ckan_db_primary_host }}"
catalog_next_ckan_db_replica_a_host: "{{ vault_catalog_next_ckan_db_replica_a_host }}"
catalog_next_ckan_db_replica_b_host: "{{ vault_catalog_next_ckan_db_replica_b_host }}"
catalog_next_ckan_db_user: "{{ vault_catalog_next_ckan_db_user }}"
catalog_next_ckan_instance_secret: "{{ vault_catalog_next_ckan_instance_secret }}"
catalog_next_ckan_instance_uuid: 5ab5625f-4ec5-435b-a725-55eaa36d264b
catalog_next_ckan_postgresql_admin_host: "{{ vault_catalog_next_ckan_postgresql_admin_host }}"
catalog_next_ckan_postgresql_admin_password: "{{ vault_catalog_next_ckan_postgresql_admin_password }}"
catalog_next_ckan_postgresql_admin_user: "{{ vault_catalog_next_ckan_postgresql_admin_user }}"
catalog_next_ckan_production_ini_template: catalog-next/etc_ckan_production.ini.j2
catalog_next_ckan_redis_host: redis1p.prod-ocsit.bsp.gsa.gov
catalog_next_ckan_redis_password: "{{ redis_password }}"
catalog_next_ckan_redis_url: redis://:{{ catalog_next_ckan_redis_password }}@{{ catalog_next_ckan_redis_host }}:6379/0
catalog_next_ckan_solr_a_host: datagov-solr1p-v2.prod-ocsit.bsp.gsa.gov
catalog_next_ckan_solr_b_host: datagov-solr2p-v2.prod-ocsit.bsp.gsa.gov
catalog_next_ckan_solr_primary_host: datagov-solrm1p-v2.prod-ocsit.bsp.gsa.gov
catalog_next_ckan_token_dat: "{{ vault_catalog_next_ckan_token_dat }}"
catalog_next_ckan_who_ini_secret: "{{ vault_catalog_next_ckan_who_ini_secret }}"
catalog_next_ckan_saml2_enabled: true
catalog_next_ckan_who_ini_path: "etc_ckan_who.default.ini.j2"
catalog_next_saml2_sp_public_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIIFgjCCA2oCCQCQl3+XUEkb0DANBgkqhkiG9w0BAQsFADCBgjELMAkGA1UEBhMC
  VVMxCzAJBgNVBAgMAkRDMRMwEQYDVQQHDApXYXNoaW5ndG9uMQwwCgYDVQQKDANH
  U0ExDDAKBgNVBAsMA1RUUzERMA8GA1UEAwwIZGF0YS5nb3YxIjAgBgkqhkiG9w0B
  CQEWE2RhdGFnb3ZoZWxwQGdzYS5nb3YwHhcNMjEwMTEyMjMzMjIwWhcNMjIwMTEy
  MjMzMjIwWjCBgjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkRDMRMwEQYDVQQHDApX
  YXNoaW5ndG9uMQwwCgYDVQQKDANHU0ExDDAKBgNVBAsMA1RUUzERMA8GA1UEAwwI
  ZGF0YS5nb3YxIjAgBgkqhkiG9w0BCQEWE2RhdGFnb3ZoZWxwQGdzYS5nb3YwggIi
  MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQD5fJlW5Q2a4l/EzXfrlCOKwwgd
  3ZykJz4xtR6qPCoI5mubHcLuQ7ADspXhaAYgUIzqPvyX8B8xW1Pi3P+YhHcviFiQ
  FIA76mcaj/PDyVGmVcvllLkqJ5AoKAM9UR8n4hQBaM7dk6E2oV1T219aH13EMdf0
  hhrU58KE3rF02O64x1nZIjGxknIwe7DqX1Wk3Xz01wkfvl1i6Bz+cfOpAe1WmnFJ
  ZSIPcp8gFOPCMUUxy3oTMpO5nSmnH2UMROO9mD/6xXzMuSj7vbVcBkoZ/ckNbXSo
  lwYxb0FK7E79jtpVNv4lFz/edoBXOjOGULO8wBmHpj+XF590eIL9u6+Aa3Fex7Pv
  HrI2ZwFALxrTbNmjkw8NDHG9OzB2cELFPmIv6z4Vbm+St1qL6UvjDv1ODSZZTeca
  u8UzcGKLceF2MKB2EDP44feWPF1P+lX3Mghu4KIxRwSyrwyQQWE/uaF0swCPMX8r
  qR0mTTVWsXqmSTuAB0pNYVbrL0+UTz7UvkWCvLB0cpEO8O/fNkJEq3d/hLKJgR9Q
  7daIHU6r+Mv4/dimXNPX3QwYrSaXbUETUP/9r8UpGIjdZmns7yG0lMdx20HymTc4
  KutnsQgqJAmnsjIY7EPbAVV8sMOuncfu0dJ/FiYvOsj9tkNiQINBPa6tUAksTn5Q
  k5EhToNngsD4d5F//QIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQCJt1nmm7QR5CgW
  VV/wvvdxQDH/96Y0f8kKTFUHC+UgzEpQOvXooO3skhgt3xgIXkXFhyMJ3zPBb41P
  +VUMr9u40k2xjB/f3oY67o/Y6yOCP0+/HSov9XprvP8ga41ZQovTLvQflctEFg5M
  x8MZD3GuCo5vGRf/Iov+PnCi+QF2d9bFfdpseEIJFv4fcOJ9lb6dqnjpgeLE0qtZ
  IY+cXgQUajOwK//yMpvQaYMkiwMgTcuSiMOoEqvfd98dewxESzlf6TtdNxrg8Vpq
  aCfeqfo5QiV0k8P/npFrbdEm8KNvlOIqzh27H7ErH4VSjH7uhc1nIGMYL2F4+yF2
  K6EXyN/q2k9tO3ANxNx/ZsC5JiVOds0qc04cPQRRaCT03dwqgjzGNIdDCcNfM6nq
  QVlHVhvUj+XYerVc5ki4CAJrvLajKhvC0SHJdR1fG+8oxbJgOUiqg3klGGzhQIbk
  T+RCdhBGXYOwjBGnabudWQPBkpjYVYKQyA+GDwcUoZneWlfKbpxcj1xpBJoewIX3
  FVSfmJg9dPxCJm03wWCiKgbb4tOaCsjnhGpTnRF6WkFVPys1qJBaoFbjub/W2p+L
  ZLfnY9zosumtWJVahSNJWrMpG7V9+wTP/pUTDYYsow4JKrH6TE+hRpaQ5gKRRPSG
  BZ3SYIbIuB2mxi5e0toZbpm6+1cumA==
  -----END CERTIFICATE-----

catalog_next_saml2_sp_private_key: "{{ vault_catalog_next_saml2_sp_private_key }}"


# common
common_audit_report_enabled: false
common_filebeat_logstash_output: "{{ vault_common_filebeat_logstash_output }}"
common_filebeat_config:
  filebeat.config.modules:
    enabled: true
    path: ${path.config}/modules.d/*.yml
  filebeat.modules:
    - module: system
      syslog:
        enabled: true
  output.logstash:
    hosts: ["{{ common_filebeat_logstash_output }}"]

common_newrelic_enabled: "{{ datagov_in_service | default(true) }}"
common_python_version_number: 2.7.10
# Trailing space is signficant here.
common_shell_prompt: >-
  ${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\h\[\033[00m\] (production) \[\033[01;34m\]\w\[\033[00m\]\$ 
common_ubuntu_advantage_token: "{{ vault_common_ubuntu_advantage_token }}"
filebeat_enabled: true
nessus_agent_enabled: true
trendmicro_enabled: true
# TODO prefix these with common_
filebeat_config: "{{ common_filebeat_config }}"
products:
  - filebeat


# dashboard
# hostname needed for smoke test, IP address needed for ALB health check
dashboard_nginx_server_name: labs.data.gov $hostname {{ ansible_default_ipv4.address }}
dashboard_service_url: https://labs.data.gov/dashboard
php_cli_memory_limit: 3192M

# data.gov-wide variables
datagov_environment: production


default_tls_host_key: "{{ vault_default_tls_host_key }}"
default_tls_host_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIILWTCCCkGgAwIBAgITHQABNI0lvrQFs7C/uQACAAE0jTANBgkqhkiG9w0BAQsF
  ADBvMRMwEQYKCZImiZPyLGQBGRYDZ292MRMwEQYKCZImiZPyLGQBGRYDZ3NhMRIw
  EAYKCZImiZPyLGQBGRYCZHMxEzARBgoJkiaJk/IsZAEZFgNlbnQxGjAYBgNVBAMT
  EUVDT0gyUy1JU1NDQTAxKDEpMB4XDTIwMDczMTEzMDI1MVoXDTIyMTEwMzEzMDI1
  MVowge8xCzAJBgNVBAYTAlVTMR0wGwYDVQQIExREaXN0cmljdCBvZiBDb2x1bWJp
  YTETMBEGA1UEBxMKV2FzaGluZ3RvbjEoMCYGA1UEChMfR2VuZXJhbCBTZXJ2aWNl
  cyBBZG1pbmlzdHJhdGlvbjEqMCgGA1UECxMhVGVjaG5vbG9neSBUcmFuc2Zvcm1h
  dGlvbiBTZXJ2aWNlMTIwMAYDVQQDEyljYXRhbG9nLWZnZGMyaXNvMXAucHJvZC1v
  Y3NpdC5ic3AuZ3NhLmdvdjEiMCAGCSqGSIb3DQEJARYTZGF0YWdvdmhlbHBAZ3Nh
  LmdvdjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMGIfs+QT4FKY5J5
  F00dsPv21kzS14NBpRQEVl+MgvvyURWdcohss/E9BlKtwYmdaJm0sDMsVaoNcS2x
  KOyTIzlVbw3QJmn33646UH8X5b36upyZh3M2EP5DAocq9A+HAITt9Wppd4qC9oW3
  0IXLM9/m+AMmBVYK+ZLazwLAmC7e+Vu61xMHAYFdiHbmsI4Jp3gO9jNKy09+LuXx
  EYSJOh9pcxxR9d2H5Gjv1OPhklfUUU+mJRJtizwOjnLUVwijMULv58/Nha8MXjFS
  sgKbQuDSj27F+4PaMN65GjaaTw79xvUjHPZDzotPi7xA9w65TGzzTyStk3dr6DpG
  6yuvwX8CAwEAAaOCB2swggdnMBMGA1UdJQQMMAoGCCsGAQUFBwMBMIIFrgYDVR0R
  BIIFpTCCBaGCKWNhdGFsb2ctZmdkYzJpc28xcC5wcm9kLW9jc2l0LmJzcC5nc2Eu
  Z292gipjYXRhbG9nLWhhcnZlc3RlcjFwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aC
  KmNhdGFsb2ctaGFydmVzdGVyMnAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIqY2F0
  YWxvZy1oYXJ2ZXN0ZXIzcC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292gipjYXRhbG9n
  LWhhcnZlc3RlcjRwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCKmNhdGFsb2ctaGFy
  dmVzdGVyNXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIqY2F0YWxvZy1oYXJ2ZXN0
  ZXI2cC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giRjYXRhbG9nLXdlYjFwLnByb2Qt
  b2NzaXQuYnNwLmdzYS5nb3aCJGNhdGFsb2ctd2ViMnAucHJvZC1vY3NpdC5ic3Au
  Z3NhLmdvdoIlY2F0YWxvZ2Itd2ViMXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIl
  Y2F0YWxvZ2Itd2ViMnAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIkY2F0YWxvZ2J3
  ZWIxcC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giRjYXRhbG9nYndlYjJwLnByb2Qt
  b2NzaXQuYnNwLmdzYS5nb3aCKWNhdGFsb2doYXJ2ZXN0ZXIxcC5wcm9kLW9jc2l0
  LmJzcC5nc2EuZ292giljYXRhbG9naGFydmVzdGVyMnAucHJvZC1vY3NpdC5ic3Au
  Z3NhLmdvdoIpY2F0YWxvZ2hhcnZlc3RlcjNwLnByb2Qtb2NzaXQuYnNwLmdzYS5n
  b3aCKWNhdGFsb2doYXJ2ZXN0ZXI0cC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292gilj
  YXRhbG9naGFydmVzdGVyNXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIpY2F0YWxv
  Z2hhcnZlc3RlcjZwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCJ2NhdGFsb2dwdWIt
  d2ViMXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoImY2F0YWxvZ3B1YndlYjFwLnBy
  b2Qtb2NzaXQuYnNwLmdzYS5nb3aCI2NhdGFsb2d3ZWIxcC5wcm9kLW9jc2l0LmJz
  cC5nc2EuZ292giNjYXRhbG9nd2ViMnAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIl
  ZGFzaGJvYXJkd2ViMXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIlZGFzaGJvYXJk
  d2ViMnAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIlZGF0YWdvdi1qdW1wMnAucHJv
  ZC1vY3NpdC5ic3AuZ3NhLmdvdoIlZGF0YWdvdi1zb2xyMXAucHJvZC1vY3NpdC5i
  c3AuZ3NhLmdvdoIlZGF0YWdvdi1zb2xyMnAucHJvZC1vY3NpdC5ic3AuZ3NhLmdv
  doImZGF0YWdvdi1zb2xybTFwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCI2ludmVu
  dG9yeS0xcC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giNpbnZlbnRvcnktMnAucHJv
  ZC1vY3NpdC5ic3AuZ3NhLmdvdoIiaW52ZW50b3J5MXAucHJvZC1vY3NpdC5ic3Au
  Z3NhLmdvdoIiaW52ZW50b3J5MnAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIecmVk
  aXMxcC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giV3b3JkcHJlc3N3ZWIxcC5wcm9k
  LW9jc2l0LmJzcC5nc2EuZ292giV3b3JkcHJlc3N3ZWIycC5wcm9kLW9jc2l0LmJz
  cC5nc2EuZ292MB0GA1UdDgQWBBSWIQCqMSADS9Gl/avaXzPqbMKqbjAfBgNVHSME
  GDAWgBRJTMnw/2SFmsdiK/7LKLQoTEUiGDBMBgNVHR8ERTBDMEGgP6A9hjtodHRw
  Oi8vZ3NhcGtpLmVudC5kcy5nc2EuZ292L2dzYWNlcnRzL0VDT0gyUy1JU1NDQTAx
  KDIpLmNybDCBpwYIKwYBBQUHAQEEgZowgZcwZQYIKwYBBQUHMAKGWWh0dHA6Ly9n
  c2Fwa2kuZW50LmRzLmdzYS5nb3YvZ3NhY2VydHMvRUNPSDJTLUlTU0NBMDEuZW50
  LmRzLmdzYS5nb3ZfRUNPSDJTLUlTU0NBMDEoMikuY3J0MC4GCCsGAQUFBzABhiJo
  dHRwOi8vZ3Nhb2NzcC5lbnQuZHMuZ3NhLmdvdi9vY3NwMAsGA1UdDwQEAwIFoDA8
  BgkrBgEEAYI3FQcELzAtBiUrBgEEAYI3FQiDia8vhZ6gfYL5gw+GsI4NhJ+XET6B
  6pw1hO9mAgFkAgETMBsGCSsGAQQBgjcVCgQOMAwwCgYIKwYBBQUHAwEwDQYJKoZI
  hvcNAQELBQADggEBALgbEK7v9AP4t34bcwJrzhGexqmEP2ptAT3jZSrn3S57X5J5
  t9BSHh9FsvegFSF39Cq7LvmKIP9NhfJBx8KVg+bir0tP2uP56slaCxXMXRVCu37e
  g1fcMEF8rtWUd57E7+HLNxuvXH1/1iIQid0feMvceMOx2drH66D2LaAIezlz4CaX
  gN1A1X5/KueZ887ntc5Ei6fZas2B/Zy/3rLIS3Ce90UrLE5nGKzLflzhExDOU9J5
  5NamNMH2Mkrz9u2C1yDd71Jix05m7ApC+Qb1nNUZhd76QDKIudm3kq89bBM2Se5a
  2pREA8NteodudO5EjMaGchcFV0Hnli4xaVNkp3k=
  -----END CERTIFICATE-----


jumpbox_operators: "{{ datagov_operators_production }}"
jumpbox_shell_prompt: "{{ common_shell_prompt }}"


inventory_ckan_service_url: https://inventory.data.gov
inventory_ckan_solr_host: datagov-solrm1p.prod-ocsit.bsp.gsa.gov
inventory_ckan_solr_port: "8983"
inventory_ckan_who_ini_path: "etc_ckan_who.saml2.ini.j2"

# Inventory Next
inventory_next_ckan_redis_host: "redis1p.prod-ocsit.bsp.gsa.gov"
inventory_next_ckan_redis_password: "{{ redis_password }}"
inventory_next_ckan_s3_bucket_name: "{{ vault_inventory_next_ckan_s3_bucket_name }}"
inventory_next_ckan_s3_bucket_prefix: "{{ vault_inventory_next_ckan_s3_bucket_prefix }}"
inventory_next_ckan_instance_secret: "{{ vault_inventory_next_ckan_instance_secret }}"
inventory_next_ckan_instance_uuid: "{{ vault_inventory_next_ckan_instance_uuid }}"
inventory_next_ckan_service_url: https://inventory-next.data.gov
inventory_next_ckan_solr_host: datagov-solrm1p-v2.prod-ocsit.bsp.gsa.gov
inventory_next_ckan_who_ini_secret: "{{ vault_inventory_next_ckan_who_ini_secret }}"
inventory_next_datastore_login_host: "{{ vault_inventory_next_datastore_login_host }}"
inventory_next_datastore_db_name: "{{ vault_inventory_next_datastore_db_name }}"
inventory_next_datastore_user: "{{ vault_inventory_next_datastore_user }}"
inventory_next_datastore_pass: "{{ vault_inventory_next_datastore_pass }}"
inventory_next_datastore_ro_user: "{{vault_inventory_next_datastore_ro_user }}"
inventory_next_datastore_ro_pass: "{{ vault_inventory_next_datastore_ro_pass }}"
inventory_next_postgresql_login_host: "{{ vault_inventory_next_postgresql_login_host }}"
inventory_next_postgresql_login_user: "{{ vault_inventory_next_postgresql_login_user }}"
inventory_next_postgresql_login_password: "{{ vault_inventory_next_postgresql_login_password }}"
inventory_next_postgresql_db_name: "{{ vault_inventory_next_postgresql_db_name }}"
inventory_next_datapusher_db_name: "{{ vault_inventory_next_datapusher_db_name }}"

# New Relic
newrelic_license_key: "{{ vault_newrelic_license_key }}"


pycsw_app_version: datagov/v2.4.x
pycsw_base_url: https://catalog.data.gov
pycsw_ckan_url: https://catalog.data.gov
pycsw_db_host: "{{ catalog_pycsw_db_host }}"
pycsw_db_name: "{{ catalog_pycsw_db_name }}"
pycsw_db_password: "{{ catalog_pycsw_db_pass }}"
pycsw_db_user: "{{ catalog_pycsw_db_user }}"

# public urls
catalog_host_public: catalog.data.gov
catalog_host_admin: admin-catalog.data.gov

catalog_url_public: https://{{ catalog_host_public }}
catalog_url_admin: https://{{ catalog_host_admin }}

ckan_site_domain: "{{ catalog_host_public }}"

# next public urls
catalog_host_public_next: catalog-next.data.gov
catalog_host_admin_next: admin-catalog-next.data.gov


# s3 bucket
catalog_bucket_name: "{{ vault_catalog_bucket_name }}"


# solr
solr_master_server: datagovsolrm1p.prod-ocsit.bsp.gsa.gov
solr_java_packages:
  - openjdk-8-jdk
solr_cores:
  - catalog
  - inventory
solr_xms: 8192m
solr_xmx: 8192m



# SecOps user
secops_user: "{{ vault_secops_user }}"
secops_user_public_key: "{{ vault_secops_user_public_key }}"

# TrendMicro
trendmicro_deb_url: https://dsm.sec.helix.gsa.gov/software/agent/Ubuntu_14.04/x86_64/
trendmicro_policy_id_app: "{{ vault_trendmicro_policy_id_app }}"
trendmicro_policy_id_jumpbox: "{{ vault_trendmicro_policy_id_jumpbox }}"
trendmicro_policy_id_web: "{{ vault_trendmicro_policy_id_web }}"

# List of CodeIgniter pre-approved admin emails
codeigniter_pre_approved_admins: "{{ vault_codeigniter_pre_approved_admins }}"

# App environment
web_app_env: production
real_ansible_env: production

# postfix
default_email_from: no-reply@data.gsa.gov
postfix_raw_options:
  - |
    smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
    smtpd_tls_mandatory_ciphers = high
    smtpd_tls_mandatory_exclude_ciphers = aNULL, MD5
  - |
    # Postfix needs a value set https://github.com/GSA/datagov-deploy/issues/1795
    smtpd_relay_restrictions = permit_mynetworks, reject_unauth_destination
postfix_relayhost: smtp.gsa.gov
postfix_relayhost_port: 25
postfix_relaytls: true
postfix_sasl_auth_enable: false
postfix_aliases:
  - user: postmaster
    alias: root
  - user: root
    alias: "{{ datagov_team_email }}"
postfix_sender_canonical_maps:
  - sender: "@{{ ansible_fqdn }}"
    rewrite: no-reply+{{ ansible_fqdn }}@data.gsa.gov


# Redis
redis_password: "{{ vault_redis_password }}"


# SAML
saml2_idp_entry: login.max.gov
saml2_idp_metadata_url: "https://{{ saml2_idp_entry }}/idp/shibboleth"
saml_idp_cert_fprint: "67:76:BB:87:FE:76:D6:4A:BE:19:3F:E2:B6:1A:49:06:AE:56:06:B8"
saml2_sp_public_certificate: "{{ vault_saml2_sp_public_certificate }}"
saml2_sp_private_key: "{{ vault_saml2_sp_private_key }}"

# td-agent
elasticsearch_endpoint: "{{ vault_elasticsearch_endpoint }}"
bsp_elasticsearch_endpoint: "{{ vault_bsp_elasticsearch_endpoint }}"
bsp_shared_key: "{{ vault_bsp_shared_key }}"
system: "es"

# nessus
nessus_agent_key: "{{ vault_nessus_agent_key }}"
nessus_agent_host: "{{ vault_nessus_agent_host }}"
nessus_agent_port: "{{ vault_nessus_agent_port }}"
nessus_agent_group: "{{ vault_nessus_agent_group }}"

# saxon license
fgdc2iso_saxon_license: "{{ vault_fgdc2iso_saxon_license }}"


# ckan
# Auth cookie `auth_tkt` must be HTTPS-only (SECURE) on Production
who_secure: True

# Automated CI tests
ci_inventory: inventories/production
ci_ssh_config_host: '*.prod-ocsit.bsp.gsa.gov'
ci_deploy_version: master


# wordpress
# hostname needed for smoke test, IP address needed for ALB health check
wordpress_nginx_server_name: www.data.gov data.gov labs.data.gov $hostname {{ ansible_default_ipv4.address }}
wordpress_service_url: https://www.data.gov
