---
# catalog
catalog_ckan_app_version: master
catalog_ckan_archiver_process_count: 3
catalog_ckan_db_host: "{{ vault_catalog_ckan_db_host }}"
catalog_ckan_db_name: "{{ vault_catalog_ckan_db_name }}"
catalog_ckan_db_pass: "{{ vault_catalog_ckan_db_pass }}"
catalog_ckan_db_user: "{{ vault_catalog_ckan_db_user }}"
catalog_ckan_harvest_fetch_process_count: 6
catalog_ckan_qa_update_process_count: 5
catalog_ckan_service_url: https://catalog.data.gov
catalog_ckan_solr_port: "8983"
catalog_ckan_solr_host: datagov-solr1p.prod-ocsit.bsp.gsa.gov
catalog_pycsw_db_host: "{{ vault_catalog_pycsw_db_host }}"
catalog_pycsw_db_name: "{{ vault_catalog_pycsw_db_name }}"
catalog_pycsw_db_pass: "{{ vault_catalog_pycsw_db_pass }}"
catalog_pycsw_db_user: "{{ vault_catalog_pycsw_db_user }}"


# common
common_filebeat_logstash_output: "{{ vault_common_filebeat_logstash_output }}"
common_filebeat_config:
  filebeat.config.modules:
    enabled: true
    path: ${path.config}/modules.d/*.yml
  filebeat.modules:
    - module: system
      syslog:
        enabled: true
  output.logstash:
    hosts: ["{{ common_filebeat_logstash_output }}"]

common_newrelic_enabled: "{{ datagov_in_service | default(true) }}"
common_python_version_number: 2.7.10
filebeat_enabled: true
nessus_agent_enabled: true
trendmicro_enabled: true
# TODO prefix these with common_
filebeat_config: "{{ common_filebeat_config }}"
products:
  - filebeat


# crm
crm_service_url: https://labs.data.gov/crm


# dashboard
dashboard_service_url: https://labs.data.gov/dashboard


# data.gov-wide variables
datagov_environment: production


default_tls_host_key: "{{ vault_default_tls_host_key }}"
default_tls_host_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIILQTCCCimgAwIBAgIKXV+xEAACAACULzANBgkqhkiG9w0BAQsFADBvMRMwEQYK
  CZImiZPyLGQBGRYDZ292MRMwEQYKCZImiZPyLGQBGRYDZ3NhMRIwEAYKCZImiZPy
  LGQBGRYCZHMxEzARBgoJkiaJk/IsZAEZFgNlbnQxGjAYBgNVBAMTEUVDT0gyUy1J
  U1NDQTAxKDEpMB4XDTE5MDcxNzEzMDk0N1oXDTIyMDcxNjEzMDk0N1owgesxCzAJ
  BgNVBAYTAlVTMR0wGwYDVQQIExREaXN0cmljdCBvZiBDb2x1bWJpYTETMBEGA1UE
  BxMKV2FzaGluZ3RvbjEoMCYGA1UEChMfR2VuZXJhbCBTZXJ2aWNlcyBBZG1pbmlz
  dHJhdGlvbjEqMCgGA1UECxMhVGVjaG5vbG9neSBUcmFuc2Zvcm1hdGlvbiBTZXJ2
  aWNlMS4wLAYDVQQDEyVjYXRhbG9nYi13ZWIxcC5wcm9kLW9jc2l0LmJzcC5nc2Eu
  Z292MSIwIAYJKoZIhvcNAQkBFhNkYXRhZ292aGVscEBnc2EuZ292MIIBIjANBgkq
  hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvEbSDO7q4reL7VUJPMuNmBIK5JsRhl07
  PUU3fdY8SO7qgWgyKzqYrrrfGCIV9Z3KEK0+DlpOpBI1QOFzLWTxO4imwyW4/DDE
  QAK7fris/2e2r/oZp/OuOfJAvvmltrcdvTg5aWGm0Dp2P/WksJZRdINqPTi3PbEQ
  gYXbeKg3YwVIdMjxXSVTijV1grrSS38t4InS+N/05Us+lUIibhC9ZHR38Ilqq6Ut
  I9F/hPLJ95wkLKwyxuCECXzNkFv9mFFjE5mtOmF9McnSfHZFSYMd7gBGToVxgumQ
  bNUDkQXdjyWCG7W+baosV01Mhxms/dDcJY4ed1LXT0Wh5+cGosisRQIDAQABo4IH
  YDCCB1wwEwYDVR0lBAwwCgYIKwYBBQUHAwEwggWjBgNVHREEggWaMIIFloIkY2F0
  YWxvZ2J3ZWIxcC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giVjYXRhbG9nYi13ZWIy
  cC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giRjYXRhbG9nYndlYjJwLnByb2Qtb2Nz
  aXQuYnNwLmdzYS5nb3aCKmNhdGFsb2ctaGFydmVzdGVyMXAucHJvZC1vY3NpdC5i
  c3AuZ3NhLmdvdoIpY2F0YWxvZ2hhcnZlc3RlcjFwLnByb2Qtb2NzaXQuYnNwLmdz
  YS5nb3aCKmNhdGFsb2ctaGFydmVzdGVyMnAucHJvZC1vY3NpdC5ic3AuZ3NhLmdv
  doIpY2F0YWxvZ2hhcnZlc3RlcjJwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCKmNh
  dGFsb2ctaGFydmVzdGVyM3AucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIpY2F0YWxv
  Z2hhcnZlc3RlcjNwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCKmNhdGFsb2ctaGFy
  dmVzdGVyNHAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIpY2F0YWxvZ2hhcnZlc3Rl
  cjRwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCKmNhdGFsb2ctaGFydmVzdGVyNXAu
  cHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIpY2F0YWxvZ2hhcnZlc3RlcjVwLnByb2Qt
  b2NzaXQuYnNwLmdzYS5nb3aCKmNhdGFsb2ctaGFydmVzdGVyNnAucHJvZC1vY3Np
  dC5ic3AuZ3NhLmdvdoIpY2F0YWxvZ2hhcnZlc3RlcjZwLnByb2Qtb2NzaXQuYnNw
  LmdzYS5nb3aCJ2NhdGFsb2dwdWItd2ViMXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdv
  doImY2F0YWxvZ3B1YndlYjFwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCJGNhdGFs
  b2ctd2ViMXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIjY2F0YWxvZ3dlYjFwLnBy
  b2Qtb2NzaXQuYnNwLmdzYS5nb3aCJGNhdGFsb2ctd2ViMnAucHJvZC1vY3NpdC5i
  c3AuZ3NhLmdvdoIjY2F0YWxvZ3dlYjJwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aC
  H2NybXdlYjFwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCH2NybXdlYjJwLnByb2Qt
  b2NzaXQuYnNwLmdzYS5nb3aCJWRhc2hib2FyZHdlYjFwLnByb2Qtb2NzaXQuYnNw
  LmdzYS5nb3aCJWRhc2hib2FyZHdlYjJwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aC
  JWRhdGFnb3YtanVtcDJwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCJWRhdGFnb3Yt
  c29scjFwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCJWRhdGFnb3Ytc29scjJwLnBy
  b2Qtb2NzaXQuYnNwLmdzYS5nb3aCJmRhdGFnb3Ytc29scm0xcC5wcm9kLW9jc2l0
  LmJzcC5nc2EuZ292giNpbnZlbnRvcnktMXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdv
  doIiaW52ZW50b3J5MXAucHJvZC1vY3NpdC5ic3AuZ3NhLmdvdoIjaW52ZW50b3J5
  LTJwLnByb2Qtb2NzaXQuYnNwLmdzYS5nb3aCImludmVudG9yeTJwLnByb2Qtb2Nz
  aXQuYnNwLmdzYS5nb3aCI3N0YXRpYy13ZWIxcC5wcm9kLW9jc2l0LmJzcC5nc2Eu
  Z292giV3b3JkcHJlc3N3ZWIxcC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292giV3b3Jk
  cHJlc3N3ZWIycC5wcm9kLW9jc2l0LmJzcC5nc2EuZ292MB0GA1UdDgQWBBSS912v
  SrrLxTh1Ssp1WUzFjY/EzjAfBgNVHSMEGDAWgBRJTMnw/2SFmsdiK/7LKLQoTEUi
  GDBMBgNVHR8ERTBDMEGgP6A9hjtodHRwOi8vZ3NhcGtpLmVudC5kcy5nc2EuZ292
  L2dzYWNlcnRzL0VDT0gyUy1JU1NDQTAxKDIpLmNybDCBpwYIKwYBBQUHAQEEgZow
  gZcwZQYIKwYBBQUHMAKGWWh0dHA6Ly9nc2Fwa2kuZW50LmRzLmdzYS5nb3YvZ3Nh
  Y2VydHMvRUNPSDJTLUlTU0NBMDEuZW50LmRzLmdzYS5nb3ZfRUNPSDJTLUlTU0NB
  MDEoMikuY3J0MC4GCCsGAQUFBzABhiJodHRwOi8vZ3Nhb2NzcC5lbnQuZHMuZ3Nh
  Lmdvdi9vY3NwMAsGA1UdDwQEAwIFoDA8BgkrBgEEAYI3FQcELzAtBiUrBgEEAYI3
  FQiDia8vhZ6gfYL5gw+GsI4NhJ+XET6B6pw1hO9mAgFkAgERMBsGCSsGAQQBgjcV
  CgQOMAwwCgYIKwYBBQUHAwEwDQYJKoZIhvcNAQELBQADggEBAGDB1fWnKHAIYGZY
  UYr56+YNlZGpW5J4J2u87bz084ODakXDQdNJcrgNS2pLJGVittGdJerIgA7LYR8t
  FB/+DHCjrTTBCE2wgBw5Gtz6wLz1jD8UN7VysHJmNiH9L4vF/4WE9Evla+qk8GHu
  dMhg4YaD+fVhVWfLldfCoGWvbRgseTXKbo2pKKpx5t/6iMZQtAe4kiYT6FrlayVZ
  y2WzcUvci3GctNwAnT7cNdEOFvRlfYOi5GQK6G7o6cDIP4IBDiIQZg1BIqwBexVs
  NGadzlJuAEXovJTGPW5bwTiwzOzXbpiMWFkEo1zG4CY/4fO9lyc/7JUPeMmZi1RI
  pJkIGDI=
  -----END CERTIFICATE-----


jumpbox_operators: "{{ datagov_operators_production }}"


inventory_ckan_service_url: https://inventory.data.gov
inventory_ckan_solr_host: datagov-solrm1p.prod-ocsit.bsp.gsa.gov
inventory_ckan_solr_port: "8983"


# Newrelic
nrinfragent_license_key: "{{ vault_nrinfragent_license_key }}"
newrelic_environment: production


pycsw_app_version: datagov/v2.4.x
pycsw_base_url: https://catalog.data.gov
pycsw_catalog_url: https://catalog.data.gov
pycsw_db_host: "{{ catalog_pycsw_db_host }}"
pycsw_db_name: "{{ catalog_pycsw_db_name }}"
pycsw_db_password: "{{ catalog_pycsw_db_pass }}"
pycsw_db_user: "{{ catalog_pycsw_db_user }}"

# public urls
urls_public:
  catalog: https://catalog.data.gov
urls_private:
  catalog: "{{ vault_urls_private_catalog }}"
ckan_site_domain: "{{ urls_public.catalog }}"

# s3 bucket
catalog_bucket_name: "{{ vault_catalog_bucket_name }}"


# solr
solr_master_server: datagovsolrm1p.prod-ocsit.bsp.gsa.gov
solr_java_packages:
  - openjdk-8-jdk
solr_xms: 8192m
solr_xmx: 8192m



# SecOps user
secops_user: "{{ vault_secops_user }}"
secops_user_public_key: "{{ vault_secops_user_public_key }}"

# TrendMicro
trendmicro_deb_url: https://dsm.sec.helix.gsa.gov/software/agent/Ubuntu_14.04/x86_64/
trendmicro_policy_id_app: "{{ vault_trendmicro_policy_id_app }}"
trendmicro_policy_id_web: "{{ vault_trendmicro_policy_id_web }}"

# List of CodeIgniter pre-approved admin emails
codeigniter_pre_approved_admins: "{{ vault_codeigniter_pre_approved_admins }}"

# App environment
web_app_env: production
real_ansible_env: production

# postfix
default_email_from: "{{ vault_default_email_from }}"
postfix_raw_options:
  - |
    smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
    smtpd_tls_mandatory_ciphers = high
    smtpd_tls_mandatory_exclude_ciphers = aNULL, MD5
postfix_relayhost: smtp.gsa.gov
postfix_relayhost_port: 25
postfix_relaytls: true
postfix_sasl_auth_enable: false
postfix_smtpd_tls_cert_file: /etc/ssl/certs/datagov_host.crt
postfix_smtpd_tls_key_file: /etc/ssl/certs/datagov_host.key
postfix_aliases:
  - user: postmaster
    alias: root
  - user: root
    alias: "{{ datagov_team_email }}"
postfix_sender_canonical_maps:
  - sender: root
    rewrite: no-reply+{{ ansible_fqdn }}@data.gov


# SAML
saml2_idp_entry: login.max.gov
saml2_idp_metadata_url: "https://{{ saml2_idp_entry }}/idp/shibboleth"
saml_idp_cert_fprint: "67:76:BB:87:FE:76:D6:4A:BE:19:3F:E2:B6:1A:49:06:AE:56:06:B8"
saml2_sp_public_certificate: "{{ vault_saml2_sp_public_certificate }}"
saml2_sp_private_key: "{{ vault_saml2_sp_private_key }}"

# td-agent
elasticsearch_endpoint: "{{ vault_elasticsearch_endpoint }}"
bsp_elasticsearch_endpoint: "{{ vault_bsp_elasticsearch_endpoint }}"
bsp_shared_key: "{{ vault_bsp_shared_key }}"
system: "es"

# nessus
nessus_agent_key: "{{ vault_nessus_agent_key }}"
nessus_agent_host: "{{ vault_nessus_agent_host }}"
nessus_agent_port: "{{ vault_nessus_agent_port }}"
nessus_agent_group: "{{ vault_nessus_agent_group }}"

# saxon license
saxon_license: "{{ vault_saxon_license }}"


# ckan
# Auth cookie `auth_tkt` must be HTTPS-only (SECURE) on Production
who_secure: True

# Automated CI tests
ci_inventory: inventories/production
ci_ssh_config_host: '*.prod-ocsit.bsp.gsa.gov'
ci_deploy_version: master


wordpress_service_url: https://www.data.gov
