# Cleanup after deployment

- name: Reverting /var/www/ permissions
  file:
    path: "/var/www"
    state: directory
    mode: 0755
    recurse: yes
  register: chmod_www

- name: Ensuring required directories exist and have write permissions
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
    recurse: yes
  with_items:
    - "{{ project_source_new_code_path }}/web/app/uploads/saml-20-single-sign-on/etc"
    - "{{ project_source_new_code_path }}/web/app/w3tc-config"
    - "{{ project_source_new_code_path }}/web/app/cache"
    - "{{ project_source_new_code_path }}/web/app/uploads"

- name: Check if cron log file is accessible
  file:
    path: "{{ item }}"
    state: touch
    mode: 0666
  with_items:
    - "/var/log/wp-cron.log"

# SERVICE MODULE WILL NOT WORK (checked Ansible versions till 2.3.1)
# `service php7.0-fpm restart` itself will not start `php7.0-fpm` if it's not running
#- name: php7.0-fpm status
#  command: /etc/init.d/php7.0-fpm status
#  register: php_fpm_status
#  tags: skip_ansible_lint

- name: Start php7.0-fpm
  command: /etc/init.d/php7.0-fpm start
#  when: '"is not running" in php_fpm_status.stdout'
  tags: skip_ansible_lint
  notify: restart nginx

#- name: ReStart php7.0-fpm
#  command: /etc/init.d/php7.0-fpm restart
#  when: '"is running" in php_fpm_status.stdout'
#  tags: skip_ansible_lint
#  notify: restart nginx
