---
datagov_team_email: team@example.com

catalog_app_type: web  # either web or worker
catalog_ckan_access_log: "{{ catalog_log_dir }}/ckan.access.log"
catalog_ckan_allow_login_routes: false
catalog_ckan_app_version: master
catalog_ckan_error_log: "{{ catalog_log_dir }}/ckan.error.log"
catalog_ckan_harvest_fetch_process_count: 2
catalog_ckan_wsgi_processes: 2
catalog_ckan_worker_type: main_worker  # Choices: main_worker misc_worker qa_worker
catalog_ckan_plugins_additional: []
catalog_ckan_plugins_default:
  - stats
  - geodatagov
  - datagov_harvest
  - ckan_harvester
  - geodatagov_geoportal_harvester
  - z3950_harvester
  - arcgis_harvester
  - waf_harvester_collection
  - geodatagov_csw_harvester
  - geodatagov_doc_harvester
  - geodatagov_waf_harvester
  - geodatagov_miscs
  - spatial_metadata
  - spatial_query
  - resource_proxy
  - spatial_harvest_metadata_api
  - datagovtheme
  - datajson_harvest
  - datajson
  - archiver
  - qa
  - googleanalyticsbasic
  - ga-report
  - extlink
  - report
  - broken_link_report

catalog_ckan_python_home: /usr
catalog_ckan_saml2_enabled: false
catalog_harvest_enable_harvest_report: false
catalog_log_dir: /var/log/ckan
app_source_path: /tmp/catalog-app
app_repo: https://github.com/GSA/catalog-app.git
app_repo_branch: master

# used in  production.ini/ckan_site_url and hosts
ckan_site_domain: "http://127.0.0.1"

# provide some default values to be overwritten later by group vars and host vars...
project_source_rollback_path: /usr/lib/ckan-rollback
project_source_new_code_path: /usr/lib/ckan-new
current_source_symlink: /usr/lib/ckan
url_readonly: http://127.0.0.1
url_writable: http://127.0.0.1
saml2_idp_entry: login.test.max.gov
ckan_instance_secret: some-secret
ckan_instance_uuid: a9778c33-ef82-4642-9099-d9d448635570
catalog_db_user: ckan
catalog_db_pass: ckan
catalog_db_name: ckan
catalog_ckan_db_host: localhost
saml2_idp_metadata_url: https://login.test.max.gov/idp/shibboleth
saml2_site_url: https://admin-catalog.data.gov/
catalog_bucket_name: somebucketname
env: local
catalog_ckan_solr_host: localhost
catalog_ckan_solr_port: 8983
app_type: catalog
# Auth cookie `auth_tkt` must be HTTPS-only (SECURE) on Production
who_secure: "False"
token_dat: placeholder-token
catalog_ckan_redis_host: localhost
redis_password: redis
