# This role is only for temporary testing purposes because https://github.com/gsa/datagov-deploy-common is too large to run as a pre-task
---
- name: assert common_tls_host_certificate role variables are set
  debug:
    msg: "common_tls_host_certificate must be defined."
  when: common_tls_host_certificate is undefined

- name: assert common_tls_host_key role variables are set
  debug:
    msg: "common_tls_host_key must be defined."
  when: common_tls_host_key is undefined

- name: ensure ssl-cert group and files exists
  apt:
    name: ssl-cert
    state: present

- name: copy host certificate
  copy:
    dest: /etc/ssl/certs/datagov_host.crt
    content: "{{ common_tls_host_certificate }}"
    mode: 0644
    owner: root
    group: root

- name: copy host key
  copy:
    dest: /etc/ssl/private/datagov_host.key
    content: "{{ common_tls_host_key }}"
    mode: 0640
    owner: root
    group: ssl-cert