---

# Enable crons only on specific hosts
crons_enabled: false

# Project path
project_source_rollback_path: /var/www/datagov/rollback
project_source_new_code_path: /var/www/datagov/new
current_source_symlink: /var/www/datagov/current
project_index_path: /var/www/datagov/current/web

# Nginx
letsencrypt: false