---
# In sandbox, we use python3 on bionic web hosts
# https://github.com/GSA/datagov-infrastructure-modules/issues/32
ansible_python_interpreter: /usr/bin/python3

datagov_service: wordpress-web1tf.internal.sandbox.datagov.us

# WordPress env
env_content_protocol: https

# MySQL credentials
env_db_host: "{{ vault_env_db_host }}"
env_db_user: "{{ vault_env_db_user }}"
env_db_pass: "{{ vault_env_db_pass }}"
env_db_name: "{{ vault_env_db_name }}"

# s3
# s3_bucket: bsp-ocsit-prod-east-appdata
# s3_prefix: datagov/wordpress/

# SAML
saml_idp_id: "https://{{ saml2_idp_entry }}/idp/shibboleth"
saml_idp_sso: "https://{{ saml2_idp_entry }}/idp/profile/SAML2/POST/SSO"
saml_idp_slo: "https://{{ saml2_idp_entry }}/idp/profile/SAML2/POST/SLO"
# saml_auth_adminpassword: "{{ vault_saml_auth_adminpassword }}"
# saml_secretsalt: "{{ vault_saml_secretsalt }}"

# Generate your keys here: https://roots.io/salts.html
auth_key: "{{ vault_auth_key }}"
secure_auth_key: "{{ vault_secure_auth_key }}"
logged_in_key: "{{ vault_logged_in_key }}"
nonce_key: "{{ vault_nonce_key }}"
auth_salt: "{{ vault_auth_salt }}"
secure_auth_salt: "{{ vault_secure_auth_salt }}"
logged_in_salt: "{{ vault_logged_in_salt }}"
nonce_salt: "{{ vault_nonce_salt }}"

