version: '2'
services:
  wpdb:
    container_name: datagov_wp_db
    image: mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: insecure
      MYSQL_DATABASE: datagov
      MYSQL_USER: datagov
      MYSQL_PASSWORD: superpassword

  wordpress:
    container_name: datagov_wp_web
    image: datagov/wp
    volumes:
          - "./.data/web:/var/www/datagov"
    depends_on:
      - wpdb
    links:
      - wpdb
    ports:
      - "8000:80"
      - "2022:22"
    restart: always
