--- # fix "Unable to resolve host IP" issue

- name: check whether hostname has been added already
  shell: cat /etc/hosts | grep $(hostname)
  register: hostname_grep
  ignore_errors: true

- name: add hostname to /etc/hosts
  shell: echo 127.0.0.1 $(hostname) >> /etc/hosts
  when: hostname_grep.stdout == ""

# temporary fix for ntpd issues
- name: fix ntpd issues
  shell: apt-get remove ntp -y && apt-get purge ntp -y && apt-get autoclean -y && apt-get autoremove -y && apt-get install ntp -y
