---
# catalog
catalog_ckan_allow_login_routes: true
catalog_ckan_app_version: master
catalog_ckan_db_host: "{{ catalog_postgresql_login_host }}"
catalog_ckan_db_name: catalog_db
catalog_ckan_db_pass: "{{ catalog_postgresql_login_password }}"
catalog_ckan_db_user: "{{ catalog_postgresql_login_user }}"
catalog_ckan_redis_host: catalog-harvester1tf.internal.sandbox.datagov.us
catalog_ckan_redis_pass: "{{ vault_catalog_ckan_redis_pass }}"
catalog_ckan_service_url: https://catalog.sandbox.datagov.us
catalog_ckan_solr_host: datagov-solr1tf.internal.sandbox.datagov.us
catalog_ckan_solr_port: "{{ solr_port }}"
catalog_ckan_who_ini_secret: "{{ vault_catalog_ckan_who_ini_secret }}"
catalog_postgresql_login_host: "{{ vault_catalog_postgresql_login_host }}"
catalog_postgresql_login_password: "{{ vault_catalog_postgresql_login_password }}"
catalog_postgresql_login_user: "{{ vault_catalog_postgresql_login_user }}"
catalog_pycsw_db_host: "{{ catalog_postgresql_login_host }}"
catalog_pycsw_db_name: pycsw
catalog_pycsw_db_pass: "{{ vault_catalog_pycsw_db_pass }}"
catalog_pycsw_db_user: pycsw
catalog_db_pass: "{{ catalog_ckan_db_pass }}"
catalog_db_name: "{{ catalog_ckan_db_name }}"
catalog_db_user: "{{ catalog_ckan_db_user }}"

# catalog-next
catalog_next_postgresql_login_host: "{{ vault_catalog_next_postgresql_login_host }}"
catalog_next_postgresql_login_password: "{{ vault_catalog_next_postgresql_login_password }}"
catalog_next_postgresql_login_user: "{{ vault_catalog_next_postgresql_login_user }}"

# common
common_newrelic_enabled: false
common_python_version_number: 2.7.10
filebeat_enabled: false
nessus_agent_enabled: false
trendmicro_enabled: false
project_git_version: master

# dashboard
# hostname needed for smoke test, IP address needed for ALB health check
dashboard_nginx_server_name: dashboard.sandbox.datagov.us $hostname {{ ansible_default_ipv4.address }}
dashboard_service_url: https://dashboard.sandbox.datagov.us


# data.gov-wide variables
datagov_enable_postgresql_role: true
datagov_environment: sandbox
datagov_sandbox_env: sandbox

default_tls_host_key: "{{ vault_default_tls_host_key }}"
default_tls_host_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIIEVTCCAz2gAwIBAgIJALhe8ZrGe78rMA0GCSqGSIb3DQEBCwUAMIHAMQswCQYD
  VQQGEwJVUzELMAkGA1UECAwCREMxEzARBgNVBAcMCldhc2hpbmd0b24xKDAmBgNV
  BAoMH0dlbmVyYWwgU2VydmljZXMgQWRtaW5pc3RyYXRpb24xKjAoBgNVBAsMIVRl
  Y2hub2xvZ3kgVHJhbnNmb3JtYXRpb24gU2VydmljZTEVMBMGA1UEAwwMKi5kYXRh
  Z292LnVzMSIwIAYJKoZIhvcNAQkBFhNkYXRhZ292aGVscEBnc2EuZ292MB4XDTE5
  MDIwOTAwMjMzNloXDTIxMDIwODAwMjMzNlowgcAxCzAJBgNVBAYTAlVTMQswCQYD
  VQQIDAJEQzETMBEGA1UEBwwKV2FzaGluZ3RvbjEoMCYGA1UECgwfR2VuZXJhbCBT
  ZXJ2aWNlcyBBZG1pbmlzdHJhdGlvbjEqMCgGA1UECwwhVGVjaG5vbG9neSBUcmFu
  c2Zvcm1hdGlvbiBTZXJ2aWNlMRUwEwYDVQQDDAwqLmRhdGFnb3YudXMxIjAgBgkq
  hkiG9w0BCQEWE2RhdGFnb3ZoZWxwQGdzYS5nb3YwggEiMA0GCSqGSIb3DQEBAQUA
  A4IBDwAwggEKAoIBAQCrvX1zkUtZyxjkniG8x8EXoFHmtm2PiavFhcs6d0W2IHPe
  jXXLUEXJb7ldwdKwi5yCTuW8J0CGoIl8EkkTy3+rQWjjS74iTvewxkcYVdHB/oXf
  wpPuL9azvX1WEekfdKCYf98D+RWnr+5XWMbXyRafI2a9yeE3et6mkeqeu4iP/8iA
  G7o/BEcLhrDFQFuzA0WQxGhajqQvSTTfjhEp2Dqq4u/Ek7DqVuf7IJ/KYt3PeGeX
  bV19LAzKt2HE5uqXSRZn0vnMRyCT9kz+yNZqUVHCzk7GE01Jl7wxTDU1cGraqrMK
  9Cg4zBNX1g3B8xucGOichpawOBiW+a5A2yhCNPzjAgMBAAGjUDBOMB0GA1UdDgQW
  BBRe5bzhJ9N8pjtAXKbwzLu6c2F4hDAfBgNVHSMEGDAWgBRe5bzhJ9N8pjtAXKbw
  zLu6c2F4hDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCdv74tZfxn
  NsfDG4SwnPvusMorYWM719wDdfXO0VIQMGcP/aRitgw6aMlHXpWltqMXOO0NyOv3
  zMbYIvTNJWRCFiOMSUSTc3UEs/Hd5/O8d31Ncqg7MJRfISlIRvjQ6FntOZ3WDmrG
  ZwnqGkfGYpj92Q2xuXDd7FjGTKXVJiwaVMkDifUe/ez74R3ltSNeohaLOkZf5Zcw
  68XH2jjigSenaTkHd8QND1yde5/ekyX7s594M5tz16Tr05Wmnf+3OSNFssooFlXY
  a6iApABZqU0Aac0KNKxx7F8BvcTfems78jd0RhKrGKD77l4VTtFb+gU2C02Abbm+
  lo4YdL0A8Y/f
  -----END CERTIFICATE-----


jenkins_admin_password: "{{ vault_jenkins_admin_password }}"
jenkins_job_authentication_token: "{{ vault_jenkins_job_authentication_token }}"
jenkins_jobs:
  - name: deploy-ci-platform
    git_url: https://github.com/gsa/datagov-deploy.git
    git_ref: refs/heads/develop
  - name: deploy-ci-catalog-app
    git_url: https://github.com/gsa/catalog.data.gov.git

jenkins_config: "{{ lookup('template', 'jenkins_config_sandbox.yml.j2') }}"

jenkins_home: /data/jenkins
jenkins_hostname: jenkins1tf.internal.sandbox.datagov.us
jenkins_tls_key: "{{ vault_jenkins_tls_key }}"
jenkins_tls_cert: |-
  -----BEGIN CERTIFICATE-----
  MIIGPTCCBCWgAwIBAgIUMAK4Lb3eFwwu9Lp5/zO7+PMBCMgwDQYJKoZIhvcNAQEL
  BQAwga0xCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJEQzETMBEGA1UEBwwKV2FzaGlu
  Z3RvbjERMA8GA1UECgwIRGF0YS5nb3YxKjAoBgNVBAsMIVRlY2hub2xvZ3kgVHJh
  bnNmb3JtYXRpb24gU2VydmljZTEZMBcGA1UEAwwQY2kuY2kuZGF0YWdvdi51czEi
  MCAGCSqGSIb3DQEJARYTZGF0YWdvdmhlbHBAZ3NhLmdvdjAeFw0xOTEyMjcwMTE3
  NTBaFw0yMDEyMjYwMTE3NTBaMIGtMQswCQYDVQQGEwJVUzELMAkGA1UECAwCREMx
  EzARBgNVBAcMCldhc2hpbmd0b24xETAPBgNVBAoMCERhdGEuZ292MSowKAYDVQQL
  DCFUZWNobm9sb2d5IFRyYW5zZm9ybWF0aW9uIFNlcnZpY2UxGTAXBgNVBAMMEGNp
  LmNpLmRhdGFnb3YudXMxIjAgBgkqhkiG9w0BCQEWE2RhdGFnb3ZoZWxwQGdzYS5n
  b3YwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC7z+cbvDyScuGkF5pu
  F5SWR7A9QCU6cBb1MZsNmkMbOvakO+Z4oWZVdwLcKiWzC0pv5JKM5ekno4Zl/OP+
  CKVu4larCoxHTtpbSE2XH5TVOQwrn4yeqtuEH4RQVgt8ZbgPLlzBtw84vGT9p9u2
  r/Dn7FaQzdGNLzEpT+nynz59nvhcWrghI54UxOJLjeMzJaz5xzC0TpsxEnEs+luo
  H5KrWX0b+zyvHjy9X8BgtGYp4g2tzVJ5N/PjZmhO4aWdnPx9blft8XpRe4KpFfue
  rD4roIJQG6Auus5ZAcjDVDF3xZaEB6pxD2OmxbFPrkVdJGHVGYsst9tdc6HQ9T6M
  Zd9yR/LDgIY9HHGBlW2NxafrsTnZiYdNDNRqfHJ1SiYhudCQ6EfQNhnPQ6Gl5rmg
  zxQgp9EAicWLu7Or4Q3KHeJ49MiZB1S7/ogfEjlBE3fx0RgB18f+LG8BtHz0ixpL
  lcc+1kKZaLA1g4Zsl/Wx/GgtI2cvrlJ00NwV+CdsCQgVt1NGXbjTDJiyZr3y3WaD
  +S94hppPlqiuARjtwkb2bj1ZFtaKOsvP4TiVH0k4plG9eIQcGB8/Z+KCiKE5XrnJ
  9RmnCLWKtWL+lXsSxVaykpYtDrZItLOlp3XGvRtHWItfrPa/05UFzFRIMrskIH5U
  9HyhxSbWQp8YSiFPvmZrI5lR9wIDAQABo1MwUTAdBgNVHQ4EFgQUR5W2BCJd592A
  /mMiMPoDontGFOgwHwYDVR0jBBgwFoAUR5W2BCJd592A/mMiMPoDontGFOgwDwYD
  VR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAI3phfgZuTLSgRJRWI/a2
  4efNzcgM78shulLwoQ0d0GNBRrDmB1zK8Q9a/YWQmZO1j8vqUe2912sSCvxsNt/t
  Skh5Q4inokJVil99mLwoQXxo7zEaCAD1tVI0DFczWr6W9fznxbKXx8Aps7oJ30zJ
  Wu94esj41lBigYCde4znae4UGucvwg6I7TSoR+ezbBxltcCuif4xzpmIiX5x14Ra
  zeG8vUHDN34L3VU4+qudohpyhpt+dVaOUyoeKjWT5pOMO5gaU7RFsEG2CZtd76rH
  7BeGjPDtiyTGIo/VyPdtcqUfEr8zIepCSyPdPtlU5bQOFtCEW0m77zX946yGLJk9
  kh/4oSphmXUDqEUGqno6yfgfAmuAmr/iRAny59J92Y3hgGHwEtJiFVYdX8k2S+So
  +XeUcbZCF7KMiByy56JxwMxNXL37WtSuRAys686Xve9D/AIARx+A5b0CH8quNTPX
  B3M2e62DBk7V+vuuGj0vMPUJPbttQBO7oBEiXl79YI7lUyC8HvZ3JACNvTDVoBsC
  tk1qBk5lXvRzl51ZMlxBTSa/nUbzUlnlpvuqYV7IjGeC+XFyndtzc2yN7ayiDN6b
  iqmUG4lFFNeBYMYt5wPR3I+e6Bn2tk/a5McVhCQt6uVBWfgiPnxrU+pef2EgQ7J9
  VzQrATk1ZB3jBepMlhLBl7I=
  -----END CERTIFICATE-----
jenkins_host: ci.sandbox.datagov.us


jumpbox_operators: "{{ datagov_operators_test }}"


inventory_ckan_service_url: https://inventory.sandbox.datagov.us
inventory_ckan_solr_port: "{{ solr_port }}"


pycsw_app_version: datagov/v2.4.x
pycsw_base_url: https://catalog.sandbox.datagov.us
pycsw_catalog_url: https://catalog.sandbox.datagov.us
pycsw_db_host: "{{ catalog_pycsw_db_host }}"
pycsw_db_name: "{{ catalog_pycsw_db_name }}"
pycsw_db_password: "{{ catalog_pycsw_db_pass }}"
pycsw_db_user: "{{ catalog_pycsw_db_user }}"


# public urls
urls_public:
  catalog: https://catalog.{{ datagov_sandbox_env }}.datagov.us
urls_private:
  catalog: https://catalog.{{ datagov_sandbox_env }}.datagov.us

ckan_site_domain: "{{ urls_public.catalog }}"

# s3 bucket
catalog_bucket_name: "{{ vault_catalog_bucket_name }}"

# List of CodeIgniter pre-approved admin emails
codeigniter_pre_approved_admins: "{{ vault_codeigniter_pre_approved_admins }}"


# App environment
web_app_env: production
real_ansible_env: production


# newrelic
nrinfragent_license_key: "{{ vault_nrinfragent_license_key }}"


# postfix
postfix_relayhost: smtp.gsa.gov
postfix_relayhost_port: 25
postfix_sasl_auth_enable: false
postfix_relaytls: true
default_email_from: no-reply@data.gov
postfix_key: "{{ vault_postfix_key }}"
postfix_pem: "{{ vault_postfix_pem }}"


# SAML
saml2_idp_entry: login.test.max.gov
saml2_idp_metadata_url: "https://{{ saml2_idp_entry }}/idp/shibboleth"
saml_idp_cert_fprint: "67:76:BB:87:FE:76:D6:4A:BE:19:3F:E2:B6:1A:49:06:AE:56:06:B8"
saml2_sp_public_certificate: "{{ vault_saml2_sp_public_certificate }}"
saml2_sp_private_key: "{{ vault_saml2_sp_private_key }}"


# fgdc2iso service on catalog-harvester
# saxon license
saxon_license: "{{ vault_saxon_license }}"


# SecOps user
secops_user: "{{ vault_secops_user }}"
secops_user_public_key: "{{ vault_secops_user_public_key }}"


# solr
solr_master_server: datagov-solr1tf.internal.{{ datagov_sandbox_env }}.datagov.us
solr_java_packages:
  - openjdk-8-jdk


# wordpress
# hostname needed for smoke test, IP address needed for ALB health check
wordpress_nginx_server_name: wordpress.sandbox.datagov.us $hostname {{ ansible_default_ipv4.address }}
wordpress_service_url: https://wordpress.sandbox.datagov.us
