---
catalog_ckan_service_url: https://{{ catalog_host_public_next }}
ckan_site_domain: https://{{ catalog_host_public_next }}

catalog_ckan_apache_server_name: "{{ catalog_host_public_next }}"
catalog_ckan_apache_server_alias:
  - d1xr5ix4dos50f.cloudfront.net
catalog_ckan_app_version: enable-saml2
catalog_ckan_db_host: "{{ catalog_next_postgresql_login_host }}"
catalog_ckan_db_name: "{{ catalog_next_ckan_db_name }}"
catalog_ckan_db_pass: "{{ catalog_next_postgresql_login_password }}"
catalog_ckan_db_user: "{{ catalog_next_postgresql_login_user }}"
catalog_ckan_fgdc2iso_host: "{{ catalog_next_ckan_fgdc2iso_host }}"

catalog_ckan_redis_url: "{{ catalog_next_ckan_redis_url }}"
catalog_ckan_redis_host: "{{ catalog_next_ckan_redis_host }}"
catalog_ckan_redis_password: "{{ catalog_next_ckan_redis_password }}"

catalog_ckan_plugins_default: "{{ catalog_next_ckan_plugins_default }}"

catalog_ckan_saml2_enabled: true

# login.gov identity sandbox
saml2_idp_metadata_url: "https://idp.int.identitysandbox.gov/api/saml/metadata2020"
saml2_site_url: "https://catalog-next.sandbox.datagov.us/"
