---
catalog_ckan_service_url: https://catalog-next.sandbox.datagov.us
ckan_site_domain: https://catalog-next.sandbox.datagov.us

catalog_ckan_db_host: "{{ catalog_next_postgresql_login_host }}"
catalog_ckan_db_name: "{{ catalog_next_ckan_db_name }}"
catalog_ckan_db_pass: "{{ catalog_next_postgresql_login_password }}"
catalog_ckan_db_user: "{{ catalog_next_postgresql_login_user }}"

catalog_ckan_redis_url: "{{ catalog_next_ckan_redis_url }}"
catalog_ckan_redis_host: "{{ catalog_next_ckan_redis_host }}"
catalog_ckan_redis_password: "{{ catalog_next_ckan_redis_password }}"

catalog_ckan_plugins_default: "{{ catalog_next_ckan_plugins_default }}"
