---

# AWS S3
aws_s3_archive_key: "{{ vault_aws_s3_archive_key }}"
aws_s3_archive_secret: "{{ vault_aws_s3_archive_secret }}"

# MySQL credentials
env_db_host: "{{ vault_env_db_host }}"
env_db_user: "{{ vault_env_db_user }}"
env_db_pass: "{{ vault_env_db_pass }}"
env_db_name: "{{ vault_env_db_name }}"