---
datagov_app_process: worker

catalog_app_type: worker

datagov_in_service: false

# catalog-workers write to database
catalog_ckan_db_host: "{{ catalog_next_ckan_db_primary_host }}"

# catalog-workers write to solr
catalog_ckan_solr_host: "{{ catalog_next_ckan_solr_primary_host }}"

# workers are in the application tier
trendmicro_policy_id: "{{ trendmicro_policy_id_app }}"
