---
- name: install apache site config
  copy:
    src: etc/apache2/sites-enabled/ckan.conf
    dest: /etc/apache2/sites-enabled/ckan.conf
    mode: 0644
  notify: reload apache

- name: install ckan config
  template:
    src: /etc/ckan/production.ini.j2
    dest: /etc/ckan/production.ini
    mode: 0640
    group: www-data
  notify: reload apache

- name: install ckan who.ini config
  template:
    src: etc/ckan/who.ini.j2
    dest: /etc/ckan/who.ini
    mode: 0640
    group: www-data
  notify: reload apache

- name: copy requirements.txt with special dependencies
  copy:
    src: requirements.native-login.txt
    dest: /tmp/requirements.native-login.txt
    mode: 0644

- name: install compatible version of repoze.who
  pip:
    requirements: /tmp/requirements.native-login.txt
    virtualenv: /usr/lib/ckan
    umask: '0022'
  notify: reload apache
