---

- name: Install Ansible via APT/PPA
  command: "{{ item }}"
  with_items:
    - apt-get install software-properties-common
    - apt-add-repository ppa:ansible/ansible
    - apt-get update
    - apt-get install ansible -y
  
