---
# role url
url_readonly: "{{ urls_public.catalog }}"
url_writable: "{{ urls_private.catalog }}"

# project path
project_source_rollback_path: /usr/lib/ckan-rollback
project_source_new_code_path: /usr/lib/ckan-new
current_source_symlink: /usr/lib/ckan
project_index_path: /usr/lib/ckan

# other
env: local
who_secure: "{{ catalog_ckan_who_secure }}"

# secrets
ckan_instance_secret: "{{ catalog_ckan_instance_secret }}"
ckan_instance_uuid: "{{ catalog_ckan_instance_uuid }}"

# token_dat for Google Analytics
token_dat: "{{ catalog_ckan_token_dat }}"

catalog_ckan_instance_secret: "{{ vault_catalog_ckan_instance_secret }}"
catalog_ckan_instance_uuid: "{{ vault_catalog_ckan_instance_uuid }}"
catalog_ckan_token_dat: "{{ vault_catalog_ckan_token_dat }}"
catalog_ckan_who_secure: "true"
# uncomment to enable saml2 authentication
#catalog_ckan_saml2_enabled: true
#catalog_ckan_plugins_additional: [saml2]
saml2_site_url: https://catalog.sandbox.datagov.us/

postgresql_login_host: "{{ catalog_postgresql_login_host }}"
postgresql_login_password: "{{ catalog_postgresql_login_password }}"
postgresql_login_user: "{{ catalog_postgresql_login_user }}"
postgresql_enable_extensions:
  - postgis
