# meta file for postfix
---
galaxy_info:
  author: Mischa ter Smitten
  company: Oefenweb.nl B.V.
  description: Set up a postfix server in Debian-like systems
  license: MIT
  min_ansible_version: 1.6
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - system
    - web
dependencies: []
