---
# catalog
catalog_ckan_app_version: master
catalog_ckan_archiver_process_count: 3
# read-only database variables
catalog_ckan_db_host: "{{ vault_catalog_ckan_db_host }}"
catalog_ckan_db_name: "{{ vault_catalog_ckan_db_name }}"
catalog_ckan_db_pass: "{{ vault_catalog_ckan_db_pass }}"
catalog_ckan_db_user: "{{ vault_catalog_ckan_db_user }}"
catalog_ckan_email_from: "{{ default_email_from }}"
catalog_ckan_harvest_fetch_process_count: 6
catalog_ckan_plugins_additional: [saml2]
catalog_ckan_qa_update_process_count: 5
catalog_ckan_readwrite_configuration: readonly
catalog_ckan_redis_host: catalog-harvester1d.dev-ocsit.bsp.gsa.gov
catalog_ckan_redis_password: "{{ redis_password }}"
catalog_ckan_fgdc2iso_host: catalog-fgdc2iso1d.dev-ocsit.bsp.gsa.gov
catalog_ckan_saml2_enabled: true
catalog_ckan_service_url: https://catalog-datagov.dev-ocsit.bsp.gsa.gov
catalog_ckan_solr_host: datagov-solr1d.dev-ocsit.bsp.gsa.gov
catalog_ckan_solr_port: "8983"
# read-only database variables
catalog_pycsw_db_host: "{{ vault_catalog_pycsw_db_host }}"
catalog_pycsw_db_name: "{{ vault_catalog_pycsw_db_name }}"
catalog_pycsw_db_pass: "{{ vault_catalog_pycsw_db_pass }}"
catalog_pycsw_db_user: "{{ vault_catalog_pycsw_db_user }}"


# common
common_audit_report_enabled: false
common_filebeat_logstash_output: "{{ vault_common_filebeat_logstash_output }}"
common_filebeat_config:
  filebeat.config.modules:
    enabled: true
    path: ${path.config}/modules.d/*.yml
  filebeat.modules:
    - module: system
      syslog:
        enabled: true
  output.logstash:
    hosts: ["{{ common_filebeat_logstash_output }}"]

common_newrelic_enabled: "{{ datagov_in_service | default(true) }}"
common_python_version_number: 2.7.10
filebeat_enabled: true
nessus_agent_enabled: true
trendmicro_enabled: true
# TODO prefix with common_
filebeat_config: "{{ common_filebeat_config }}"
products:
  - filebeat


# dashboard
# hostname needed for smoke test, IP address needed for ALB health check
dashboard_nginx_server_name: dashboard-datagov.dev-ocsit.bsp.gsa.gov $hostname {{ ansible_default_ipv4.address }}
dashboard_service_url: https://dashboard-datagov.dev-ocsit.bsp.gsa.gov

# data.gov-wide variables
datagov_environment: staging
datagov_serial: "100%"


default_tls_host_key: "{{ vault_default_tls_host_key }}"
default_tls_host_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIIJnDCCCISgAwIBAgITHQABMTy5ab3TDNl/OwACAAExPDANBgkqhkiG9w0BAQsF
  ADBvMRMwEQYKCZImiZPyLGQBGRYDZ292MRMwEQYKCZImiZPyLGQBGRYDZ3NhMRIw
  EAYKCZImiZPyLGQBGRYCZHMxEzARBgoJkiaJk/IsZAEZFgNlbnQxGjAYBgNVBAMT
  EUVDT0gyUy1JU1NDQTAxKDEpMB4XDTIwMDcyMjE2NTg1MloXDTIyMTAyNTE2NTg1
  Mlowge4xCzAJBgNVBAYTAlVTMR0wGwYDVQQIExREaXN0cmljdCBvZiBDb2x1bWJp
  YTETMBEGA1UEBxMKV2FzaGluZ3RvbjEoMCYGA1UEChMfR2VuZXJhbCBTZXJ2aWNl
  cyBBZG1pbmlzdHJhdGlvbjEqMCgGA1UECxMhVGVjaG5vbG9neSBUcmFuc2Zvcm1h
  dGlvbiBTZXJ2aWNlMTEwLwYDVQQDEyhjYXRhbG9nLWZnZGMyaXNvMWQuZGV2LW9j
  c2l0LmJzcC5nc2EuZ292MSIwIAYJKoZIhvcNAQkBFhNkYXRhZ292aGVscEBnc2Eu
  Z292MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuGwmNIXchVAFX46n
  TdDJTMJvBd76omR6kxl1b5PzUHBIDBqbYaa2a8dufWFMm+tWGpLZk1MSBVjOao/O
  Fu+buKBArHoFRvLOnDkD3QdrOd7umwLT55CEylALB3faMYtqbVIJ/KAjH787Ev5Q
  /GOYg7s/fV16/ebGyrm4kGhLQNALgyHHjcf3DLES8MuQpNuFbkf1Fiqz/b+Rml0A
  HT6YP1iPLf+ZuqjTieifZ8rVMFZCUv+wxtCa/NSmj/M/l565id/pgyGAvpqDyL4n
  9SyHcMzlmGRT544FTTy2z+mb48BMCbtpa/fDQiCpoMVX0xvrGNulfWEIiFRCqVWX
  ckyPKwIDAQABo4IFrzCCBaswEwYDVR0lBAwwCgYIKwYBBQUHAwEwggPyBgNVHREE
  ggPpMIID5YIpY2F0YWxvZy1oYXJ2ZXN0ZXIxZC5kZXYtb2NzaXQuYnNwLmdzYS5n
  b3aCKWNhdGFsb2ctaGFydmVzdGVyMmQuZGV2LW9jc2l0LmJzcC5nc2EuZ292giNj
  YXRhbG9nLXdlYjFkLmRldi1vY3NpdC5ic3AuZ3NhLmdvdoIjY2F0YWxvZy13ZWIy
  ZC5kZXYtb2NzaXQuYnNwLmdzYS5nb3aCKGNhdGFsb2doYXJ2ZXN0ZXIxZC5kZXYt
  b2NzaXQuYnNwLmdzYS5nb3aCKGNhdGFsb2doYXJ2ZXN0ZXIyZC5kZXYtb2NzaXQu
  YnNwLmdzYS5nb3aCJmNhdGFsb2dwdWItd2ViMWQuZGV2LW9jc2l0LmJzcC5nc2Eu
  Z292giVjYXRhbG9ncHVid2ViMWQuZGV2LW9jc2l0LmJzcC5nc2EuZ292giJjYXRh
  bG9nd2ViMWQuZGV2LW9jc2l0LmJzcC5nc2EuZ292giJjYXRhbG9nd2ViMmQuZGV2
  LW9jc2l0LmJzcC5nc2EuZ292giRkYXNoYm9hcmR3ZWIxZC5kZXYtb2NzaXQuYnNw
  LmdzYS5nb3aCJGRhc2hib2FyZHdlYjJkLmRldi1vY3NpdC5ic3AuZ3NhLmdvdoIk
  ZGF0YWdvdi1qdW1wMmQuZGV2LW9jc2l0LmJzcC5nc2EuZ292gidkYXRhZ292LXNv
  bHIxZC12Mi5kZXYtb2NzaXQuYnNwLmdzYS5nb3aCJGRhdGFnb3Ytc29scjFkLmRl
  di1vY3NpdC5ic3AuZ3NhLmdvdoInZGF0YWdvdi1zb2xyMmQtdjIuZGV2LW9jc2l0
  LmJzcC5nc2EuZ292giRkYXRhZ292LXNvbHIyZC5kZXYtb2NzaXQuYnNwLmdzYS5n
  b3aCKGRhdGFnb3Ytc29scm0xZC12Mi5kZXYtb2NzaXQuYnNwLmdzYS5nb3aCJWRh
  dGFnb3Ytc29scm0xZC5kZXYtb2NzaXQuYnNwLmdzYS5nb3aCImludmVudG9yeS0x
  ZC5kZXYtb2NzaXQuYnNwLmdzYS5nb3aCImludmVudG9yeS0yZC5kZXYtb2NzaXQu
  YnNwLmdzYS5nb3aCIWludmVudG9yeTFkLmRldi1vY3NpdC5ic3AuZ3NhLmdvdoIh
  aW52ZW50b3J5MmQuZGV2LW9jc2l0LmJzcC5nc2EuZ292gh1yZWRpczFkLmRldi1v
  Y3NpdC5ic3AuZ3NhLmdvdoIkd29yZHByZXNzd2ViMWQuZGV2LW9jc2l0LmJzcC5n
  c2EuZ292giR3b3JkcHJlc3N3ZWIyZC5kZXYtb2NzaXQuYnNwLmdzYS5nb3YwHQYD
  VR0OBBYEFAx9zVbnCeOTKNVK3Hr3yqg3vsuxMB8GA1UdIwQYMBaAFElMyfD/ZIWa
  x2Ir/ssotChMRSIYMEwGA1UdHwRFMEMwQaA/oD2GO2h0dHA6Ly9nc2Fwa2kuZW50
  LmRzLmdzYS5nb3YvZ3NhY2VydHMvRUNPSDJTLUlTU0NBMDEoMikuY3JsMIGnBggr
  BgEFBQcBAQSBmjCBlzBlBggrBgEFBQcwAoZZaHR0cDovL2dzYXBraS5lbnQuZHMu
  Z3NhLmdvdi9nc2FjZXJ0cy9FQ09IMlMtSVNTQ0EwMS5lbnQuZHMuZ3NhLmdvdl9F
  Q09IMlMtSVNTQ0EwMSgyKS5jcnQwLgYIKwYBBQUHMAGGImh0dHA6Ly9nc2FvY3Nw
  LmVudC5kcy5nc2EuZ292L29jc3AwCwYDVR0PBAQDAgWgMDwGCSsGAQQBgjcVBwQv
  MC0GJSsGAQQBgjcVCIOJry+FnqB9gvmDD4awjg2En5cRPoHqnDWE72YCAWQCARMw
  GwYJKwYBBAGCNxUKBA4wDDAKBggrBgEFBQcDATANBgkqhkiG9w0BAQsFAAOCAQEA
  a4MJYVWrfRMD5rnKwFu2/cIr5yd5rGmUAFHIYoe5fwofQXCKIJFAamb44Z7j7uhk
  c8Ra9O1yVIBK92a7bt9GZCj0vXuTMqePpzeek31kPWs+8+YsWuksMbKGJ2mWoGUg
  8hLfkYv49j8jlYE6++7h8qHmuci0Es9+HaNep/w3/Dn/Nc2Cqg+yRJ4kdbPSU3Qo
  hY/x1x6NveVjUxSitc1YG1PGC5Q/AJ0j7aCrH4QWDO8lJJlp1XeOnuZ9ybfcHQo8
  gmlMAXfrJmng5Ohws2m8yaKffAkJTs1oBpZEitFCo0/7ug6QeD0/mLALpPs1CgHh
  HJbScy5l4lTIoLlT+Qy/gw==
  -----END CERTIFICATE-----


jumpbox_operators: "{{ datagov_operators_production }}"


inventory_app_environment: staging
inventory_ckan_service_url: https://inventory-datagov.dev-ocsit.bsp.gsa.gov
inventory_ckan_solr_host: datagov-solrm1d.dev-ocsit.bsp.gsa.gov
inventory_ckan_solr_port: "8983"


# Newrelic
nrinfragent_license_key: "{{ vault_nrinfragent_license_key }}"
newrelic_environment: staging


pycsw_app_environment: staging
pycsw_app_version: datagov/v2.4.x
pycsw_base_url: https://catalog-datagov.dev-ocsit.bsp.gsa.gov
pycsw_ckan_url: https://catalog-datagov.dev-ocsit.bsp.gsa.gov
pycsw_db_host: "{{ catalog_pycsw_db_host }}"
pycsw_db_name: "{{ catalog_pycsw_db_name }}"
pycsw_db_password: "{{ catalog_pycsw_db_pass }}"
pycsw_db_user: "{{ catalog_pycsw_db_user }}"


# public urls
urls_public:
  catalog: https://catalog-datagov.dev-ocsit.bsp.gsa.gov
urls_private:
  catalog: https://catalog-datagov.dev-ocsit.bsp.gsa.gov
ckan_site_domain: "{{ urls_public.catalog }}"


# Redis
redis_password: "{{ vault_redis_password }}"


# solr
solr_master_server: tempdatagovsolrm1d.dev-ocsit.bsp.gsa.gov
solr_java_packages:
  - openjdk-8-jdk
solr_cores:
  - catalog
  - inventory
solr_xms: 8192m
solr_xmx: 8192m

# SecOps user
secops_user: "{{ vault_secops_user }}"
secops_user_public_key: "{{ vault_secops_user_public_key }}"

# TrendMicro
trendmicro_deb_url: https://dsm.sec.helix.gsa.gov/software/agent/Ubuntu_14.04/x86_64/
trendmicro_policy_id_app: "{{ vault_trendmicro_policy_id_app }}"
trendmicro_policy_id_jumpbox: "{{ vault_trendmicro_policy_id_jumpbox }}"
trendmicro_policy_id_web: "{{ vault_trendmicro_policy_id_web }}"

# List of CodeIgniter pre-approved admin emails
codeigniter_pre_approved_admins: "{{ vault_codeigniter_pre_approved_admins }}"

# App environment
web_app_env: production
real_ansible_env: staging

# postfix
default_email_from: "{{ vault_default_email_from }}"
postfix_raw_options:
  - |
    smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
    smtpd_tls_mandatory_ciphers = high
    smtpd_tls_mandatory_exclude_ciphers = aNULL, MD5
postfix_relayhost: smtp.gsa.gov
postfix_relayhost_port: 25
postfix_relaytls: true
postfix_sasl_auth_enable: false
postfix_smtpd_tls_cert_file: /etc/ssl/certs/datagov_host.crt
postfix_smtpd_tls_key_file: /etc/ssl/certs/datagov_host.key
postfix_aliases:
  - user: postmaster
    alias: root
  - user: root
    alias: "{{ datagov_team_email }}"
postfix_sender_canonical_maps:
  - sender: "@{{ ansible_fqdn }}"
    rewrite: no-reply+{{ ansible_fqdn }}@data.gov


# SAML
saml2_idp_entry: login.test.max.gov
saml2_idp_metadata_url: "https://{{ saml2_idp_entry }}/idp/shibboleth"
saml_idp_cert_fprint: "7A43DACB95D67FB6A804FD37C8A7DCA5B0384939"
saml2_sp_public_certificate: "{{ vault_saml2_sp_public_certificate }}"
saml2_sp_private_key: "{{ vault_saml2_sp_private_key }}"

# td-agent
elasticsearch_endpoint: "{{ vault_elasticsearch_endpoint }}"
bsp_elasticsearch_endpoint: "{{ vault_bsp_elasticsearch_endpoint }}"
bsp_shared_key: "{{ vault_bsp_shared_key }}"
system: "es"

# nessus
nessus_agent_key: "{{ vault_nessus_agent_key }}"
nessus_agent_host: "{{ vault_nessus_agent_host }}"
nessus_agent_port: "{{ vault_nessus_agent_port }}"
nessus_agent_group: "{{ vault_nessus_agent_group }}"

# saxon license
fgdc2iso_saxon_license: "{{ vault_fgdc2iso_saxon_license }}"


# ckan
# Auth cookie `auth_tkt` must be HTTPS-only (SECURE) on Production
who_secure: True

# jumpbox users
users: "{{ vault_users }}"

# Automated CI tests
ci_inventory: inventories/staging
ci_ssh_config_host: '*.dev-ocsit.bsp.gsa.gov'
ci_deploy_version: develop

# hostname needed for smoke test, IP address needed for ALB health check
wordpress_nginx_server_name: wordpress-datagov.dev-ocsit.bsp.gsa.gov $hostname {{ ansible_default_ipv4.address }}
wordpress_service_url: https://wordpress-datagov.dev-ocsit.bsp.gsa.gov
