---
# catalog
catalog_ckan_apache_server_name: "{{ catalog_host_public }}"
catalog_ckan_app_version: fcs
catalog_ckan_archiver_process_count: 3
# read-only database variables
catalog_ckan_db_host: "{{ vault_catalog_ckan_db_host }}"
catalog_ckan_db_name: "{{ vault_catalog_ckan_db_name }}"
catalog_ckan_db_pass: "{{ vault_catalog_ckan_db_pass }}"
catalog_ckan_db_user: "{{ vault_catalog_ckan_db_user }}"
catalog_ckan_email_from: "{{ default_email_from }}"
catalog_ckan_harvest_fetch_process_count: 4
catalog_ckan_plugins_additional: [saml2]
catalog_ckan_qa_update_process_count: 5
catalog_ckan_readwrite_configuration: readonly
catalog_ckan_redis_host: catalog-harvester1d.dev-ocsit.bsp.gsa.gov
catalog_ckan_redis_password: "{{ redis_password }}"
catalog_ckan_fgdc2iso_host: catalog-fgdc2iso1d.dev-ocsit.bsp.gsa.gov
catalog_ckan_saml2_enabled: true
catalog_ckan_service_url: https://{{ catalog_host_public }}
catalog_ckan_admin_service_url: https://{{ catalog_host_admin }}
catalog_ckan_who_ini_path: "etc_ckan_who.saml2.ini.j2"
catalog_ckan_solr_host: datagov-solr1d.dev-ocsit.bsp.gsa.gov
catalog_ckan_solr_port: "8983"

catalog_ckan_wsgi_processes: 4

# catalog-next
catalog_next_ckan_db_name: "{{ vault_catalog_next_ckan_db_name }}"
catalog_next_ckan_db_pass: "{{ vault_catalog_next_ckan_db_pass }}"
catalog_next_ckan_db_primary_host: "{{ vault_catalog_next_ckan_db_primary_host }}"
catalog_next_ckan_db_replica_host: "{{ vault_catalog_next_ckan_db_replica_host }}"
catalog_next_ckan_db_user: "{{ vault_catalog_next_ckan_db_user }}"
catalog_next_ckan_envs: |
  {{ newrelic_app_envs }}
catalog_next_ckan_instance_secret: "{{ vault_catalog_next_ckan_instance_secret }}"
catalog_next_ckan_instance_uuid: 1d6ce0c2-1e55-48c5-8d2a-37452ff57989
catalog_next_ckan_postgresql_admin_host: "{{ vault_catalog_next_ckan_postgresql_admin_host }}"
catalog_next_ckan_postgresql_admin_password: "{{ vault_catalog_next_ckan_postgresql_admin_password }}"
catalog_next_ckan_postgresql_admin_user: "{{ vault_catalog_next_ckan_postgresql_admin_user }}"
catalog_next_ckan_production_ini_template: catalog-next/etc_ckan_production.ini.j2
catalog_next_ckan_redis_host: redis1d.dev-ocsit.bsp.gsa.gov
catalog_next_ckan_redis_password: "{{ redis_password }}"
catalog_next_ckan_redis_url: redis://:{{ catalog_next_ckan_redis_password }}@{{ catalog_next_ckan_redis_host }}:6379/0
catalog_next_ckan_solr_a_host: datagov-solr1d-v2.dev-ocsit.bsp.gsa.gov
catalog_next_ckan_solr_b_host: datagov-solr2d-v2.dev-ocsit.bsp.gsa.gov
catalog_next_ckan_solr_primary_host: datagov-solrm1d-v2.dev-ocsit.bsp.gsa.gov
catalog_next_ckan_token_dat: "{{ vault_catalog_next_ckan_token_dat }}"
catalog_next_ckan_who_ini_secret: "{{ vault_catalog_next_ckan_who_ini_secret }}"
catalog_next_ckan_saml2_enabled: true
catalog_next_ckan_who_ini_path: "etc_ckan_who.default.ini.j2"
catalog_next_saml2_sp_public_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIIGajCCBFICCQCGVoZYp6VwmTANBgkqhkiG9w0BAQsFADCB9jELMAkGA1UEBhMC
  VVMxHTAbBgNVBAgMFERpc3RyaWN0IG9mIENvbHVtYmlhMRMwEQYDVQQHDApXYXNo
  aW5ndG9uMSgwJgYDVQQKDB9HZW5lcmFsIFNlcnZpY2VzIEFkbWluaXN0cmF0aW9u
  MSowKAYDVQQLDCFUZWNobm9sb2d5IFRyYW5zZm9ybWF0aW9uIFNlcnZpY2UxIjAg
  BgkqhkiG9w0BCQEWE2RhdGFnb3ZoZWxwQGdzYS5nb3YxOTA3BgNVBAMMMGFkbWlu
  LWNhdGFsb2ctbmV4dC1kYXRhZ292LmRldi1vY3NpdC5ic3AuZ3NhLmdvdjAeFw0y
  MTAzMjIxNDE1MzNaFw0yMzAzMjIxNDE1MzNaMIH2MQswCQYDVQQGEwJVUzEdMBsG
  A1UECAwURGlzdHJpY3Qgb2YgQ29sdW1iaWExEzARBgNVBAcMCldhc2hpbmd0b24x
  KDAmBgNVBAoMH0dlbmVyYWwgU2VydmljZXMgQWRtaW5pc3RyYXRpb24xKjAoBgNV
  BAsMIVRlY2hub2xvZ3kgVHJhbnNmb3JtYXRpb24gU2VydmljZTEiMCAGCSqGSIb3
  DQEJARYTZGF0YWdvdmhlbHBAZ3NhLmdvdjE5MDcGA1UEAwwwYWRtaW4tY2F0YWxv
  Zy1uZXh0LWRhdGFnb3YuZGV2LW9jc2l0LmJzcC5nc2EuZ292MIICIjANBgkqhkiG
  9w0BAQEFAAOCAg8AMIICCgKCAgEA18GNFPEw7sWPw1CjtqjWVt5h7Xf59uNXEZOg
  W4xUK6bcBB/MrfEvCnxWGtEEnu06iXfzUoHfZ0wIGqwvDsLdK93XRJ4og3NEGVo8
  fsLN/drvOqryqFKsCQiJQRFoNiIS8OHeZwqAYno2Esxl4UKsc1m7GKNprWQyAxmy
  PZW/cdxkiHXuRjYE2dYLtGmgH1F5Q8oZAF8gBnQPf+wq9U/KI7pePmmhABus/ukl
  oxMktC0VhwtQhhz7KXyhrefjb4U1Go2DkximibNcTXCSuqGkejBRPIs17gZgH/fE
  1YPoXHBIdxYyEKQrj/M1s+AHBr6dN0PF7D6JUJvfRmw6GeoxekNgiBFC1vvoytPB
  vKZ1JnpXHt411YQOcuVPjQd9TvF5wh0wOc5/B/NQfG/MU16yPao/yu+rjDCQlmnW
  cfRyrQV3wjWlqxne/5mAM4c+eKf9pL8M0oGGVx3Z8/5oHAYQ+QtP/us4zyz1ewy6
  zH/36xMrhm+kc6TtcL+GlvMwpQbdJz/DtizHECbJEdNCb8Axver6iTJ+fpIuaUl5
  t1+Wj7l07Cptb1QMWjgRUQEB697uEvt31WZab4syBjbOLopfLTgTxMSs3URNC14G
  axYbtXWjij/dqslqLTWwvVaZHuCTNznteeXMV11VefLAkvPqfugwxModO65ZEJT0
  mpQZOc0CAwEAATANBgkqhkiG9w0BAQsFAAOCAgEAbA7+29PLqY6hREAiMYPct0LR
  i+1TvRVXTVrVkO8GHc8EQUlbDEje2bH4lsXGkSD7sTdDgSfPTV00MTMZLp34L9EE
  dSTCJ8WthmlWxXyIuba7LvUN3ijENhknDyADDKEbkUm3OjvaXhdlZyNmro3/0A4h
  kqGTKnn7F476WP+HDQJQbs5GkoZ1NCSkRPdkVe/2HAkNieOUshzwM8viWZjqtaMD
  CPGLPdislD4UtlB6+dxnBohT/GRVKnYS9ur3I5dzK1CJQTa9EiRKwykZGdkeMmfM
  //5XGhzewz9aLzmwnwQvt6LrlBmqf5If8/+ePyqRWp6SA0UjvyTH638moeglYoPL
  hrRTMXmF3WWGpcPK82HiwKuLYdWECe+SZDWwjO7qpcCbKjnnbOkTqgYSbS6JRG8x
  XaNaFPA3aDzDLRCQfD664HWhwkHIhoOdVMz77yhUPJwUSliiRe+noNfJfOTsg1zN
  C3wpG/PVkZMLfNzGPmIGeGvNLVokGZqnpYtrn0LNGbsqU8/++rJZ0QOO6nsIXnMu
  Z26psl3X8PjotVW64pr4fGXADs0eY8xuuSS2W0LFJyEziQJpi148hbm8JNrb7EAn
  VhkAWtYJd5ypOYV3hYpaCRnBoLXMOX8An5nOsaM0xN59/cj0eM+glKRXw2Zstp88
  rKbKeAkw4MwOH11HiIk=
  -----END CERTIFICATE-----

catalog_next_saml2_sp_private_key: "{{ vault_catalog_next_saml2_sp_private_key }}"

# common
common_audit_report_enabled: false
common_filebeat_logstash_output: "{{ vault_common_filebeat_logstash_output }}"
common_filebeat_config:
  filebeat.config.modules:
    enabled: true
    path: ${path.config}/modules.d/*.yml
  filebeat.modules:
    - module: system
      syslog:
        enabled: true
  output.logstash:
    hosts: ["{{ common_filebeat_logstash_output }}"]

common_newrelic_enabled: "{{ datagov_in_service | default(true) }}"
common_python_version_number: 2.7.10
common_ubuntu_advantage_token: "{{ vault_common_ubuntu_advantage_token }}"
filebeat_enabled: true
nessus_agent_enabled: true
trendmicro_enabled: true
# TODO prefix with common_
filebeat_config: "{{ common_filebeat_config }}"
products:
  - filebeat


# dashboard
# hostname needed for smoke test, IP address needed for ALB health check
dashboard_nginx_server_name: dashboard-datagov.dev-ocsit.bsp.gsa.gov $hostname {{ ansible_default_ipv4.address }}
dashboard_service_url: https://dashboard-datagov.dev-ocsit.bsp.gsa.gov

# data.gov-wide variables
datagov_environment: staging
datagov_serial: "100%"


default_tls_host_key: "{{ vault_default_tls_host_key }}"
default_tls_host_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIIJxjCCCK6gAwIBAgITHQABNI40g2MEaD9RBAACAAE0jjANBgkqhkiG9w0BAQsF
  ADBvMRMwEQYKCZImiZPyLGQBGRYDZ292MRMwEQYKCZImiZPyLGQBGRYDZ3NhMRIw
  EAYKCZImiZPyLGQBGRYCZHMxEzARBgoJkiaJk/IsZAEZFgNlbnQxGjAYBgNVBAMT
  EUVDT0gyUy1JU1NDQTAxKDEpMB4XDTIwMDczMTEzMDI1MVoXDTIyMTEwMzEzMDI1
  MVowge4xCzAJBgNVBAYTAlVTMR0wGwYDVQQIExREaXN0cmljdCBvZiBDb2x1bWJp
  YTETMBEGA1UEBxMKV2FzaGluZ3RvbjEoMCYGA1UEChMfR2VuZXJhbCBTZXJ2aWNl
  cyBBZG1pbmlzdHJhdGlvbjEqMCgGA1UECxMhVGVjaG5vbG9neSBUcmFuc2Zvcm1h
  dGlvbiBTZXJ2aWNlMTEwLwYDVQQDEyhjYXRhbG9nLWZnZGMyaXNvMWQuZGV2LW9j
  c2l0LmJzcC5nc2EuZ292MSIwIAYJKoZIhvcNAQkBFhNkYXRhZ292aGVscEBnc2Eu
  Z292MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxGnxSAfZtvu2IBYa
  6hJPGvD18OoN/j/97eMlyzYnLqLkpGCEZjpGNR2Pc2g576ABD1HPt6knApYweCFV
  zrdit8C/uJTccsFk5TfzzTPiakLjOQLtLNhm6NtEPDx8n2dpEnAH1yyQoYAYzba8
  rcmLOgXm+SJHpsUXJLAJ5RUkzdkOOXRyiwCa8jw7u83D36/gSO93BkAsQCBZ9EPx
  NjejvZ9/hLff4d7OpKq6Z3Srkrlwvd9XX2/PrasOwplq7JhpR8ZnewCdB1UFo+H+
  HkACaQhMTLB5HR/X8JnHgECfyGtRHphMlmK043tWEzpOLXd1ceUxCPjT1RW6K7pY
  yJjd/wIDAQABo4IF2TCCBdUwEwYDVR0lBAwwCgYIKwYBBQUHAwEwggQcBgNVHREE
  ggQTMIIED4IoY2F0YWxvZy1mZ2RjMmlzbzFkLmRldi1vY3NpdC5ic3AuZ3NhLmdv
  doIpY2F0YWxvZy1oYXJ2ZXN0ZXIxZC5kZXYtb2NzaXQuYnNwLmdzYS5nb3aCKWNh
  dGFsb2ctaGFydmVzdGVyMmQuZGV2LW9jc2l0LmJzcC5nc2EuZ292giNjYXRhbG9n
  LXdlYjFkLmRldi1vY3NpdC5ic3AuZ3NhLmdvdoIjY2F0YWxvZy13ZWIyZC5kZXYt
  b2NzaXQuYnNwLmdzYS5nb3aCKGNhdGFsb2doYXJ2ZXN0ZXIxZC5kZXYtb2NzaXQu
  YnNwLmdzYS5nb3aCKGNhdGFsb2doYXJ2ZXN0ZXIyZC5kZXYtb2NzaXQuYnNwLmdz
  YS5nb3aCJmNhdGFsb2dwdWItd2ViMWQuZGV2LW9jc2l0LmJzcC5nc2EuZ292giVj
  YXRhbG9ncHVid2ViMWQuZGV2LW9jc2l0LmJzcC5nc2EuZ292giJjYXRhbG9nd2Vi
  MWQuZGV2LW9jc2l0LmJzcC5nc2EuZ292giJjYXRhbG9nd2ViMmQuZGV2LW9jc2l0
  LmJzcC5nc2EuZ292giRkYXNoYm9hcmR3ZWIxZC5kZXYtb2NzaXQuYnNwLmdzYS5n
  b3aCJGRhc2hib2FyZHdlYjJkLmRldi1vY3NpdC5ic3AuZ3NhLmdvdoIkZGF0YWdv
  di1qdW1wMmQuZGV2LW9jc2l0LmJzcC5nc2EuZ292gidkYXRhZ292LXNvbHIxZC12
  Mi5kZXYtb2NzaXQuYnNwLmdzYS5nb3aCJGRhdGFnb3Ytc29scjFkLmRldi1vY3Np
  dC5ic3AuZ3NhLmdvdoInZGF0YWdvdi1zb2xyMmQtdjIuZGV2LW9jc2l0LmJzcC5n
  c2EuZ292giRkYXRhZ292LXNvbHIyZC5kZXYtb2NzaXQuYnNwLmdzYS5nb3aCKGRh
  dGFnb3Ytc29scm0xZC12Mi5kZXYtb2NzaXQuYnNwLmdzYS5nb3aCJWRhdGFnb3Yt
  c29scm0xZC5kZXYtb2NzaXQuYnNwLmdzYS5nb3aCImludmVudG9yeS0xZC5kZXYt
  b2NzaXQuYnNwLmdzYS5nb3aCImludmVudG9yeS0yZC5kZXYtb2NzaXQuYnNwLmdz
  YS5nb3aCIWludmVudG9yeTFkLmRldi1vY3NpdC5ic3AuZ3NhLmdvdoIhaW52ZW50
  b3J5MmQuZGV2LW9jc2l0LmJzcC5nc2EuZ292gh1yZWRpczFkLmRldi1vY3NpdC5i
  c3AuZ3NhLmdvdoIkd29yZHByZXNzd2ViMWQuZGV2LW9jc2l0LmJzcC5nc2EuZ292
  giR3b3JkcHJlc3N3ZWIyZC5kZXYtb2NzaXQuYnNwLmdzYS5nb3YwHQYDVR0OBBYE
  FG3Bo3iaWHcGzzZHSVqzce7lSNxzMB8GA1UdIwQYMBaAFElMyfD/ZIWax2Ir/sso
  tChMRSIYMEwGA1UdHwRFMEMwQaA/oD2GO2h0dHA6Ly9nc2Fwa2kuZW50LmRzLmdz
  YS5nb3YvZ3NhY2VydHMvRUNPSDJTLUlTU0NBMDEoMikuY3JsMIGnBggrBgEFBQcB
  AQSBmjCBlzBlBggrBgEFBQcwAoZZaHR0cDovL2dzYXBraS5lbnQuZHMuZ3NhLmdv
  di9nc2FjZXJ0cy9FQ09IMlMtSVNTQ0EwMS5lbnQuZHMuZ3NhLmdvdl9FQ09IMlMt
  SVNTQ0EwMSgyKS5jcnQwLgYIKwYBBQUHMAGGImh0dHA6Ly9nc2FvY3NwLmVudC5k
  cy5nc2EuZ292L29jc3AwCwYDVR0PBAQDAgWgMDwGCSsGAQQBgjcVBwQvMC0GJSsG
  AQQBgjcVCIOJry+FnqB9gvmDD4awjg2En5cRPoHqnDWE72YCAWQCARMwGwYJKwYB
  BAGCNxUKBA4wDDAKBggrBgEFBQcDATANBgkqhkiG9w0BAQsFAAOCAQEAEtmAuOHZ
  /GxPJzbRl8QZHqKh1vDgZaXHrRy4TXSKvGtjClW+S+UZ92p41cUUg/o4ytShf6D1
  zA2yadttrUkGgSChKl/USyQnOd+m7DaIm9FNm2qXIiuem7GTt+ZRKhbM/HotU1Zq
  McgmN7KK2qRNdWWq7ANf5Y2ywrZE9J91RNyPn+g0MOPcEcgqkK2Vnld/jwg/YbnI
  wAqvmlGosd0gyaaWjv7n9H7S6Vx2obc+NLSI5hEoQRHSvy8lNKxElZS8bhG+FRMq
  1k0XgGCOrKUzvWDDg+A6Bs7mvlnftW4kMi8vyrAaCqm/t8hpsEwJP/f4XZfhkS7W
  UbNhQisQRXNheg==
  -----END CERTIFICATE-----


jumpbox_operators: "{{ datagov_operators_production }}"


inventory_app_environment: staging
inventory_ckan_service_url: https://inventory-next-datagov.dev-ocsit.bsp.gsa.gov
inventory_ckan_solr_host: datagov-solrm1d.dev-ocsit.bsp.gsa.gov
inventory_ckan_solr_port: "8983"
inventory_ckan_who_ini_path: "etc_ckan_who.saml2.ini.j2"

# Inventory Next
inventory_next_ckan_envs: |
  {{ newrelic_app_envs }}
inventory_next_ckan_redis_host: "redis1d.dev-ocsit.bsp.gsa.gov"
inventory_next_ckan_redis_password: "{{ redis_password }}"
inventory_next_ckan_s3_bucket_name: "{{ vault_inventory_next_ckan_s3_bucket_name }}"
inventory_next_ckan_s3_bucket_prefix: "{{ vault_inventory_next_ckan_s3_bucket_prefix }}"
inventory_next_ckan_instance_secret: "{{ vault_inventory_next_ckan_instance_secret }}"
inventory_next_ckan_instance_uuid: "{{ vault_inventory_next_ckan_instance_uuid }}"
inventory_next_ckan_service_url: https://inventory-next-datagov.dev-ocsit.bsp.gsa.gov
inventory_next_ckan_solr_host: datagov-solrm1d-v2.dev-ocsit.bsp.gsa.gov
inventory_next_ckan_who_ini_secret: "{{ vault_inventory_next_ckan_who_ini_secret }}"
inventory_next_datastore_login_host: "{{ vault_inventory_next_datastore_login_host }}"
inventory_next_datastore_db_name: "{{ vault_inventory_next_datastore_db_name }}"
inventory_next_datastore_user: "{{ vault_inventory_next_datastore_user }}"
inventory_next_datastore_pass: "{{ vault_inventory_next_datastore_pass }}"
inventory_next_datastore_ro_user: "{{vault_inventory_next_datastore_ro_user }}"
inventory_next_datastore_ro_pass: "{{ vault_inventory_next_datastore_ro_pass }}"
inventory_next_postgresql_login_host: "{{ vault_inventory_next_postgresql_login_host }}"
inventory_next_postgresql_login_user: "{{ vault_inventory_next_postgresql_login_user }}"
inventory_next_postgresql_login_password: "{{ vault_inventory_next_postgresql_login_password }}"
inventory_next_postgresql_db_name: "{{ vault_inventory_next_postgresql_db_name }}"
inventory_next_datapusher_db_name: "{{ vault_inventory_next_datapusher_db_name }}"

# New Relic
newrelic_enabled: true
newrelic_license_key: "{{ vault_newrelic_license_key }}"

# public urls
catalog_host_public: catalog-datagov.dev-ocsit.bsp.gsa.gov
catalog_host_admin: admin-catalog-datagov.dev-ocsit.bsp.gsa.gov

catalog_url_public: https://{{ catalog_host_public }}
catalog_url_admin: https://{{ catalog_host_admin }}

ckan_site_domain: "{{ catalog_host_public }}"

# next public urls
catalog_host_public_next: catalog-next-datagov.dev-ocsit.bsp.gsa.gov
catalog_host_admin_next: admin-catalog-next-datagov.dev-ocsit.bsp.gsa.gov


# Redis
redis_password: "{{ vault_redis_password }}"


# solr
solr_master_server: tempdatagovsolrm1d.dev-ocsit.bsp.gsa.gov
solr_java_packages:
  - openjdk-8-jdk
solr_cores:
  - catalog
  - inventory
solr_xms: 8192m
solr_xmx: 12288m

# SecOps user
secops_user: "{{ vault_secops_user }}"
secops_user_public_key: "{{ vault_secops_user_public_key }}"

# TrendMicro
trendmicro_deb_url: https://dsm.sec.helix.gsa.gov/software/agent/Ubuntu_14.04/x86_64/
trendmicro_policy_id_app: "{{ vault_trendmicro_policy_id_app }}"
trendmicro_policy_id_jumpbox: "{{ vault_trendmicro_policy_id_jumpbox }}"
trendmicro_policy_id_web: "{{ vault_trendmicro_policy_id_web }}"

# List of CodeIgniter pre-approved admin emails
codeigniter_pre_approved_admins: "{{ vault_codeigniter_pre_approved_admins }}"

# App environment
web_app_env: production
real_ansible_env: staging

# postfix
default_email_from: no-reply-staging@data.gsa.gov
postfix_raw_options:
  - |
    smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
    smtpd_tls_mandatory_ciphers = high
    smtpd_tls_mandatory_exclude_ciphers = aNULL, MD5
  - |
    # Postfix needs a value set https://github.com/GSA/datagov-deploy/issues/1795
    smtpd_relay_restrictions = permit_mynetworks, reject_unauth_destination
postfix_relayhost: smtp.gsa.gov
postfix_relayhost_port: 25
postfix_relaytls: true
postfix_sasl_auth_enable: false
postfix_aliases:
  - user: postmaster
    alias: root
  - user: root
    alias: "{{ datagov_team_email }}"
postfix_sender_canonical_maps:
  - sender: "@{{ ansible_fqdn }}"
    rewrite: no-reply-staging+{{ ansible_fqdn }}@data.gsa.gov
postfix_transport_maps:
  - pattern: "{{ datagov_team_email }}"  # deliver mail to the data.gov team normally
    result: smtp
  - pattern: "*"  # discard all other mail
    result: "discard:"


# SAML
saml2_idp_entry: login.test.max.gov
saml2_idp_metadata_url: "https://{{ saml2_idp_entry }}/idp/shibboleth"
saml_idp_cert_fprint: "7A43DACB95D67FB6A804FD37C8A7DCA5B0384939"
saml2_sp_public_certificate: "{{ vault_saml2_sp_public_certificate }}"
saml2_sp_private_key: "{{ vault_saml2_sp_private_key }}"


# smoke tests
smoke_enable_cdn_checks: false


# td-agent
elasticsearch_endpoint: "{{ vault_elasticsearch_endpoint }}"
bsp_elasticsearch_endpoint: "{{ vault_bsp_elasticsearch_endpoint }}"
bsp_shared_key: "{{ vault_bsp_shared_key }}"
system: "es"

# nessus
nessus_agent_key: "{{ vault_nessus_agent_key }}"
nessus_agent_host: "{{ vault_nessus_agent_host }}"
nessus_agent_port: "{{ vault_nessus_agent_port }}"
nessus_agent_group: "{{ vault_nessus_agent_group }}"

# saxon license
fgdc2iso_saxon_license: "{{ vault_fgdc2iso_saxon_license }}"


# ckan
# Auth cookie `auth_tkt` must be HTTPS-only (SECURE) on Production
who_secure: True

# jumpbox users
users: "{{ vault_users }}"

# Automated CI tests
ci_inventory: inventories/staging
ci_ssh_config_host: '*.dev-ocsit.bsp.gsa.gov'
ci_deploy_version: develop

# hostname needed for smoke test, IP address needed for ALB health check
wordpress_nginx_server_name: wordpress-datagov.dev-ocsit.bsp.gsa.gov $hostname {{ ansible_default_ipv4.address }}
wordpress_project_git_version: fcs
wordpress_service_url: https://wordpress-datagov.dev-ocsit.bsp.gsa.gov
