---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: ckan-inventory-app-bionic
    image: ubuntu:bionic
    groups:
      - bionic
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  lint: |
    set -e
    ansible-lint
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
  inventory:
    group_vars:
      all:
        python_home: /usr
        inventory_ckan_solr_port: 8983
        db_is_setup: false
        inventory_ckan_envs: |
          TEST_ENV=1
      bionic:
        inventory_app_repo_branch: fcs
        inventory_next: true
        datapusher_build_pkg_branch: datagov/inventory-next
scenario:
  name: default
  # TODO fix idempotency
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint: |
    set -e
    flake8
