---
# common
common_newrelic_enabled: "{{ datagov_in_service | default(true) }}"
common_filebeat_logstash_output: "{{ vault_common_filebeat_logstash_output }}"
common_filebeat_config:
  filebeat.config.modules:
    enabled: true
    path: ${path.config}/modules.d/*.yml
  filebeat.modules:
    - module: system
      syslog:
        enabled: true
  output.logstash:
    hosts: ["{{ common_filebeat_logstash_output }}"]

filebeat_enabled: true
nessus_agent_enabled: true
trendmicro_enabled: true
# TODO prefix these with common_
filebeat_config: "{{ common_filebeat_config }}"
products:
  - filebeat


# data.gov-wide variables
datagov_environment: mgmt
default_tls_host_key: "{{ vault_default_tls_host_key }}"
default_tls_host_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIIF8zCCBNugAwIBAgITHQABhtGTccqaE4TQOAACAAGG0TANBgkqhkiG9w0BAQsF
  ADBvMRMwEQYKCZImiZPyLGQBGRYDZ292MRMwEQYKCZImiZPyLGQBGRYDZ3NhMRIw
  EAYKCZImiZPyLGQBGRYCZHMxEzARBgoJkiaJk/IsZAEZFgNlbnQxGjAYBgNVBAMT
  EUVDT0gyUy1JU1NDQTAxKDEpMB4XDTIxMDEwNTEzMjQ0MFoXDTIzMDQxMDEzMjQ0
  MFowgeoxCzAJBgNVBAYTAlVTMR0wGwYDVQQIExREaXN0cmljdCBvZiBDb2x1bWJp
  YTETMBEGA1UEBxMKV2FzaGluZ3RvbjEoMCYGA1UEChMfR2VuZXJhbCBTZXJ2aWNl
  cyBBZG1pbmlzdHJhdGlvbjEqMCgGA1UECxMhVGVjaG5vbG9neSBUcmFuc2Zvcm1h
  dGlvbiBTZXJ2aWNlMS0wKwYDVQQDEyRkYXRhZ292anVtcDFtLm1nbXQtb2NzaXQu
  YnNwLmdzYS5nb3YxIjAgBgkqhkiG9w0BCQEWE2RhdGFnb3ZoZWxwQGdzYS5nb3Yw
  ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDisoWc+NtessiUWzT2ZkYQ
  TyCIu8RGu50RMIu0LO2yt73zN2tB2oXbxjPLnAwsVQ0LM9+JA7seZjPjcClun3Dt
  qr8uYYEo57dGpSRBta4PgmNLSvyrEmFhvD5quA6uT8vOmQcqTe48xWci0tkvq0/6
  PCWOWbsXrGd0YnwYzXF61q+7hDOYkxXq6hAS1MTd/xQ13jT/bULcr/H2MmKfk7u/
  xd8Cd/zYNp91H/jsjQd3NnvwpOgWS0mmwVafoQclJMODs5ZDLTxvvq74ovUpjjSa
  l8whE+lhvUesgjvN60qu2Cd4IhHHxfB4ljbUUO6SzIzngZ2jr2DcfP1vRYuqGR/h
  AgMBAAGjggIKMIICBjATBgNVHSUEDDAKBggrBgEFBQcDATBPBgNVHREESDBGgiRk
  YXRhZ292anVtcDFtLm1nbXQtb2NzaXQuYnNwLmdzYS5nb3aCHmplbmtpbnMubWdt
  dC1vY3NpdC5ic3AuZ3NhLmdvdjAdBgNVHQ4EFgQUOPElQgGilU/DraXoCf5BVrJK
  owowHwYDVR0jBBgwFoAUSUzJ8P9khZrHYiv+yyi0KExFIhgwTAYDVR0fBEUwQzBB
  oD+gPYY7aHR0cDovL2dzYXBraS5lbnQuZHMuZ3NhLmdvdi9nc2FjZXJ0cy9FQ09I
  MlMtSVNTQ0EwMSgyKS5jcmwwgacGCCsGAQUFBwEBBIGaMIGXMGUGCCsGAQUFBzAC
  hllodHRwOi8vZ3NhcGtpLmVudC5kcy5nc2EuZ292L2dzYWNlcnRzL0VDT0gyUy1J
  U1NDQTAxLmVudC5kcy5nc2EuZ292X0VDT0gyUy1JU1NDQTAxKDIpLmNydDAuBggr
  BgEFBQcwAYYiaHR0cDovL2dzYW9jc3AuZW50LmRzLmdzYS5nb3Yvb2NzcDALBgNV
  HQ8EBAMCBaAwPAYJKwYBBAGCNxUHBC8wLQYlKwYBBAGCNxUIg4mvL4WeoH2C+YMP
  hrCODYSflxE+geqcNYTvZgIBZAIBEzAbBgkrBgEEAYI3FQoEDjAMMAoGCCsGAQUF
  BwMBMA0GCSqGSIb3DQEBCwUAA4IBAQB84p9EsvN2b1QzeR6YRp9X0VnRFY3BSgQx
  DbEj+8bwxBX8HSxUTqQ13q+E3LndWAL5aGfh19RYCU1XJ2U9Qtc/2p2TVnUXPlOE
  VHKUYjmVdd20hPDMVR5RMoJbDjNTGNAL8EzFVhIpgvRe/D9DdTMC+0b15GqfYF/o
  6pgfxBhoVaOiv/RwTmx7wOiAFjHu/BK7tE4p9ju/IEk/ip/iBPe8kt4amg1GmqSF
  HZQncz/D72epa9B6P/nhkv2hGudIJ6wIbfIxPJhW7zYZxoq7psKZ/FnhSJBEp8In
  jpWgOaB/bbEeRYZE/DMGKwDBRHWXmUg6YnrRpScgXj98Y3gXKk+I
  -----END CERTIFICATE-----


# jenkins
jenkins_admin_password: "{{ vault_jenkins_admin_password }}"
jenkins_admins: "{{ datagov_operators_production | map(attribute='email') | list }}"
jenkins_admins_permissions:
  #- Agent/Build
  #- Agent/Configure
  #- Agent/Connect
  #- Agent/Create
  #- Agent/Delete
  #- Agent/Disconnect
  #- Agent/Provision
  - Credentials/Create
  - Credentials/Delete
  - Credentials/ManageDomains
  - Credentials/Update
  - Credentials/View
  - Job/Build
  - Job/Cancel
  #- Job/Configure
  #- Job/Create
  #- Job/Delete
  - Job/Discover
  - Job/Move
  - Job/Read
  - Job/Workspace
  - Lockable Resources/Reserve
  - Lockable Resources/Unlock
  - Lockable Resources/View
  # TODO disable admin once configured
  - Overall/Administer
  - Overall/Read
  - Run/Delete
  - Run/Replay
  - Run/Update
  #- SCM/Tag
  - View/Configure
  - View/Create
  - View/Delete
  - View/Read

jenkins_job_authentication_token: "{{ vault_jenkins_job_authentication_token }}"
jenkins_job_use_polling: true
jenkins_jobs:
  - name: deploy-ci-platform
    git_url: https://github.com/gsa/datagov-deploy.git
  - name: deploy-ci-app-catalog-next
    git_url: https://github.com/gsa/catalog.data.gov.git
    git_ref: fcs

jenkins_saml_authentication_context: "http://idmanagement.gov/ns/assurance/aal/3?hspd12=true"  # Require PIV card authentication
jenkins_saml_sp_entity_id: urn:gov:gsa:SAML:2.0.profiles:sp:sso:gsa:datagov-ci-jenkins
jenkins_saml_keystore_password: "{{ vault_jenkins_saml_keystore_password }}"
jenkins_saml_keystore_path: "{{ playbook_dir }}/files/mgmt/saml-key.jks"
jenkins_saml_private_key_password: "{{ vault_jenkins_saml_private_key_password }}"
jenkins_saml_idp_metadata_url: https://secure.login.gov/api/saml/metadata2022
jenkins_saml_idp_logout_url: https://secure.login.gov/api/saml/logout2022
jenkins_system_message: >
  Data.gov continuous integration and delivery service.
jenkins_home: /data/jenkins
jenkins_host: jenkins.mgmt-ocsit.bsp.gsa.gov
jenkins_tls_key: "{{ default_tls_host_key }}"
jenkins_tls_cert: "{{ default_tls_host_certificate }}"
jenkins_workflow: production
jenkins_url: ci-datagov.mgmt-ocsit.bsp.gsa.gov


# jumpbox
jumpbox_operators: "{{ datagov_operators_production }}"


# nessus
nessus_agent_key: "{{ vault_nessus_agent_key }}"
nessus_agent_host: "{{ vault_nessus_agent_host }}"
nessus_agent_port: "{{ vault_nessus_agent_port }}"
nessus_agent_group: "{{ vault_nessus_agent_group }}"


# New Relic
newrelic_license_key: "{{ vault_newrelic_license_key }}"


# postfix
default_email_from: no-reply-mgmt@data.gsa.gov
postfix_raw_options:
  - |
    smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
    smtpd_tls_mandatory_ciphers = high
    smtpd_tls_mandatory_exclude_ciphers = aNULL, MD5
  - |
    # Postfix needs a value set https://github.com/GSA/datagov-deploy/issues/1795
    smtpd_relay_restrictions = permit_mynetworks, reject_unauth_destination
postfix_relayhost: smtp.gsa.gov
postfix_relayhost_port: 25
postfix_relaytls: true
postfix_sasl_auth_enable: false
postfix_aliases:
  - user: postmaster
    alias: root
  - user: root
    alias: "{{ datagov_team_email }}"
postfix_sender_canonical_maps:
  - sender: "@{{ ansible_fqdn }}"
    rewrite: no-reply-mgmt+{{ ansible_fqdn }}@data.gsa.gov


# TrendMicro
trendmicro_enabled: true
trendmicro_policy_id_jumpbox: "{{ vault_trendmicro_policy_id_jumpbox }}"
trendmicro_policy_id_mgmt_app: "{{ vault_trendmicro_policy_id_mgmt_app }}"
trendmicro_policy_id_mgmt_web: "{{ vault_trendmicro_policy_id_mgmt_web }}"
