---
driver:
  name: docker
  use_sudo: false

transport:
  max_ssh_sessions: 5

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: false
  # The config expects ~/ansible-secret.txt, no easy way to override so we just
  # create the file.
  custom_pre_play_command: |
    echo fake-password > ~/ansible-secret.txt
  ansible_extra_flags: >-
    --skip-tags=skip_in_kitchen <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  # kitchen-ansible sets ANSIBLE_ROLE_PATH which ignores our ansible.cfg
  # role_path. To work around, we override the env variable so roles/vendor is
  # included.
  # https://github.com/neillturner/kitchen-ansible/issues/284
  env_vars:
    ANSIBLE_ROLES_PATH: /tmp/kitchen/roles:/tmp/kitchen/roles/vendor

  extra_vars:
    default_tls_host_certificate: |-
      -----BEGIN CERTIFICATE-----
      MIIEGTCCAwGgAwIBAgIJAL+dmeInc15LMA0GCSqGSIb3DQEBCwUAMIGiMQswCQYD
      VQQGEwJVUzELMAkGA1UECAwCREMxEzARBgNVBAcMCldhc2hpbmd0b24xKDAmBgNV
      BAoMH0dlbmVyYWwgU2VydmljZXMgQWRtaW5pc3RyYXRpb24xDDAKBgNVBAsMA1RU
      UzEVMBMGA1UEAwwMZGF0YWdvdi50ZXN0MSIwIAYJKoZIhvcNAQkBFhNkYXRhZ292
      aGVscEBnc2EuZ292MB4XDTE5MDIyMjAwNTAyM1oXDTIwMDIyMjAwNTAyM1owgaIx
      CzAJBgNVBAYTAlVTMQswCQYDVQQIDAJEQzETMBEGA1UEBwwKV2FzaGluZ3RvbjEo
      MCYGA1UECgwfR2VuZXJhbCBTZXJ2aWNlcyBBZG1pbmlzdHJhdGlvbjEMMAoGA1UE
      CwwDVFRTMRUwEwYDVQQDDAxkYXRhZ292LnRlc3QxIjAgBgkqhkiG9w0BCQEWE2Rh
      dGFnb3ZoZWxwQGdzYS5nb3YwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
      AQC2vHGrABrdODX95iYCYykVenBdIYHGqrUuRNhgOOqm+L12NKw/0zrRGO34HIcw
      yrpVL7zF+lDTvcjWjP7EJtbQ0k4W2bAkv2NxWhVxtlnxC4dJ0a2XhUwD2PfaK95G
      uAPRKNZsNnoUAOWC8PAh5i5T0kXfWwSFb/oUBB8nMybcbL6y30G3fF/8liTwgh9Q
      unyaz7vOajkvnHRW7d1R9Jlpb6zOwLNT/yvMeP68XGeQK1iGoaQ6jcfeAEwP/1mH
      RDZTVg1haL9R/1eqJNbo6WBt5syhJ2pmauFINyqgT5eq+Uv4Yf6eYdRU+zP3MQtq
      yY0Q09aXp2gieA42YYQ/WrbTAgMBAAGjUDBOMB0GA1UdDgQWBBSSiGn2sABS9OFg
      J1thma17rfsEPjAfBgNVHSMEGDAWgBSSiGn2sABS9OFgJ1thma17rfsEPjAMBgNV
      HRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCa+hxbQjd/BjywbpnmuWJo66wo
      FMerIGny8YbWh8d06P6Fcx45u04jlJQbvSzA6PgWlZoBACQt9ZKFjDR06XXtapQo
      wTit+d9dhbISgbntSckF0FqMynoZ/B6tXZ6JoHd7FyZ3KWRAbEL41DMG2AW46JBp
      4TaVjRTxOe2PA6VNhZwcH+yRSppguqh3UNus5BzVl53avwXomrE2svjTNEu8hMYZ
      nwZtkNpsn7jZ3EbFznxKysA1aXmxZYNOnkJHSYEMs9kpdo9ymikZTzE+r6j+qVEJ
      iXN+eL6gQ9i1vWc6MbfAdR7Zib3dHZmEQtYyXbHqnmmPI9Y2ousd+c6HPu+z
      -----END CERTIFICATE-----

    default_tls_host_key: |-
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC2vHGrABrdODX9
      5iYCYykVenBdIYHGqrUuRNhgOOqm+L12NKw/0zrRGO34HIcwyrpVL7zF+lDTvcjW
      jP7EJtbQ0k4W2bAkv2NxWhVxtlnxC4dJ0a2XhUwD2PfaK95GuAPRKNZsNnoUAOWC
      8PAh5i5T0kXfWwSFb/oUBB8nMybcbL6y30G3fF/8liTwgh9Qunyaz7vOajkvnHRW
      7d1R9Jlpb6zOwLNT/yvMeP68XGeQK1iGoaQ6jcfeAEwP/1mHRDZTVg1haL9R/1eq
      JNbo6WBt5syhJ2pmauFINyqgT5eq+Uv4Yf6eYdRU+zP3MQtqyY0Q09aXp2gieA42
      YYQ/WrbTAgMBAAECggEADEeVi9wx8fO5DRrOKxLmy96ydk+uHN+T1UwjDjRE8Ht+
      n9biTFexeCOouieQniLBasAOe29axx/VwzUuWZgSj23SeY6fW5jQ4ekfz8hlOuF/
      ceJ5O9llRkzqOur/wNjUyNVps1Pl2DpHMglm2aBSNKfIsj23jA/+SiIMxeGWFvHK
      liADcv5bQCqir74YR6iXpo+AUXYVE5PbWTGqPxd1Ccve/1UKv7rj453BKQboJ1Lj
      CivxIvJDPtiu2XzFf2OK3N1D5TsuCvSoVsNMRbt5xj9nSu2WHcNCanja3WVcR+sG
      iWIgg7BsRsg9FdJXNFK5/tfZsOHWp/IeJ541kM2ZAQKBgQDvm3V9reHCofdUGppH
      2UeT2q1bI1JMGQOeXYUoI1dpLjbrNsikdlOTg/lctLpfAkirawJRqjDaadrfTfTQ
      zDALgiu7vnIv6o2IUG7o8je8qPRaWL7Oc73Xi7khfoKSe923FROJwoZFUB3Vw6Fc
      nUlWqnIf5cCslyee4AUm7mJkoQKBgQDDPO35znChoAhx1LKYHs9CFfthT1e4cXTb
      ud+OTtWupak/blip6LxbrvFJvp56H/YR9VEBP3t+A5zW5D42LaYObS0QnpldDndu
      bMxOoWAOKVNQ5cVSgsF9MjAQrJmJaUbrXC0YrUzLwHmgWUMgHZtINmBJmjZHpcap
      1JiEb7Xy8wKBgQCbj83PA/Zf+/Hsy7zAywOarc4BLsR+nXro9YS/E3rr0dJcEdxg
      UmZejr91/exGROBTUo1V4e4Hz9QHSMCaUwcaYa/tG29dRqYPC1GGscOYHAVRJu7y
      cNifOZq/cThqzDqdY/SkawPrumE0aOe5jnCP8OdZaDwYkaZqkr0lkn2VIQKBgGOJ
      +/aBpvDwS33lqExgYODbnjdloV6bEa443N6MGOua8GgzlSbDTs0bq08izV+MTgOn
      4+3T9N0xcFQrOACdU21FglVX1u8XwhJdi+iG5Bc0QJMdInZHzehLny/RH9JsB0lV
      zHQpXt7+ucPj3pJQJewyNPMxmXz76waJKl1TKxu7AoGBAOWmw6ob5XrTfOkqBQZ2
      eJAyMh2KRBG5SD4QMTZcZ+/Qal5DvCb9eLD45OLX0Dob0TE9Fxa5dY3Oiqm0V43l
      KtLS6UG/GI2y19z79DddVz0huaBh+5G/ga+Li5PcWQpNRa6Ytkqpv3pSIA1g858Q
      fIV3Y1kH5D8tMuygZyavoRiP
      -----END PRIVATE KEY-----

    kitchen: true
    python_home: /usr
  # For debugging
  #ansible_verbose: true
  #ansible_diff: true
  #ansible_verbosity: 2

platforms:
 # Ubuntu Trusty with Upstart
  - name: ubuntu-14.04
    driver_config:
      image: rndmh3ro/docker-ubuntu1404-ansible:latest
      platform: ubuntu

suites:
  - name: catalog-web
    provisioner:
      hosts:
        - catalog-web
      playbook: catalog.yml
      extra_vars:
        redis_password: fake-redis-password
        ckan_site_domain: http://test-kitchen-datagov.local
      ansible_extra_flags: >-
        --tags=frontend,ami-fix,bsp --skip-tags=solr,db,cron,skip_in_kitchen <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  - name: catalog-harvester
    provisioner:
      hosts:
        - catalog-harvester
      playbook: catalog.yml
      extra_vars:
        redis_password: fake-redis-password
      ansible_extra_flags: >-
        --tags=harvester,ami-fix,bsp --skip-tags=apache,solr,db,saml2,skip_in_kitchen <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  - name: crm-web
    provisioner:
      hosts:
        - crm-web
      playbook: crm-web.yml
      ansible_extra_flags: >-
        --tags=provision --skip-tags=skip_in_kitchen <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  - name: dashboard-web
    provisioner:
      hosts:
        - dashboard-web
      playbook: dashboard-web.yml
      extra_vars:
        dashboard_user: kitchen # TODO this should just be the default user (ubuntu) but the role should ensure the user exists
      ansible_extra_flags: >-
        --tags=provision --skip-tags=skip_in_kitchen <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
#  - name: datagov-web
#    provisioner:
#      playbook: datagov-web.yml
  - name: efk-nginx
    provisioner:
      hosts:
        - efk_nginx
      playbook: efk-nginx.yml
  - name: efk-stack
    provisioner:
      hosts:
        - efk_nginx
      playbook: efk-stack.yml
#  - name: elastalert
#    provisioner:
#      playbook: elastalert.yml
#  - name: elasticsearch
#    provisioner:
#      playbook: elasticsearch.yml
  - name: fluentd
    provisioner:
      playbook: common/fluentd.yml
#  - name: hardening
#    provisioner:
#      playbook: hardening.yml
#  - name: harvester
#    provisioner:
#      playbook: harvester.yml
  - name: inventory-web
    provisioner:
      hosts: inventory-web
      playbook: inventory.yml
      ansible_extra_flags: >-
        --skip-tags="solr,db,deploy-rollback,skip_in_kitchen" <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  - name: jekyll
    provisioner:
      hosts:
        - jekyll-web
      playbook: jekyll.yml
      extra_vars:
        jekyll_apps:
          - name: sdg-indicators
            repo: https://github.com/GSA/sdg-indicators/
            config: _config_prod.yml
            branch: master
            port: "8000"
            s3_bucket: fakebucket
            secret_key: testsecret
#  - name: kibana
#    provisioner:
#      playbook: kibana.yml
  - name: logrotate
    provisioner:
      playbook: logrotate.yml
  - name: misc
    provisioner:
      hosts:
        - web
      playbook: common/misc.yml
#  - name: nessus
#    provisioner:
#      playbook: nessus.yml
  - name: newrelic-infrastructure
    provisioner:
      playbook: newrelic-infrastructure.yml
#  - name: newrelic-php
#    provisioner:
#      playbook: newrelic-php.yml
#  - name: newrelic-python
#    provisioner:
#      playbook: newrelic-python.yml
  - name: postfix
    provisioner:
      playbook: common/postfix.yml
  - name: secops
    provisioner:
      playbook: common/secops.yml
#  - name: solr
#    provisioner:
#      playbook: solr.yml
  - name: trendmicro
    provisioner:
      playbook: common/trendmicro.yml
  - name: web-proxy
    provisioner:
      playbook: web-proxy.yml
    # We use "ubuntu-common" instead of "ubuntu" to avoid kitchen thinking
    # we're talking about the ubuntu platform.
  - name: ubuntu-common
    provisioner:
      playbook: common/ubuntu.yml
  - name: unattended-upgrades
    provisioner:
      playbook: unattended-upgrades.yml
