---
driver:
  name: docker
  use_sudo: false

transport:
  max_ssh_sessions: 5

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: false
  # The config expects ~/ansible-secret.txt, no easy way to override so we just
  # create the file.
  custom_pre_play_command: |
    echo fake-password > ~/ansible-secret.txt
  ansible_extra_flags: >-
    --skip-tags=skip_in_kitchen <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  # kitchen-ansible sets ANSIBLE_ROLE_PATH which ignores our ansible.cfg
  # role_path. To work around, we override the env variable so roles/vendor is
  # included.
  # https://github.com/neillturner/kitchen-ansible/issues/284
  env_vars:
    ANSIBLE_ROLES_PATH: /tmp/kitchen/roles:/tmp/kitchen/roles/vendor
  extra_vars:
    kitchen: true
  # For debugging
  #ansible_verbose: true
  #ansible_diff: true
  #ansible_verbosity: 2

platforms:
 # Ubuntu Trusty with Upstart
  - name: ubuntu-14.04
    driver_config:
      image: rndmh3ro/docker-ubuntu1404-ansible:latest
      platform: ubuntu

suites:
  - name: catalog-web
    provisioner:
      hosts:
        - catalog-web
      playbook: catalog.yml
      extra_vars:
        redis_password: fake-redis-password
        ckan_site_domain: http://test-kitchen-datagov.local
      ansible_extra_flags: >-
        --tags=frontend,ami-fix,bsp --skip-tags=solr,db,cron,skip_in_kitchen <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  - name: catalog-harvester
    provisioner:
      hosts:
        - catalog-harvester
      playbook: catalog.yml
      extra_vars:
        redis_password: fake-redis-password
      ansible_extra_flags: >-
        --tags=harvester,ami-fix,bsp --skip-tags=apache,solr,db,saml2,skip_in_kitchen <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
#  - name: crm-web
#    provisioner:
#      playbook: crm-web.yml
  - name: dashboard-web
    provisioner:
      hosts:
        - dashboard-web
      playbook: dashboard-web.yml
      extra_vars:
        dashboard_user: kitchen # TODO this should just be the default user (ubuntu) but the role should ensure the user exists
      ansible_extra_flags: >-
        --tags=provision --skip-tags=skip_in_kitchen <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
#  - name: datagov-web
#    provisioner:
#      playbook: datagov-web.yml
#  - name: efk-nginx
#    provisioner:
#      playbook: ekf-nginx.yml
#  - name: efk-stack
#    provisioner:
#      playbook: ekf-stack.yml
#  - name: elastalert
#    provisioner:
#      playbook: elastalert.yml
#  - name: elasticsearch
#    provisioner:
#      playbook: elasticsearch.yml
#  - name: fluentd
#    provisioner:
#      playbook: fluent.yml
#  - name: hardening
#    provisioner:
#      playbook: hardening.yml
#  - name: harvester
#    provisioner:
#      playbook: harvester.yml
  - name: inventory-web
    provisioner:
      hosts: inventory-web
      playbook: inventory.yml
      ansible_extra_flags: >-
        --skip-tags="solr,db,deploy-rollback,skip_in_kitchen" <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  - name: jekyll
    provisioner:
      hosts:
        - jekyll-web
      playbook: jekyll.yml
      extra_vars:
        jekyll_apps:
          - name: sdg-indicators
            repo: https://github.com/GSA/sdg-indicators/
            config: _config_prod.yml
            branch: master
            port: "8000"
            s3_bucket: fakebucket
            secret_key: testsecret
#  - name: jumpbox
#    provisioner:
#      playbook: jumpbox.yml
#  - name: kibana
#    provisioner:
#      playbook: kibana.yml
  - name: logrotate
    provisioner:
      playbook: logrotate.yml
#  - name: nessus
#    provisioner:
#      playbook: nessus.yml
#  - name: newrelic-infrastructure
#    provisioner:
#      playbook: newrelic-infrastructure.yml
#  - name: newrelic-php
#    provisioner:
#      playbook: newrelic-php.yml
#  - name: newrelic-python
#    provisioner:
#      playbook: newrelic-python.yml
#  - name: postfix
#    provisioner:
#      playbook: postfix.yml
#  - name: secops
#    provisioner:
#      playbook: secops.yml
#  - name: solr
#    provisioner:
#      playbook: solr.yml
#  - name: trendmicro
#    provisioner:
#      playbook: trendmicro.yml
  - name: web-proxy
    provisioner:
      playbook: web-proxy.yml
