---
- name: Catalog worker (harvester) stack
  hosts: catalog-harvester,!v2
  vars:
      app_type: catalog

  roles:
    - role: software/ckan/common

    - role: software/ckan/catalog/ckan-app
      vars:
        app_repo_branch: "{{ catalog_ckan_app_version }}"
      tags:
        - app-deploy

- name: logrotate configuration
  hosts: catalog-harvester,!v2
  roles:
    - role: nickhammond.logrotate
      logrotate_scripts:
        - name: harvest-run
          paths:
            - /var/log/harvester_run.log
            - /var/log/fetch-consumer.log
            - /var/log/gather-consumer.log
          options:
            - compress
            - copytruncate
            - daily
            - missingok
            - rotate 60
