---
- name: Deploy Wordpress
  hosts:  "{{ datagov_web_hosts | default('wordpress-web') }}"
  serial: 1
  roles:
  # TODO remove the die-no-tags role. You should be able to run a role playbook
  # with no tags and have it be idempotent.
  - { role: software/common/tls, tags: [provision, tls] }
  - { role: software/common/php-common, tags: [provision] }
  - { role: geerlingguy.git, tags: [git, provision] }
  - { role: geerlingguy.nginx, tags: [nginx, provision] }
  - { role: geerlingguy.php, tags: [php, provision] }
  - { role: geerlingguy.php-mysql, tags: [php, php-mysql, provision] }
  - { role: geerlingguy.php-memcached, tags: [php, php-memcached, provision] }
  - { role: sbaerlocher.wp-cli, tags: [php, cli, provision] }
  - { role: geerlingguy.composer, tags: [php, provision] }
  - { role: software/wordpress/datagov-sudo-2-init, tags: [provision, deploy, deploy-rollback] }

- name: Deploying Data.gov
  hosts: wordpress-web
  serial: 1
  become: no
  roles:
  - { role: software/wordpress/datagov-deploy, tags: [deploy, provision] }
  - { role: software/common/datagov-deploy-rollback, tags: [deploy-rollback] }


- name: Cleanup
  hosts: wordpress-web
  serial: 1
  roles:
  - { role: software/common/php-fixes, tags: [php, provision, deploy] }
  - { role: software/wordpress/datagov-sudo-3-cleanup, tags: [provision, deploy, deploy-rollback, cleanup] }
