---
- name: Deploy Tomcat
  hosts: catalog-fgdc2iso
  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.java
    - role: robertdebock.tomcat
      vars:
        tomcat_version9: "9.0.48"
        tomcat_instances:
          - name: "tomcat"
            version: 9
            address: "127.0.0.1"

- name: Deploy nginx
  hosts: catalog-fgdc2iso
  roles:
    - role: geerlingguy.nginx
      vars:
        nginx_upstreams:
          - name: "tomcat"
            servers:
              - "127.0.0.1:8080"
        nginx_vhosts:
          - listen: "80"
            server_name: "fgdc2iso"
            filename: "fgdc2iso.80.conf"
            extra_parameters: |
              location / {
                proxy_pass http://tomcat;
              }
          - listen: "443 ssl"
            server_name: "fgdc2iso"
            filename: "fgdc2iso.443.conf"
            extra_parameters: |
              location / {
                proxy_pass http://tomcat;
              }
              ssl_certificate     {{ fgdc2iso_tls_certificate_filepath | default(default_tls_host_certificate_filepath) }};
              ssl_certificate_key {{ fgdc2iso_tls_key_filepath | default(default_tls_host_key_filepath) }};
              ssl_protocols       TLSv1.2 TLSv1.3;
              ssl_ciphers         HIGH:!aNULL:!MD5;
      tags: [nginx, provision]

- name: Deploy fgdc2iso
  hosts: catalog-fgdc2iso
  roles:
    - role: gsa.datagov-deploy-fgdc2iso

  # Host-level smoke tests
  tasks:
    - name: flush handlers
      meta: flush_handlers

    - name: assert app is up
      uri:
        url: https://{{ ansible_fqdn }}/fgdc2iso/
        validate_certs: false
        method: POST
        body: |
          <metadata>
            <idinfo>
              <citation>
                <citeinfo>
                  <title>ABC 123</title>
                </citeinfo>
              </citation>
            </idinfo>
          </metadata>
        status_code: 200
        return_content: yes
      retries: 3
      delay: 10
      register: result
      until: not result.failed
      tags:
        - smoke

    - name: assert valid iso returned
      assert:
        that: "'<gco:CharacterString>ABC 123' in result.content"
      tags:
        - smoke

- name: logrotate configuration
  hosts: catalog-fgdc2iso
  roles:
    - role: nickhammond.logrotate
      logrotate_scripts:
        - name: nginx
          paths:
            - /var/log/nginx/*.log
          options:
            - compress
            - copytruncate
            - daily
            - missingok
            - rotate 60
