---
- name: Install Jekyll Apps
  hosts: jekyll-web
  remote_user: ubuntu
  become: yes
  become_method: sudo

  vars:
    ruby_version: "2.3.0"
    gemset: "jekyll"
    jekyll_apps:
      - {
          name: "sdg-indicators-usa",
          repo: "https://github.com/GSA/sdg-indicators-usa/",
          config: "_config.yml",
          branch: "prod-pages",
          port: 8000,
          s3_bucket: "{{ s3_bucket_sdg | default('') }}",
          secret_key: "{{ jekyll_webhook_secret | default('') }}"
        }
      - {
          name: "data-federation",
          repo: "https://github.com/GSA/us-data-federation",
          config: "_config_prod.yml",
          branch: "master",
          port: 8001,
          s3_bucket: "{{ s3_bucket_federation | default('') }}",
          secret_key: "{{ jekyll_webhook_secret | default('') }}"
        }
      - {
          name: "data-strategy",
          repo: "https://github.com/GSA/data-strategy",
          config: "_config_prod.yml",
          branch: "master",
          port: 8002,
          s3_bucket: "{{ s3_bucket_strategy | default('') }}",
          secret_key: "{{ jekyll_webhook_secret | default('') }}"
        }

  roles:
    - software/ubuntu/common
    - {role: software/common/secops-ssh, tags: ['secops'] }
    - {role: software/common/trendmicro, tags: ['trendmicro', 'skip_in_kitchen'] }
    - {role: monitoring/fluentd/kernel, tags: ['frontend', 'harvester', 'fluentd'] }
    - {role: monitoring/fluentd/limits, tags: ['frontend', 'harvester', 'fluentd'] }
    - {role: monitoring/fluentd/td-agent, tags: ['frontend', 'harvester', 'fluentd', 'skip_in_kitchen'] }
    - {role: software/common/misc, tags: ['misc'] }
    - role: gsa.datagov-deploy-apache2
    - role: rvm.ruby
      rvm1_user: root
      rvm1_install_path: /usr/local/rvm
      rvm1_install_flags: '--auto-dotfiles'
      rvm1_rvm_check_for_updates: False
      rvm1_rubies: ['ruby-{{ruby_version}}']
    - software/jekyll
