---
- name: ansistrano.deploy
  version: 3.3.0
- name: ANXS.apt
  version: v2.0.0
- name: ANXS.build-essential
  version: v2.0.0
- name: avanov.pyenv
  version: 1.1.0
- name: davidwittman.redis
  version: 1.2.7
# TODO this is no longer supported, switch to upstream https://github.com/telus/ansible-upstart
- name: dwcramer.upstart
  src: https://github.com/dwcramer/ansible-upstart.git
  version: 0.2.0
- name: geerlingguy.composer
  version: 1.7.6
- name: geerlingguy.git
  version: 2.0.4
- name: geerlingguy.java
  version: 1.9.6
- name: geerlingguy.jenkins
  version: 3.8.0
- name: geerlingguy.nginx
  version: 2.6.3
- name: geerlingguy.php
  version: 3.7.0
- name: geerlingguy.php-versions
  version: 3.1.1
- name: geerlingguy.php-memcached
  version: 2.0.2
- name: geerlingguy.php-mysql
  version: 2.0.2
- name: geerlingguy.pip
  version: 1.3.0
- name: geerlingguy.solr
  version: 5.1.0
- name: gsa.ansible-os-ubuntu-14
  src: https://github.com/GSA/ansible-os-ubuntu-14.git
  version: master
- name: gsa.ansible-os-ubuntu-16
  src: https://github.com/GSA/ansible-os-ubuntu-16
  version: 1.0.4
- name: gsa.datagov-deploy-dashboard
  src: https://github.com/GSA/datagov-deploy-dashboard
  version: v1.0.2
- name: gsa.datagov-deploy-apache2
  src: https://github.com/GSA/datagov-deploy-apache2
  version: v1.3.1
- name: gsa.datagov-deploy-common
  src: https://github.com/GSA/datagov-deploy-common
  version: v4.0.2
- name: gsa.datagov-deploy-jenkins
  src: https://github.com/GSA/datagov-deploy-jenkins
  version: feature/jobs
- name: gsa.datagov-deploy-jumpbox
  src: https://github.com/GSA/datagov-deploy-jumpbox
  version: v2.0.1
- name: gsa.datagov-deploy-pycsw
  src: https://github.com/GSA/datagov-deploy-pycsw
  version: v1.0.4
- name: gsa.datagov-deploy-redis
  src: https://github.com/GSA/datagov-deploy-redis
  version: v1.0.2
- name: gsa.datagov-deploy-solr
  src: https://github.com/GSA/datagov-deploy-solr.git
  version: v1.0.0
- name: gsa.datagov-deploy-wordpress
  src: https://github.com/GSA/datagov-deploy-wordpress.git
  version: v1.0.4
- name: jnv.unattended-upgrades
  version: v1.8.0
- name: jobscore.beats
  version: v1.0.0
- name: newrelic.newrelic-infra
  version: 0.7.0
- name: nickhammond.logrotate
  version: v0.0.5
- name: nleutner.newrelic-php
  version: 1.0.0
- name: oefenweb.postfix
  version: v2.10.4
- name: sbaerlocher.wp-cli
  version: 1.3.1
