---
# Platform plays
#################
- import_playbook: common.yml
  tags:
    - common


# Service plays
################
- import_playbook: jumpbox.yml
  tags:
    - jumpbox
- import_playbook: fgdc2iso.yml
  tags:
    - fgdc2iso
- import_playbook: solr.yml
  tags:
    - solr
- import_playbook: redis.yml
  tags:
    - redis


# Application plays
####################
- import_playbook: catalog.yml
  tags:
    - catalog
- import_playbook: dashboard-web.yml
  tags:
    - dashboard
- import_playbook: datagov-web.yml
  tags:
    - wordpress
- import_playbook: inventory.yml
  tags:
    - inventory

# Validation and cleanup
#########################
- import_playbook: smoke.yml
  tags:
    - smoke
