---
- name: Host smoke tests
  # TODO This check should be enabled on jumpbox and jenkins
  # Skip the check on the delegate host because the firewall allows
  # localhost access and the check will fail.
  hosts: "!jumpbox:!jenkins"
  tasks:
    - name: assert smtp port is closed
      wait_for:
        host: "{{ ansible_fqdn }}"
        port: 25
        state: stopped  # closed
        msg: smtp port expected to be closed
        timeout: 10
      delegate_to: localhost
      become: false


- name: catalog.data.gov cache smoke tests
  hosts: all
  gather_facts: false
  tasks:
    - name: assert static assets are cached
      # This test is a bit tricky because the URLs for most assets are
      # generated at build time and change with each deploy. Use one that doesn't change.
      vars:
        url: https://catalog.data.gov/fanstatic/datagovtheme/images/favicon.ico
      block:
        - name: prime the cache
          uri:
            url: "{{ url }}"
            status_code: 200
            follow_redirects: none
        - name: wait for 10 seconds
          pause:
            seconds: 10
        - name: check the cache
          uri:
            url: "{{ url }}"
            status_code: 200
            follow_redirects: none
          register: second_response
        - name: assert second request receives cached response
          assert:
            that: second_response.x_cache == "Hit from cloudfront"
            fail_msg: |
              Response looks like it was not cached when it should be:
              {{ second_response | to_json }}
      delegate_to: localhost
      become: false
      run_once: true
      when: smoke_enable_cdn_checks | default(True)


    - name: assert TTL for 4xx is less than 10 seconds to prevent CPDoS
      block:
        - name: prime the cache
          uri:
            url: https://catalog.data.gov/four04?unique=1
            status_code: 404
            follow_redirects: none
          register: first_response
        - name: wait for 10 seconds
          pause:
            seconds: 10
        - name: check the cache
          uri:
            url: https://catalog.data.gov/four04?unique=1
            status_code: 404
            follow_redirects: none
            return_content: true
          register: second_response
        - name: debug first_response
          debug:
            msg: "first_response={{ first_response | to_json }}"
          when: debug is defined
        - name: assert not cached
          assert:
            that: first_response.x_cache != "Hit from cloudfront"
            fail_msg: |
              Response looks like it was cached when it shouldn't be:
              {{ second_response.content }}
      delegate_to: localhost
      become: false
      run_once: true
      when: smoke_enable_cdn_checks | default(True)
