- hosts: all
  roles:
  - role: jnv.unattended-upgrades
    unattended_origins_patterns:
    - 'origin=Ubuntu,archive=${distro_codename}-security'
    - 'o=Ubuntu,a=${distro_codename}'
    - 'o=Ubuntu,a=${distro_codename}-updates'
    unattended_package_blacklist: []
    unattended_mail: "{{ datagov_team_email }}"
    unattended_mail_only_on_error: true
