---

- name: make sure ckanext-saml2 dependency packages are installed
  apt: name={{ packages }} state=present
  vars:
    packages:
      - memcached
      - swig
      - xmlsec1

- name: create directory for application logs
  file: dest=/var/log/ckan owner=www-data group=www-data mode=0755 state=directory

# Work-around https://github.com/GSA/catalog-app/issues/76
- name: create dynamic_menu dir for ckanext-datagovtheme
  file: path=/var/tmp/ckan/dynamic_menu owner=www-data group=www-data mode=0755 state=directory

- name: create CKAN temp directory
  file: path=/var/tmp/ckan owner=www-data group=www-data mode=0755 state=directory

- name: create CKAN storage directory
  file: path=/var/lib/ckan owner=www-data group=www-data mode=0755 state=directory

# Work-around https://github.com/GSA/catalog-app/issues/76
- name: pre-populate menu.json for ckanext-datagovtheme
  copy: src=menu.json dest=/var/tmp/ckan/dynamic_menu/menu.json owner=www-data group=www-data mode=0644 force=false
  register: menu_json

# Work-around https://github.com/GSA/catalog-app/issues/76
- name: set menu.json as stale (old modification time)
  file: path=/var/tmp/ckan/dynamic_menu/menu.json modification_time=202001010000.00 state=file
  when: menu_json is changed

- name: Remove old rollback code
  file: path="{{ project_source_rollback_path }}" state=absent

- name: Check whether new code dir exists
  stat: path="{{ project_source_new_code_path }}"
  register: p

- name: Create rollback code
  command: cp --recursive --preserve "{{ project_source_new_code_path }}" "{{ project_source_rollback_path }}"
  when: p.stat.isdir is defined and p.stat.isdir
  tags: skip_ansible_lint

- name: Symlink current dir with rollback code
  file:
    src: "{{ project_source_rollback_path }}"
    path: "{{ current_source_symlink }}"
    state: link
  when: p.stat.isdir is defined and p.stat.isdir

- name: Remove new code
  file: path="{{ project_source_new_code_path }}" state=absent

- name: Clone CKAN app
  git:
    repo: '{{ app_repo }}'
    dest: '{{ app_source_path }}'
    version: '{{ app_repo_branch }}'

- name: setup virtualenv for new deployment
  pip:
    name:
      - pip>=19.3.0
      - setuptools>=44.0.0,<45.0.0  # setuptools 45+ requires python 3.5, keep pinned below, but still modern version
    virtualenv: '{{ project_source_new_code_path }}'
    virtualenv_python: "{{ catalog_ckan_python_home }}/bin/python"
    umask: "0022"

- name: install requirements
  pip:
    requirements: "{{ app_source_path }}/requirements-freeze.txt"
    virtualenv: "{{ project_source_new_code_path }}"
    virtualenv_python: "{{ catalog_ckan_python_home }}/bin/python"
    umask: "0022"
  notify:
    - reload apache2
    - reload supervisor

# Configure CKAN
- name: Configure production.ini
  template: src=templates/{{ item }}.j2 dest=/{{ item }} owner=root group=www-data mode=0640
  with_items:
    - etc/ckan/production.ini
  notify:
    - reload apache2
    - reload supervisor

# Add token.dat file
- name: Add token.dat file
  copy:
    content="{{ token_dat }}"
    dest=/etc/ckan/token.dat
    owner=root
    group=www-data
    mode=0640
  notify:
    - reload apache2
    - reload supervisor

- name: Configure who.ini
  copy:
    src: "{{ app_source_path }}/config/environments/{{ env }}/saml2/who.ini"
    dest: /etc/ckan
    remote_src: true
    owner: root
    group: www-data
    mode: 0640
  notify:
    - reload apache2
    - reload supervisor

# TODO remove this after production deploy
- name: undo point site_url in /etc/hosts to localhost
  action: lineinfile dest=/etc/hosts line="127.0.0.1 {{ ckan_site_domain | regex_replace('https?\://','') }}" state=absent
  tags:
   - molecule-notest

- name: Symlink current dir with new code
  file:
    src: "{{ project_source_new_code_path }}"
    path: "{{ current_source_symlink }}"
    state: link
  notify:
    - reload apache2
    - reload supervisor
