---
# Data.gov prerequisites

# TODO this doesn't really belong here. And we shouldn't be installing from
# subversion.
- name: install subversion for composer dependencies
  apt: name=subversion state=present

- name: Ensure log dir exists
  file: path=/var/log/wordpress state=directory owner={{ wordpress_app_user }} group={{ wordpress_app_user }} mode=0755

- name: Copying Data.gov configuration for Nginx
  template:
    src: "datagov.nginx.conf"
    dest: "/etc/nginx/sites-enabled/datagov.nginx.conf"
  notify:
    - reload nginx

- name: Remove old wp cron
  cron:
    name: "Data.gov WordPress cron"
    minute: "*/15"
    user: "www-data"
    job: "cd {{ current_source_symlink }} && wp cron event run --due-now >> /var/log/wp-cron.log 2>&1"
    cron_file: "wordpress-datagov"
    state: absent

- name: Installing required packages
  package: name={{ item }} state=present
  with_items:
    - mariadb-client
    - php{{ wordpress_php_major_minor_version }}-zip
    - nginx-extras

- name: Remove previous deployment rollback folder
  file: path="{{ project_source_rollback_path }}" state=absent
