---

  - include: check_requirements.yml
    tags: checkreqs

  - include: section_01.yml
    tags: section01, MA2

  - include: section_02.yml
    tags: section02

  - include: section_03.yml
    tags: section03

  - include: section_04.yml
    tags: section04

  - include: section_05.yml
    tags: section05

  - include: section_07.yml
    tags: section07

  - include: section_08.yml
    tags: section08

  - include: section_06.yml
    tags: section06

  - include: section_09.yml
    tags: section09

  - include: section_10.yml
    tags: section10

  - include: section_11.yml
    tags: section11

  - include: section_12.yml
    tags: section12

  - include: section_13.yml
    tags: section13

