---

  - name: 7.1.1 Disable IP Forwarding (Scored)
    sysctl: >
      name=net.ipv4.ip_forward
      value={{net_ipv4_ip_forward}}
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.1
      - section7.1.1

  - name: 7.1.2.1 Disable Send Packet Redirects (Scored)
    sysctl: >
      name=net.ipv4.conf.all.send_redirects
      value=0
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.1
      - section7.1.2

  - name: 7.1.2.2 Disable Send Packet Redirects (Scored)
    sysctl: >
      name=net.ipv4.conf.default.send_redirects
      value=0
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.1
      - section7.1.2

  - name: 7.2.1.1 Disable Source Routed Packet Acceptance (Scored)
    sysctl: >
      name=net.ipv4.conf.all.accept_source_route
      value=0
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.2
      - section7.2.1

  - name: 7.2.1.2 Disable Source Routed Packet Acceptance (Scored)
    sysctl: >
      name=net.ipv4.conf.default.accept_source_route
      value=0
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.2
      - section7.2.1

  - name: 7.2.2.1 Disable ICMP Redirect Acceptance (Scored)
    sysctl: >
      name=net.ipv4.conf.all.accept_redirects
      value=0
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.2
      - section7.2.2

  - name: 7.2.2.2 Disable ICMP Redirect Acceptance (Scored)
    sysctl: >
      name=net.ipv4.conf.default.accept_redirects
      value=0
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.2
      - section7.2.2

  - name: 7.2.3.1 Disable Secure ICMP Redirect Acceptance (Scored)
    sysctl: >
      name=net.ipv4.conf.all.secure_redirects
      value=0
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.2
      - section7.2.3

  - name: 7.2.3.2 Disable Secure ICMP Redirect Acceptance (Scored)
    sysctl: >
      name=net.ipv4.conf.default.secure_redirects
      value=0
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.2
      - section7.2.3

  - name: 7.2.4.1 Log Suspicious Packets (Scored)
    sysctl: >
      name=net.ipv4.conf.all.log_martians
      value=1
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.2
      - section7.2.4

  - name: 7.2.4.2 Log Suspicious Packets (Scored)
    sysctl: >
      name=net.ipv4.conf.default.log_martians
      value=1
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.2
      - section7.2.4

  - name: 7.2.4.3 Log Suspicious Packets (flushing tables) (Scored)
    sysctl: >
      name=net.ipv4.route.flush
      value=1
      state=present
    tags:
      - section7
      - section7.2
      - section7.2.4

  - name: 7.2.5 Enable Ignore Broadcast Requests (Scored)
    sysctl: >
      name=net.ipv4.icmp_echo_ignore_broadcasts
      value=1
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.2
      - section7.2.5

  - name: 7.2.6 Enable Bad Error Message Protection (Scored)
    sysctl: >
      name=net.ipv4.icmp_ignore_bogus_error_responses
      value=1
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.2
      - section7.2.6

  - name: 7.2.7.1 Enable RFC-recommended Source Route Validation (Scored)
    sysctl: >
      name=net.ipv4.conf.all.rp_filter
      value=1
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.2
      - section7.2.7

  - name: 7.2.7.2 Enable RFC-recommended Source Route Validation (Scored)
    sysctl: >
      name=net.ipv4.conf.default.rp_filter
      value=1
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.2
      - section7.2.7

  - name: 7.2.8 Enable TCP SYN Cookies (Scored)
    sysctl: >
      name=net.ipv4.tcp_syncookies
      value=1
      state=present
    when: enable_tcp_syncookies
    ignore_errors: yes
    tags:
      - section7
      - section7.2
      - section7.2.8

  - name: 7.3.1.1 Disable IPv6 Router Advertisements (Not Scored)
    sysctl: >
      name=net.ipv6.conf.all.accept_ra
      value=0
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.3
      - section7.3.1

  - name: 7.3.1.2 Disable IPv6 Router Advertisements (Not Scored)
    sysctl: >
      name=net.ipv6.conf.default.accept_ra
      value=0
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.3
      - section7.3.1

  - name: 7.3.2.1 Disable IPv6 Redirect Acceptance (Not Scored)
    sysctl: >
      name=net.ipv6.conf.all.accept_redirects
      value=0
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.3
      - section7.3.2

  - name: 7.3.2.2 Disable IPv6 Redirect Acceptance (Not Scored)
    sysctl: >
      name=net.ipv6.conf.default.accept_redirects
      value=0
      state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.3
      - section7.3.2

  - name: 7.3.3 Disable IPv6 (Not Scored)
    sysctl: >
      name={{ item }}
      value=1
      state=present
    with_items:
      - net.ipv6.conf.all.disable_ipv6
      - net.ipv6.conf.default.disable_ipv6
      - net.ipv6.conf.lo.disable_ipv6
    when: disable_ipv6 == True
    ignore_errors: yes
    tags:
      - section7
      - section7.3
      - section7.3.3

  - name: 7.4.1 Install TCP Wrappers (Scored)
    apt: name=tcpd state=present
    ignore_errors: yes
    tags:
      - section7
      - section7.4
      - section7.4.1

  - name: 7.4.2 Create /etc/hosts.allow (Not Scored)
    debug: msg="*** Verify /etc/hosts.allow ***"
    ignore_errors: yes
    tags:
      - section7
      - section7.4
      - section7.4.2

  - name: 7.4.3 Verify Permissions on /etc/hosts.allow (Scored)
    file: >
        path=/etc/hosts.allow
        owner=root
        group=root
        mode=0644
    tags:
      - section7
      - section7.4
      - section7.4.3

  - name: 7.4.4 Create /etc/hosts.deny (Not Scored)
    debug: msg='*** Verify /etc/hosts.deny ***'
    tags:
      - section7
      - section7.4
      - section7.4.4

  - name: 7.4.5 Verify Permissions on /etc/hosts.deny (Scored)
    file: >
        path=/etc/hosts.deny
        owner=root
        group=root
        mode=0644
    tags:
      - section7
      - section7.4
      - section7.4.5

  - name: 7.5.0 Ensures /etc/modprobe.d/ exists (Not Scored)
    file: >
        path=/etc/modprobe.d
        state=directory
    register: cis_conf_file
    tags:
      - section7
      - section7.5

  - name: 7.5.1-4 Disable DCCP, SCTP, RDS, TIPC (Not Scored)
    lineinfile: >
        dest=/etc/modprobe.d/CIS.conf
        line='install {{ item }} /bin/true'
        state=present
        create=True
    with_items:
        - dccp
        - sctp
        - rds
        - tipc
    ignore_errors: yes
    tags:
      - section7
      - section7.5
      - section7.5.1
      - section7.5.2
      - section7.5.3
      - section7.5.4

  - name: 7.6 Deactivate Wireless Interfaces (Not Scored)
    shell: 'lspci -k | grep -i wifi'
    changed_when: False
    register: lspci_wifi
    failed_when: lspci_wifi.rc == 0
    ignore_errors: yes
    tags:
      - section7
      - section7.6

  - name: 7.7.1 Ensure Firewall is active (install) (Scored)
    apt: >
        name=ufw
        state=present
    when: activate_ufw
    ignore_errors: yes
    tags:
      - section7
      - section7.7

  - name: 7.7.2 Ensure Firewall is active (Scored)
    service: >
        name=ufw
        state=started
    when: activate_ufw
    ignore_errors: yes
    tags:
      - section7
      - section7.7
