---

  - name: 9.3.1 Set SSH Protocol to 2 (Scored)
    lineinfile: >
        dest='/etc/ssh/sshd_config'
        regexp='^Protocol'
        state=present
        line='Protocol 2'
    notify: restart ssh
    tags:
      - section9
      - section9.3
      - section9.3.1

  - name: 9.3.2 Set LogLevel to INFO (Scored)
    lineinfile: >
        dest='/etc/ssh/sshd_config'
        regexp='^LogLevel'
        state=present
        line='LogLevel INFO'
    notify: restart ssh
    tags:
      - section9
      - section9.3
      - section9.3.2

  - name: 9.3.3 Set Permissions on /etc/ssh/sshd_config (Scored)
    file: path='/etc/ssh/sshd_config' owner=root group=root mode=600
    notify: restart ssh
    tags:
      - section9
      - section9.3
      - section9.3.3

#Regroups sections 9.3.4 9.3.7 9.3.8 9.3.9 9.3.10
  - name: 9.3.{4,7,8,9,10} Disable some SSH options (Scored)
    lineinfile: >
        dest='/etc/ssh/sshd_config'
        regexp='^{{ item }}'
        line='{{ item }} no'
        state=present
    with_items:
      - X11Forwarding
      - HostbasedAuthentication
      - PermitRootLogin
      - PermitEmptyPasswords
      - PermitUserEnvironment
    notify: restart ssh
    tags:
      - section9
      - section9.3
      - section9.3.4
      - section9.3.7
      - section9.3.8
      - section9.3.9
      - section9.3.10

  - name: 9.3.5 Set SSH MaxAuthTries to 4 or Less (Scored)
    lineinfile: >
        dest='/etc/ssh/sshd_config'
        regexp='^MaxAuthTries'
        line='MaxAuthTries 4'
        state=present
    notify: restart ssh
    tags:
      - section9
      - section9.3
      - section9.3.5

  - name: 9.3.6 Set SSH IgnoreRhosts to Yes (Scored)
    lineinfile: >
        dest='/etc/ssh/sshd_config'
        regexp='^IgnoreRhosts'
        line='IgnoreRhosts yes'
        state=present
    notify: restart ssh
    tags:
      - section9
      - section9.3
      - section9.3.6

  - name: 9.3.11 Use Only Approved Cipher in Counter Mode (Scored)
    lineinfile: >
        dest='/etc/ssh/sshd_config'
        regexp='^Ciphers'
        line='Ciphers aes128-ctr,aes192-ctr,aes256-ctr'
        state=present
    notify: restart ssh
    tags:
      - section9
      - section9.3
      - section9.3.11

  - name: 9.3.12.1 Set Idle Timeout Interval for User Login (Scored)
    lineinfile: >
        dest='/etc/ssh/sshd_config'
        regexp='^ClientAliveInterval'
        line='ClientAliveInterval 300'
        state=present
    tags:
      - section9
      - section9.3
      - section9.3.12
      - section9.3.12.1

  - name: 9.3.12.2 Set Idle Timeout Interval for User Login (Scored)
    lineinfile: >
        dest='/etc/ssh/sshd_config'
        regexp='^ClientAliveCountMax'
        line='ClientAliveCountMax 0'
        state=present
    notify: restart ssh
    tags:
      - section9
      - section9.3
      - section9.3.12
      - section9.3.12.2

  - name: 9.3.13.1 Limit Access via SSH (Scored)
    shell: grep AllowUsers /etc/ssh/sshd_config
    register: allow_rc
    failed_when: allow_rc.rc == 1
    changed_when: False
    always_run: True
    ignore_errors: True
    tags:
      - section9
      - section9.3
      - section9.3.13
      - section9.3.13.1

  - name: 9.3.13.2 Limit Access via SSH (Scored)
    shell: grep AllowGroups /etc/ssh/sshd_config
    register: allow_rc
    failed_when: allow_rc.rc == 1
    changed_when: False
    always_run: True
    ignore_errors: True
    tags:
      - section9
      - section9.3
      - section9.3.13
      - section9.3.13.2

  - name: 9.3.13.3 Limit Access via SSH (Scored)
    shell: grep DenyUsers /etc/ssh/sshd_config
    register: allow_rc
    failed_when: allow_rc.rc == 1
    changed_when: False
    always_run: True
    ignore_errors: True
    tags:
      - section9
      - section9.3
      - section9.3.13
      - section9.3.13.3

  - name: 9.3.13.4 Limit Access via SSH (Scored)
    shell: grep DenyGroups /etc/ssh/sshd_config
    register: allow_rc
    failed_when: allow_rc.rc == 1
    changed_when: False
    always_run: True
    ignore_errors: True
    notify: restart ssh
    tags:
      - section9
      - section9.3
      - section9.3.13
      - section9.3.13.4

  - name: 9.3.14 Set SSH Banner (Scored)
    lineinfile: >
        dest='/etc/ssh/sshd_config'
        regexp='^Banner'
        line='Banner /etc/issue.net'
        state=present
    notify: restart ssh
    tags:
      - section9
      - section9.3
      - section9.3.14

