---

  - name: 10.1.1.1 Set Password Expiration Days (check) (Scored)
    command: grep -oP '(?<=^PASS_MAX_DAYS\s)[0-9]+' /etc/login.defs
    register: pass_max_days
    changed_when: False
    always_run: True
    tags:
      - section10
      - section10.1
      - section10.1.1

  - name: 10.1.1.2 Set Password Expiration Days (Scored)
    lineinfile: >
        dest='/etc/login.defs'
        line='PASS_MAX_DAYS 90'
        regexp='^PASS_MAX_DAYS'
    when: pass_max_days.stdout_lines > 90
    tags:
      - section10
      - section10.1
      - section10.1.1

  - name: 10.1.2.1 Set Password Change Minimum Number of Days (check) (Scored)
    command: grep -oP '(?<=^PASS_MIN_DAYS\s)[0-9]+' /etc/login.defs
    register: pass_min_days
    changed_when: False
    always_run: True
    tags:
      - section10
      - section10.1
      - section10.1.2

  - name: 10.1.2.2 Set Password Change Minimum Number of Days (Scored)
    lineinfile: >
        dest='/etc/login.defs'
        line='PASS_MIN_DAYS 7'
        regexp='^PASS_MIN_DAYS'
    when: pass_min_days.stdout_lines < 7
    tags:
      - section10
      - section10.1
      - section10.1.2

  - name: 10.1.3.1 Set Password Expiring Warning Days (check) (Scored)
    command: grep -oP '(?<=^PASS_WARN_AGE\s)[0-9]+' /etc/login.defs
    register: pass_warn_age
    changed_when: False
    always_run: True
    tags:
      - section10
      - section10.1
      - section10.1.3

  - name: 10.1.3.2 Set Password Expiring Warning Days (Scored)
    lineinfile: >
        dest='/etc/login.defs'
        line='PASS_WARN_AGE 7'
        regexp='^PASS_WARN_AGE'
    when: pass_warn_age.stdout_lines < 7
    tags:
      - section10
      - section10.1
      - section10.1.3

  - name: 10.2.1.1 Disable System Accounts (check) (Scored)
    shell: awk -F':' '($1!="root" && $1!="sync" && $1!="shutdown" &&$1!="halt" && $3<500 && $7!="/usr/sbin/nologin" && $7!="/bin/false") {print $1}' /etc/passwd
    register: awk_etc_passwd
    changed_when: False
    always_run: True
    tags:
      - section10
      - section10.2

  - name: 10.2.2.2 Disable System Accounts (Scored)
    command: /usr/sbin/usermod -s /usr/sbin/nologin {{ item }}
    with_items: "{{awk_etc_passwd.stdout_lines}}"
    tags:
      - section10
      - section10.2

  - name: 10.3 Set Default Group for root Account (Scored)
    user: >
        name=root
        group=root
    tags:
      - section10
      - section10.3

  - name: 10.4 Set Default umask for Users (Scored)
    lineinfile: >
        dest=/etc/login.defs
        line='UMASK\t077'
        regexp='^UMASK'
        state=present
    tags:
      - section10
      - section10.4

  - name: 10.5.1 Lock Inactive User Accounts (check) (Scored)
    command: grep INACTIVE /etc/login.defs
    changed_when: False
    failed_when: False
    always_run: True
    register: lock_inactive_rc
    tags:
      - section10
      - section10.5
        
  - name: 10.5.2 Lock Inactive User Accounts (Scored)
    lineinfile: >
        dest=/etc/login.defs
        line='INACTIVE=35'
        state=present
    when: lock_inactive_rc.rc == 1
    tags:
      - section10
      - section10.5

