- name: Initialize ckan db
  command: ckan db init
  tags: skip_ansible_lint

- name: Initialize ckan report db
  command: ckan --plugin=ckanext-report report initdb
  tags: skip_ansible_lint

- name: Initialize ckan ga-report db
  command: ckan --plugin=ckanext-ga-report initdb
  tags: skip_ansible_lint
